### ISSUE TITLE
Ability to Pause Batch Process 

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#104]
The ability to pause a batch process would be really handy. The system resources get really bogged down even with lots of memory and CPU cores so being able to pause while doing other work and then resume afterwards would be very helpful.

**Comment by jonathan-knapp** [comment]
@van-amics can you add this as a high-priority?

**Comment by van-amics** [comment]
Sure, Jonathan. I'll work on this bug right away!




-Bruker Confidential-

**Comment by ChiLyMan** [comment]
Checked and working.
