### ISSUE TITLE
Process Missing Frames During Batch

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#105]
Batch reclassification regularly misses frames:
![image](https://user-images.githubusercontent.com/84986921/130839308-2bec3f66-35f1-45b2-bd96-cd87f48374ab.png)

Out of the 8 files here, only 2 actually fully processed.

Result is the missing frames are all classed as unknowns:
![image](https://user-images.githubusercontent.com/84986921/130839391-1b8a38b6-73c0-45f2-8d32-380e8ac1bd80.png)

Suspect it is due to availability of resources as all other apps are slow during reclassification (despite multi-cores and plenty of memory). This is for a mapped measurement and is using v. 2617

**Comment by van-amics** [comment]
The detailed errors probably in the log file. Please have a look at the log file to see what may cause the frame skipping.

**Comment by jonathan-knapp** [comment]
@MarkGuo7 what is the status of this?

**Comment by jonathan-knapp** [comment]
@Matt-Power can you please tell us if this is fixed?

**Comment by Matt-Power** [comment]
I don't think so - had a measurement do it today or at least something similar - fills in background randomly with a mineral in certain frames. Not sure if it's the same bug though.

**Comment by ChiLyMan** [comment]
Matt, Stupid question but is there data in the original database for those fields? Is it only happening during reclassification?
I've seen something like this, but during measurement, I would just be missing a field or half a field.

**Comment by Matt-Power** [comment]
Happened during classification. Raw data was fine. There is a very similar issue (#215) which is still present.
