### ISSUE TITLE
M4 Investigator - Saved bcf location

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#108]
The saved bcf file and mre are saved where the ivst file is saved independent of any other choices such as in “options”.

**Comment by jonathan-knapp** [comment]
This is an issue with the M4 software, not AMICS. We will be changing this in AMICS 3.3 to have a project structure. At this time we will not be changing this. This item will be closed, as the changes planned for 3.3. We will not change for 3.2.
