### ISSUE TITLE
M4 Investigator - GUI Labels

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#113]
The “WD” concept is not correct M4 and should be labelled differently, i.e. Z stage height. 

This is a generic issue throughout the software where everything is expressed from a SEM point of view. Many labels/buttons/information is thus incorrectly expressed when using the software on a M4 (or microXRF system)

**Comment by jonathan-knapp** [comment]
This is a duplicate of Core #394 that is in the testing workflow.
