### ISSUE TITLE
M4 Investigator - WD value entered manually

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#115]
Can not enter a “WD” (Z Stage height) value manually, it must always be measured or obtained from the system.

**Comment by MarkGuo7** [comment]
If there are no WD values, will be auto-focus. If recorded WD values from the system, then will set to the given values.
These focus values, should set by each sample or do auto-focus. Manual input need a safety check, otherwise may cause trouble.

**Comment by AHM-amics** [comment]
Agreed that from a safety procedure that it is required to record from the system.
