### ISSUE TITLE
M4 Investigator - M4 system stabilisation

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#117]
The control for the kV and uA current needs to wait longer to stabilize. For example, when changing from 100uA to 200uA it starts the measurement at some value different to 200uA, for example 185 uA, that is, the M4 system hasnt yet stabilized from the changing values.

**Comment by MarkGuo7** [comment]
Need confirm with Nigel on M4.

**Comment by MarkGuo7** [comment]
Duplicate with #120
