### ISSUE TITLE
M4 Investigator - "Switch" Button not working 

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#119]
Uncertain as to what the “switch” option does. If it is to deactivate a measurement, it does not work.

**Comment by MarkGuo7** [comment]
Need confirm with Nigel on M4.

**Comment by bernie1034** [comment]
Added a comment in GitHub that didn't link to here. But an update - the switch "sort of" works. If you have two measurement areas, you can switch off the second and have it stop. However, for more than 2 measurements, if you switch off one in the middle of the run, it prompts an error on the M4: "Fehler bei Bereichsprufung" (translates as "Range check error"). You need to manually hit the error dialogue "OK" button multiple times before this goes away, and only then will AMICS move on to the next measurement.
