### ISSUE TITLE
Utilize "Expand" and "Collapse" functionality in other areas of the software 

### ISSUE THREAD

**Issue by knapp-amics** [Bruker-Amics/bugs_features#12]

**Comment by MarkGuo7** [comment]
Where? :)

**Comment by knapp-amics** [comment]
No idea .. just collapse stuff! Lol

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by AHM-amics** [comment]
@knapp-amics, @MarkGuo7 This was a request from me to include in the mineral groupings popup box. From my side, this was completed and I have tested it and it works.
