### ISSUE TITLE
BUG-MINOR_AMICS_M4 INVESTIGAOR_MEASUREMENT:System Hangs when changing kV values

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#120]
Sometimes when changing the kV and uA the system hangs, that is it doesn’t reach the correct conditions and times out or stops working. After which a hard software reset is required.

**Comment by MarkGuo7** [comment]
Need to figure out how the api works. Close for now because this function doesn't work for the moment.
