### ISSUE TITLE
BSE Adjuster No Minerals in Field

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#123]
I am trying to adjust some mapping measurements but I get the following error:

![image](https://user-images.githubusercontent.com/84986921/131545474-572bfa4f-833d-494c-bbdf-44f9c8d0350b.png)

Trouble is that the sample is >80% Dolomite_1 so very abundant in every field:

![image](https://user-images.githubusercontent.com/84986921/131545899-43d5faa2-e0f0-47c4-957a-3e5ba51501bd.png)

This seems to only happen on mapping measurements (segmented images seem OK).

**Comment by jonathan-knapp** [comment]
Can you test with the Beta to see if this is fixed?

**Comment by GGloy** [comment]
@MarkGuo7  This seems to work only if I increase the dot size. Is that correct?

**Comment by MarkGuo7** [comment]
Need test with spot size one on mapping mode.

**Comment by GGloy** [comment]
@MarkGuo7 Still does not work if the dot size is 1, but otherwise work fine

**Comment by ChiLyMan** [comment]
Any update on this one? I tested on the limited mapping data I have and it worked. 
Is Dot Size = Spot Size?

**Comment by GGloy** [comment]
Dot Size  is the area displayed representing the X-ray point (number of pixels) Hope that makes sense!
You can close the ticket.

**Comment by ChiLyMan** [comment]
As commanded :)

**Comment by Matt-Power** [comment]
Let me test. It wasn't an issue with the dot size, just that the image was not showing at all. I think that this may be a "block" measurement though. Let me check and get back to you.

**Comment by Matt-Power** [comment]
Sorry, replying to the wrong issue (duh). Let me check that it works with the two measurement types though.

**Comment by Matt-Power** [comment]
Works. All good.

**Comment by ChiLyMan** [comment]
Matt just confirming this is for issue #123.

 

Not for the missing frames issue #105

**Comment by Matt-Power** [comment]
For this issue #123
