### ISSUE TITLE
Bug - cant delete an oretype 

### ISSUE THREAD

**Issue by GGloy** [Bruker-Amics/bugs_features#125]
In version 3.2.0.3 when selecting to remove an oretype get "unspecified error"

![image.png](https://images.zenhubusercontent.com/60af4a22d2c5ea1082755c53/1ea05180-7b5b-4593-b046-e702cf20385c)

**Comment by AHM-amics** [comment]
Hi All (Gerda),
Yes. I have had this issue. This error occurs in AMICS Standard Manager. However, the Ore Type can be deleted from within AMICS Process. There are also potential differences between the functionality of AMICS Standard Manager and controlling the Standards from within AMICS Process.

**Comment by bernie1034** [comment]
I can delete Ore types from v3.2.0.3. I do this within Process (I thought Mineral Standard Manager had been retired and with functionality transferred to Process?).

**Comment by MarkGuo7** [comment]
I will close this item for the moment. 
All the oretype operations should be in Processing and I will remove the old mineral standard manager out of installer.
Let me if you have any other issues or suggestion around oretype.
