### ISSUE TITLE
Mixing generates incorrect mix spectra output

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#128]
I am not sure of the seriousness of this issue.

However, in using a simple system of olivine, fayalite and forsterite endmembers, the AMICS mixing does not generate the correct mixes. 

It overestimates the Si and Mg, so that in the final mixes a Fo80 olivine becomes Fo20 or 30 in the mixes. I have the synthetically created spectra for the range of Fayalite to Forsterite and they do NOT match when creating the mixes from the two endmembers in AMICS

Mark - what is the "formula" or "instructions" for the mixing?

I think a quick meeting to discuss is required so I can demo my concerns.

**Comment by MarkGuo7** [comment]
@AHM-amics We discussed this morning and the best way is maybe to have spectrum generator that can generate proper mix spectrum with the given element compositions. Could Esprit team help?

**Comment by AHM-amics** [comment]
This is link to issue #135. I have commented there. I will talk this side. However, I am not sure this is the solution. I do not believe we can create synthetic e-beam spectra. I will discuss here.

**Comment by MarkGuo7** [comment]
As Andrew suggested, better to mix spectrum by the life time, but currently we don't have this value yet. And we need to figure out what the life time will be if the standards generated from the combined result xrays.

**Comment by jonathan-knapp** [comment]
What do you mean by lifetime?
________________________________

**Comment by MarkGuo7** [comment]
Each Xray captured has real time, life time and dead time. Normalize xray by life time make more sense than by total counts, which is the current way to mix.

**Comment by jonathan-knapp** [comment]
Live time?
________________________________

**Comment by MarkGuo7** [comment]
Oh, I see. Called it life time couple of years already :)

**Comment by MarkGuo7** [comment]
Talking with Thomas, so many factors included in the xray file (spx file), so there is no way to manually to mix them properly.
So I will close it for the moment. May need Berlin team to give us an API to mix the spectrum that Esprit can Quant properly.

**Comment by AHM-amics** [comment]
Dear Mark / Thomas,

Thanks for the information, however I am a little confused.  Currently the normalization and subsequent mixing is based on the number of counts.  This needs to change to be based on normalizing based on the “live time”.  This should be recorded in the spx (or am I wrong).  Therefore, the mixing can be accurately done if this factor “live time” is used rather than counts.

I am not sure what are these other factors? I know there is normally lots of factors in an spx file, i.e. all the is need for qunatifcation amongst other factors, but for the current mixing idea in AMICS to be useful, especially for solid solution mixes, it is only “live time” that is relevant.

Please advise as this is a critical issue and causing problems for clients.  I would like to discuss further.

Thomas – any comments?.

Saludos,
Andrew

**Comment by MarkGuo7** [comment]
@AHM-amics Morning Andrew

Thanks for you quick reply, let's talk with Thomas when there is time lot fit all of us.

Mark
