### ISSUE TITLE
Calculation Table Appears Then Disappears

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#132]
OK, I thought that taking a video would show this better than I can describe - link sent direct to you. I overlaid the resource monitor so you can see how much memory it is using (basically all 32Gb of it)

When I open up a file to extract simple modal data, the table loads (takes a while) but then instantly disappears and Process starts to use massive amounts of memory (in the video the AMICS window goes black - in reality it is just sitting there as normal but doing nothing). The memory use just keeps on building and building and then at points, drops back down until finally, the table loads. This measurement literally took over 5 minutes to load so that I could extract simple modal data. For this project I have 12 samples so in excess of 1 hour for basic data extraction.

The batch also has this bug but you cannot see the progress at all, just the crazy memory use in the resource manager. And for the reason outlined in other issues, I cannot use a batch calculation because all the data gets truncated. 

I am using an i7 10th gen with 32Gb of memory - this is not a slow computer.

**Comment by jonathan-knapp** [comment]
@bernie1034 have you seen this? I have not. I did not see this video. Can you re-send the video to everyone?

**Comment by bernie1034** [comment]
@knapp-amics  Yes, I have seen this. I replicated while on a call with Matt.

**Comment by Matt-Power** [comment]
Link to video on a OneDrive share re-sent. Let me know if you have any issues.

**Comment by ChiLyMan** [comment]
Do we have any update on this? I've not seen it myself.
