### ISSUE TITLE
Wrong Mineral Legend When Extracted From Calculation Tab

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#133]
If you export a mineral legend when the calculation table tab is active, the legend extracted is the Primary Mineral Grouping, even if the correct mineral grouping is selected in both the sample images tab and the calculation table tab. If you switch back to the sample images tab (which often means a long wait), the correct mineral legend will be extracted.

**Comment by GGloy** [comment]
This has not changed ......vs 3.3.0.1158

**Comment by GGloy** [comment]
This ticket can be closed. Thanks!
