### ISSUE TITLE
Mixing Spectra Calculation is Incorrect

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#135]
As I understand it, the mixing of spectra first requires that each spectra should be normalized. This process is incorrect, and generates incorrect mixed spectra.  The spectra should be normalized based on time (either live or real time). These values will be included with each spectrum. The use of normalizing base on total counts will create incorrect spectra, the severity of which will vary depending on the elements present. 
In an example this is obvious using Olivine because it is essentially a two-element system where Fe and Mg change. This is further exaggerated because it is a MicroXRF analysis and not a SEM (e-beam) analysis where the same issue occurs, but not as severe. In this case, the microXRF has an extreme Fe intensity compared to Mg (by orders of magnitude). Therefore, normalizing by counts will greatly overestimate the Mg concentration, and thus the mixed spectra will be wrong.

**Comment by AHM-amics** [comment]
AMICS Process v3.1.1.2617

**Comment by jonathan-knapp** [comment]
We need to address with Timo

**Comment by AHM-amics** [comment]
I have the synthetic spectra module from Timo and it works well. However, this will not solve all the issues for AMICS. This is because to create the synthetic spectra it needs an Atomic Formula. Two main issues amongst others are: 1. This is only for microXRF spectra and not SEM ebeam spectra. 2. Not all spectra used for matching have a "correct" or "accurate" associated forumla, especially any user created spectrum, especially from the sample itself, will not have a correct formula to use for mixing spectra.

**Comment by jonathan-knapp** [comment]
@AHM-amics we will have a project early in the new year to address spectral mixing. Hitachi has an expert that has also been working on this. In release 3.4 or 3.5 I want to bring spectral simulation into AMICS and have the ability to generate mixes or sythitic reference spectra. I don't want to spend any
