### ISSUE TITLE
AMICS Process Standards not fully functional unless a measurement is open

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#136]
AMICS Process v 3.1.1.2617

It is not possible to use AMICS Process Standards without opening a sample measurement first.

For example, if I wish to edit a Mineral List or import spectra etc, the buttons in the standards tab are greyed out until I open a measurement.

**Comment by jonathan-knapp** [comment]
This has been addressed. Simply have to pick the checklist option.
