### ISSUE TITLE
AMICS Process Standards Functionality - missing capabilities

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#137]
AMICS Process Standards v3.1.1.2617

Some simple functionality in the AMICS Process Standards is missing or not obvious as to how.

1. It is not possible to change an "Ore Type" name in AMICS Process Standards (only in Standard Manager)
2. It is not possible to scroll with the mouse for choosing a Standard (Ore Type) to use or edit when the list of Ore Types is longer than can be displayed. First you must hover over any Ore Type with the mouse (dont click) and then use the down arrows.

**Comment by jonathan-knapp** [comment]
The oretype will change in v. 2.3. THanks for the comment, but it is going to be a lot different. Will update you with the plan soon/
