### ISSUE TITLE
AMICS Process Standards AAN Calculation is Incorrect

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#138]
AMICS Process v3.1.1.2617

The calculation for AAN when entering a formula in a standard is wrong. 

This now yields different values to those stored in the database under the AAW column header.

Question: The AAW (Average Atomic Weight) is an incorrect term. The values in this column in the database are the AAN (Average Atomic Number). The AAW should be the AAM (Average Atomic Mass), which is something different.

**Comment by MarkGuo7** [comment]
@AHM-amics Could we discuss it when you have time and what's the right way to calculate from formula? Thanks

**Comment by AHM-amics** [comment]
@MarkGuo7 I am generally available all next week. Let me know which Day is best for you - morning my time / afternoon yours.

**Comment by MarkGuo7** [comment]
@AHM-amics Hi Andrew, do you have time today? Your morning, my afternoon?
