### ISSUE TITLE
Import multiple spectra 

### ISSUE THREAD

**Issue by knapp-amics** [Bruker-Amics/bugs_features#14]

**Comment by Sperrylite-MattNg** [comment]
File formats allowed should include spx (bruker files), ems and msa files (DTSA-II); also possibly spc (EDAX files)

**Comment by MarkGuo7** [comment]
You can import multi spx files now. 
Other file formats need to confirm.

**Comment by knapp-amics** [comment]
Thanks Mark. Let's close this one and make. Anew one for other file formats.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
