### ISSUE TITLE
Testing with GTK

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#142]
Need time to test with GTK. They got AMICS for valuation. Anybody knows details about this customer?

![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/cf566574-fefc-4751-ab97-6cbb32cff1da)

**Comment by MarkGuo7** [comment]
They bought license of 2.3 but missing the API option.
The 1.9 version on their system works.
It's a FEI system with MLA.

**Comment by AHM-amics** [comment]
Hi Mark,

As I understand it the have an official AMICS licence for many years. They purchase a FEI MLA/QEMSCAN and also purchased a AMICS for this system. This was facilitated by Sam. I suspect they are keen to get AMICS runnign smoothly as they have an M4+ with AMICS now and I will be doing the training in the first week of October. So they will have both SEM and M4 AMICS.

**Comment by GGloy** [comment]
YEs they have bought AMICS its not a trail
