### ISSUE TITLE
Batch Calculations Not Working For Association Data (ver 3.1.1.2617)

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#144]
Batch calculations for Mineral Association data do not work. The batch process appears to work (the progress window appears to go to completion) but no datasheet is generated. 

I have not tried many other data types but modals and liberation do appear to work.

**Comment by jonathan-knapp** [comment]
@Matt-Power how would you want this output to look like? We can only do this as a repeated table (not combined), but give us an idea of what it will look like.

**Comment by Matt-Power** [comment]
Tab per sample would be fine.
