### ISSUE TITLE
Measurement starts on wrong sample 3.2.0.87

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#153]
Using the 28 block holder, the hole 7 is the first sample to be analysed even though samples are sorted in position order.

It appears that the samples are measured by default in rotation order (0 rotation samples, then 90 etc) and there is no obvious way to change this. This makes workflow management very challenging, especially where different projects with different priorities are in the same holder.

Please include option to prioritise by position number and / or by the order specified in Investigator.

Ultimately, what is needed (from a workflow, ease of setup and efficiency of stage movement point of view) is the ability to move to an X-Y position and then rotate in each sample sequentially. I think that is already on the list but would be a significant improvement.

**Comment by GGloy** [comment]
According to my testing the order is working now, I think this can be closed.

**Comment by ChiLyMan** [comment]
As per last comment
