### ISSUE TITLE
Make sure there are UUID for all user standards.

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#155]

**Comment by Matt-Power** [comment]
Not sure if this is related but when you create a new standard from a measurement and copy data from the library, the UUID is only assigned if you edit one of the properties. If you just accept the data without changing, no UUID is generated. It is possible to force a UUID to be assigned (e.g. by clicking on one of the properties boxes) but not if the standard has come from a pre-existing list (i.e. if an ore type is duplicated then all of the original standards cannot be edited).

**Comment by ghost** [comment]
UUID also not automatically generated when a mix spectra of two minerals is made. UUID only generated when properties for the mix is modified.
