### ISSUE TITLE
Three phase mixes 

### ISSUE THREAD

**Issue by knapp-amics** [Bruker-Amics/bugs_features#16]
![image.png](https://images.zenhubusercontent.com/60a274843870252752494569/dd03afda-6f46-403f-a18b-6ff93569730d)

**Comment by MarkGuo7** [comment]
See #15 :)

**Comment by knapp-amics** [comment]
This is one of the most often requested features. Can you expand on why this may "not be a good idea?" 

Thanks Mark

**Comment by knapp-amics** [comment]
@MarkGuo7 can you put an estimate on this? I want this in the beta if possible. Lets put a warning if it is going to generate more than 60 or 70

**Comment by jonathan-knapp** [comment]
@MarkGuo7 for clarification... when we say three-phase mixes we mean combining three spectra into a single spectrum.  Has this been done? Nigel provided the chart... 

I went to look for that but found not find it.

**Comment by MarkGuo7** [comment]
Nope, no time to do it yet.

**Comment by jonathan-knapp** [comment]
Ah, ok. It was in the "Done" workflow. Let's move it to the backlog and try to do it when we have time for the beta. It's important to the M4 users. This was very high on the list from Andrew Menzies. I think that the most quick and dirty will be ok to start. See how it works...
________________________________
