### ISSUE TITLE
Run measurements the order from the list

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#162]
If there are rotations, AMICS will try to group the same rotation together to run.
Maybe need an option to run as exactly what customer setup?

**Comment by Matt-Power** [comment]
Yes please. Running in the specified order should always be the default (and is imperative to have this) and the group by rotation should be an option. The option to rotate in samples (like a carousel) on the 28 block holder is really, really important too.

With the 28 block holder, the sample order is completely jumbled which makes managing multiple projects in the same holder tricky and extremely prone to loading errors. It is also impossible to change priorities after the samples have been loaded as re-ordering the samples in AMICS only works within the rotation groups.
