### ISSUE TITLE
Centralize the result folder at remote machine is really slow.

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#163]
Current solution is the avoid remote centralize folder.

**Comment by Matt-Power** [comment]
So are you saying that the basic functionality to write results to a central server location will not be fixed / included? This is a really big deal with respect to data backup and many, many aspects of project management.

**Comment by jonathan-knapp** [comment]
Matt,
It's part of BiFROST. We will write to a local folder and Sync. We can have option to remove from local storage once it's in the central location. The size of the files and data structure makes writing directly to network storage (without a local intermediate step) not feasible. To have a client where we write to a local drive and then it moves the data to the central server is how most applications that work with very large files have to work. It would probably be possible with a local gigabit lan and a special TC P-ip card, but the file sync option just simply is more reliable without switched bits or lost information.

For now we need to make sure that we're saving to a local drive and this will be much more seamless after the BiFROST implementation. Hopefully measurements will just "show up" everywhere where they are needed.
________________________________

**Comment by Matt-Power** [comment]
I was thinking of this at the data collection and processing stage (implementing at the BiFROST stage seems several steps too far down the line - I will have moved manually for processing, editing etc long before then). The main concern is that raw data needs to be preserved and written to project locations before the data reduction step (which may be carried out by several people). Ideally the local PC is always in use with measurements so manually copying / backing up large amounts of data into project folders on a server is going to cause reliability problems to the run, and is extremely prone to errors and data corruption. Local drives are a pain to back up too so are at significant risk of data loss on failure.
 
Measurements could previously be saved to a mounted network drive without issue but it seems that the implementation of the centralised results folder has thrown an issue somewhere so is this not a bug?

**Comment by jonathan-knapp** [comment]
AMICS must always access a locally mounted drive. The R/O requirements are too high for a network drive. At the earliest stages the files will be saved to a local HDD or SDD that will sync to the cloud. You can implement this today by pointing your investigator to a network syncing BOX, Google Drive, or OneDrive folder. AMICS gets the R/O it needs and the data - even at the early stages - is sent to the cloud.

We are planning a "check out" system, but the details are not finalized. It is in scope to organize the transfer of files to multiple remote locations. However, this will be either FTP from a local folder  or sync folder and not a mounted network drive. We just write too much data for that. It will be we happen. Not with the current architecture - and that's a network issue, not a AMICS issue.

I want to reiterate so you understand: the transfer of the fill file (not just the results) from the data collection site to the location of data reduction is in the scope of BiFROST. You could have a working solution today if you stop useing a mounted network drive that transfers all data with a IP protocol and switch to a folder sync. The bottleneck is the network, not AMICS.
________________________________

**Comment by Matt-Power** [comment]
OK, thanks and I get that the network will be a bottleneck. 

The issue here though is that AMICS takes literally 30 minutes or more to start if the centralised folder is enabled.

**Comment by jonathan-knapp** [comment]
Please send screenshots of the setup and the location of the folder. If it's still taking a long time when not on a network mounted drive than Mark will take a look. This centralized folder will be outdated with the 3.4 project though. The new project structure will supersede this grater. This is a stopgap measure.
________________________________

**Comment by MarkGuo7** [comment]
@Matt-Power Hi Matt, thanks for your feedback. I would like to give it another try since it is important. May I have another look of your computer when you have time?

**Comment by Matt-Power** [comment]
Hi Mark,

Thanks and no worries. Can you have a look mid-next week please? It is a long weekend and the system is set to run some very big measurements which can’t be interrupted but they should be finished by Tuesday (my time). I’ll drop you a note when they are done / system is ready (I’ll try not to forget!).

Thanks,

Matt

Matthew Power Ph.D.
d - 604.420.0117
c - 604.880.7656
