### ISSUE TITLE
Save Mapping results as Particle results then you can deagglomerate them etc.

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#167]

**Comment by jonathan-knapp** [comment]
@MarkGuo7 I want to consider a change for AMICS 3.3.1 - can we only measure in one mode and switch between block and particulate mode in Process? Having a truly uniform file structure (with segment ID for each pixel, for example) will make it a lot easier for external parties to use the files.

**Comment by GGloy** [comment]
@knapp-amics can you close this, and make the one measurement mode a new entry?
