### ISSUE TITLE
Remove User STD Manager out of source code

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#169]

**Comment by GGloy** [comment]
Mark, is this for version 3.2?

**Comment by MarkGuo7** [comment]
I removed it from 3.3 source code.
Still with 3.2.

**Comment by GGloy** [comment]
Did you do anything for the optimize X-ray position? What do I need to look for? (this is also not 3.2 right?)

**Comment by MarkGuo7** [comment]
This is not about xray position. 
I removed the Std Manager source code out of 3.3, and there will be no std manager included in the installer anymore.
We didn't maintain these source code for quite long time. Let me know if you still need it.
