### ISSUE TITLE
Formula parser doesn't work and normalisation splits all elements evenly

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#174]
Looks like the formula parser has stopped working in 3.2.0.128; if I change the formula and then hit the parser button, nothing changes. The existing data is kept but new elements are not added and the chemical data remains unchanged.

If I then hit the normalisation button, whatever elements are already there are divided equally (i.e. if there are 3 elements listed, they are all reset to 33.33, if 4 listed, 25 etc etc).

**Comment by GGloy** [comment]
Can be closed
