### ISSUE TITLE
Mineral Image Disappears After Stitching (Maps)

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#175]
The mineral image disappears after I stitch a mapped measurement and all data fields are empty. It doesn't matter which layer is selected - all are blank. The BSE image remains though.

I have to re-open the file for it to reappear.

**Comment by jonathan-knapp** [comment]
@Matt-Power is this still happening?

**Comment by Matt-Power** [comment]
Yes - still happening in 3.2.0.236

**Comment by jonathan-knapp** [comment]
I was able to reproduce this in 3.3.0.1382. 
![image.png](https://images.zenhubusercontent.com/60a274843870252752494569/a2b45557-c5ea-4892-bdaf-afd88eab3c05)
*Steps to Reproduce*
1. Open any mapping measurement
2. Select "Do Auto Field Adjust" 
![image.png](https://images.zenhubusercontent.com/60a274843870252752494569/841309fa-1263-4dbf-899e-ea28d68dd74a)
3. Data is empty

*Workaround*
Close measurement and open. Stitching is preserved, and data layers reappear. 

*Impact*
Many added steps (open and close a measurement) when working with mapping measurements. Total disruptions. 

@MarkGuo7 this is a bug that was logged on October 27, 2021. It is now over a year old. This one needs to be addressed as soon as we are finished with the current project and back to bug bashing.

**Comment by Matt-Power** [comment]
Just to add, this has been happening to me with segmented images in 3.3.0.1315 too (happened just now) so maybe not specific to mapped measurements.

**Comment by GGloy** [comment]
I could still repeat this in version 1508 - however fields where not blanck but reverted to dots.
![image.png](https://images.zenhubusercontent.com/60af4a22d2c5ea1082755c53/fdbc4858-21e2-4ec2-9c44-a2f0a77831ec)

**Comment by Matt-Power** [comment]
Ditto. The images are there but the dot size is either 0 or 1 (either way too small to see when at a normal zoom). The dot size selection box does not revert to 1 (which is good), it's just the actual dot size that is wrong. You can get the image back by toggling the dot size but this takes a while for a big image.

**Comment by jonathan-knapp** [comment]
@MarkGuo7 just tested and this is still happening. The dot size resets. We need to make sure it stays totally filled in.

**Comment by GGloy** [comment]
@MarkGuo7 this is still happening in vs 1812.

**Comment by ChiLyMan** [comment]
Gerda, did you try onf 1829? I just gave it a try on this version and cannot replicate.

**Comment by GGloy** [comment]
Chi, just tried it, and we can close this issue.
