### ISSUE TITLE
The screen ratio doesn't work on M4 overview image

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#176]
M4 always keeps the 1:1 ratio.

If choose 4:3 from Tools, the overview will look like:

![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/52d02e47-64bd-46df-a4bb-7c257e9f145c)

**Comment by jonathan-knapp** [comment]
Is this fixed and tested?

Jonathan P. Knapp Ph.D.
Market Segment Manager
AMICS Product Manager
1 (720) 236-2129
***@***.***

________________________________

**Comment by MarkGuo7** [comment]
Gerda said it is good enough now :)
