### ISSUE TITLE
28 Block Holder Measurements Fail on Rotate

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#177]
After rotating to the next group of holes, measurements usually fail 30-40 seconds into the measurement. This is with Investigator version 3.2.

Holes with 0° rotate run OK (e.g. 7, 8 etc) but when the measurement proceeds on to the next rotation group, it generally fails on the first sample in the group (not always but most times). 

It can be restarted without issue by clearing the measurement and hitting the start button but it means that use of the 28 block holder is severely restricted as it will fail after each rotate i.e. up to 3 times. This is inevitably late at night, on weekends or both so substantial instrument time is lost.

This is a very significant problem as it means that the 28 block holder is totally unreliable and virtually unusable (as well as difficult to load and set up - the completely jumbled run order is not workable and sample mix-ups are inevitable).

**Comment by MarkGuo7** [comment]
@Matt-Power Sorry reply late. Any chance you can send me the logs of these failures? Thanks

**Comment by jonathan-knapp** [comment]
@Matt-Power has this been fixed?

**Comment by Matt-Power** [comment]
Not sure if fixed per se but with AMICS control of stage, it's not an issue (stage movements are quicker so doesn't time out). Might still be there when Esprit controls stage though.
