### ISSUE TITLE
Particles missing on fine samples

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#179]
Some brighter small particles missing on the fine sample results, need to find out why and how to improve it.

**Comment by GGloy** [comment]
Improved significantly - this can be closed

**Comment by jonathan-knapp** [comment]
Please close anything that can be closed

Jonathan P. Knapp Ph.D.
Market Segment Manager
AMICS Product Manager
1 (720) 236-2129
***@***.***

________________________________
