### ISSUE TITLE
Cannot modify properties of mineral definitions synced from other ore types

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#181]
If I sync mineral definitions from one ore type to another, I cannot change any of the properties in the destination ore type. Fields such as state, chemistry, density etc etc are all inaccessible. These need to be editable after transfer to the destination ore type.

**Comment by MarkGuo7** [comment]
@Matt-Power Hi Matt

Is it still there? Could you show me how to repeat it? Thanks

**Comment by GGloy** [comment]
Matt, it seems if I sync then press the reload option to "refresh" the mineral list I can edit.

**Comment by Matt-Power** [comment]
@GGloy and @MarkGuo7 Sorry, forgot to reply earlier but I think this was fixed a while back. Haven't had any similar problems recently. Thanks.
