### ISSUE TITLE
BUG-MAJOR_AMICS-3.3.0.1660_PROCESS_EXPORT: Batch export puts white lines on frame boundaries in matrix mapped images

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#183]
When I run a batch export to extract mapped images, white lines appear at the frame boundaries. If I manually export the same image, all is OK and there are no white lines. This unfortunately means that the batch export for mapped images can't be used as it messes up any post-AMICS calculations. 

For what it's worth, I have the dot size set at 5 for the measurements (so there is no white space around the pixel). Default in the options is also set at 5.

**Comment by jonathan-knapp** [comment]
@Matt-Power is this still happening?

**Comment by Matt-Power** [comment]
Occasionally. It used to be all samples but now it is only random ones (occasionally 1 per project). All samples are the same so no idea why one can be different. Not sure if I can ever reproduce it though as it appears to be random.

**Comment by jonathan-knapp** [comment]
Ok. Very strange. What we are going to need is a batch that is causing this issue. When you see it next, let me know. We may have to transfer all of the files to figure out why it's happening.

**Comment by Matt-Power** [comment]
Just had real problems with this. Some samples showed the lines and some didn't - it appears to be something to do with the stitching but it's not that straightforward. Details are:
Marc and I split a project into two - he stitched one half and I did the other. We used the same version (3.2.1.261 - there are some nasty bugs in 3.3 that mean that we cannot use any of the versions of that). I then processed all samples in the same way. Only the samples that I stitched had the white lines - all of the ones Marc stitched were fine. However... I had to re-stitch a bunch of the ones Marc did (cleared all stitching and then re-did it). Even after restitching on my computer, there were no white lines on the images i.e. they were still OK so it seems that there is something persistent in the mre files.
I've reprocessed and messed around with the files endlessly and it's always the same - the files that I initially stitched have while lines, the ones that Marc did initially do not, even if I restitch or reprocess etc etc.
If you export manually, the images do not have lines, it's only when you run a batch extraction. It only appears in mapped measurements.
@MarkGuo7 I will send some files that show the issue - if you run a batch on them, you'll see that some have lines, some don't.

**Comment by ChiLyMan** [comment]
@Matt-Power I tried to recreate the white line issue we were discussing about yesterday. I first started by doing a batch export of the BSE image using AMICS Process 3.3.0.1406 using the Project Manager batch exporting option, but this didn't create white lines . I then did a batch export using the Batch button option in AMICS Process 3.3.0.1406, which also didn't create white lines in the BSE exports. I then did batch exporting in 3.2.1.0 using the Batch button but still cannot recreate the white lines. 
Finally, I deleted the databases and redownloaded the data from OneDrive and did another batch export using the Batch button in 3.2.1.0, and still could not recreate the white lines.
Did you also select "stitch images" during the batch exporting?
[Stitching_Issue.pdf](https://github.com/Bruker-Amics/bugs_features/files/10042785/Stitching_Issue.pdf)

**Comment by Matt-Power** [comment]
@ChiLyMan the lines only show themselves in the mineral images - did you look at those?

**Comment by ChiLyMan** [comment]
@Matt-Power OK I can now see it in mineral maps on 002 and 065RR (though note 002 looks like the bug you mentioned of have two data sets in same measurement).
I need to chat with Mark, because when doing the batch export an overview image is also produced (grey scale) which have "black" lines in 002 and 065RR, and not in 001RR.

**Comment by Matt-Power** [comment]
OK, thanks, glad I'm not going crazy. 001RR was the one that was initially stitched on a different machine so does not have the lines.

002 does have that issue with the two datasets - can't remember how I triggered it but I think it happens in Investigator. Basically it writes two measurements into the same folder (or somehow duplicates the measurement within the folder). In that case, the measurement was 56 frames but there are 112 field measurements. If you delete 57 on, the measurement looks fine. It doesn't happen a lot so and not sure when / how it happens so haven't logged but will keep an eye out.

**Comment by ChiLyMan** [comment]
Just found another sample from FLEXSEM analysis which also shows these white lines in the mineral map images.

@MarkGuo7 I'll send you the database via OneDrive

![image](https://user-images.githubusercontent.com/84643841/212176960-212b157c-abba-4082-8823-7e452feda900.png)
![image](https://user-images.githubusercontent.com/84643841/212176994-bde83c52-1001-40c8-8ba5-663c7f5bb55e.png)

**Comment by MarkGuo7** [comment]
Thanks Chi, I will take a look

**Comment by Matt-Power** [comment]
Unfortunately still present in v 3.3.0.1660

**Comment by Matt-Power** [comment]
3.3.0.1701

Looks like this issue is fixed! Thank you!!

**Comment by Matt-Power** [comment]
Sorry, spoke too soon.

Issue is still there but random - some images exported in a batch will have the lines, others do not.

**Comment by jonathan-knapp** [comment]
I was so happy when you sent that email about the issue being gone. It will go back on the Bug bash list.

**Comment by jonathan-knapp** [comment]
@MarkGuo7 this one has become mission critical and needs some attention first.

**Comment by jonathan-knapp** [comment]
@Matt-Power this item has been added to the "In Progress" queue.

**Comment by Matt-Power** [comment]
3.3.0.1903

Just tried to recreate this and no white lines have appeared so far (yay!). I'll extract a few more projects to be certain - maybe keep open for a few days just in case.

**Comment by Matt-Power** [comment]
Tried this again in 1961 and think it's safe to say it's fixed. Thank you!

**Comment by Matt-Power** [comment]
Unfortunately, these are back in version 3.3.0.255

**Comment by Matt-Power** [comment]
Still an issue in 2074

**Comment by ChiLyMan** [comment]
@Matt-Power can you send me a few of these data sets. I just tested on newer build on the sample data you gave me before and the white lines are not there.

**Comment by ChiLyMan** [comment]
@MarkGuo7 Checked the data set from Matt and the lines (linked to the boundary line between fields) are only present during batch export. Doing a single manual export (i.e. Export Image) does not generate these white lines. 
In the example image below, you can see the boundary lines from AMICS Process, then when doing a batch export you can see the white lines that are not present during a manual single sample Export Image operation.
![Examples](https://github.com/Bruker-Amics/bugs_features/assets/84643841/84f797f4-668c-4016-ae01-95f246f17ce9)

What is interesting is if you imagine the field stitching happening in the order left=>right and top=>bottom, the white lines represent the field boundary of the field stitched later on. If you look at my basic example below, field 1 in dark blue is laid down first. Then field 2 in green is laid on top of field 1. Then field 3 in orange is laid on top of fields 1 and 2, and finally, field 4 in light blue is laid on top of 1,2 and 3. Now if I trace out the field lines for the "exposed field (i.e. those that have not been overwritten by another field) you will see the red field lines mimicking the white lines. 
![image](https://github.com/Bruker-Amics/bugs_features/assets/84643841/fdb517d2-f45d-480d-a8a1-dd5d25d5ecd2)
Stupid question, but assuming the batch image export is not the same code as the single export image code, there hasn't been a white border added to field images?

**Comment by MarkGuo7** [comment]
Hi Chi & Matt

Could you send me one of these samples? 
My excuse is that I am working on a new computer now, so want to build a new issue datastore set.
But the real reason is, I am not that organizing person to keep things sorted. Sorry about that.

So, could you send me the dataset when you report an issue?
Especially the batching issues, because I am working on it for the moment.

With thanks

Mark

**Comment by MarkGuo7** [comment]
Sorry, I got the dataset that Matt shared. 
Should check all my emails before asking.
My bad

**Comment by MarkGuo7** [comment]
Hi Matt

Could you try this new build to see if any better?
https://bruker-my.sharepoint.com/:u:/p/junfeng_guo/EfX28N76kvpJtb25qtfhEs0BuT9sL8QFkoYbFlKNROm4jw?e=wav7Kn

By the way, tomorrow is public holiday here

**Comment by ChiLyMan** [comment]
I cannot test this on the data set I know generated these white lines before as version 3.3.2 fails to open these three sample data. I can open the data in version 3.3.1 and it will open in AMICS Tools version 3.3.2, but fails to open in Process.
@MarkGuo7 I will send you these dataset via OneDrive link so you can see why this is failing.

Just for completeness the log in AMICSTools shows the following:-
2024-6-12 13:47:08.782 AMICS::AMICSTool::CAMICSToolDoc::ImportIADImageFile(1291) [Trace]: Start to open file: E:\AMICS_Test_Data\White Lines\VL-22206-001RR-Map\VL-22206-001RR-Map.mre
2024-6-12 13:47:08.923 AMICS::Datastore::MineralTagTable::ReadMineralTagList(34) [Info]: There are no mineral tags.
2024-6-12 13:47:09.044 AMICS::Common::CAMICSFieldLoader::OpenResultFile(100) [Trace]: Start to load field images (56)
2024-6-12 13:47:14.336 AMICS::Common::CAMICSFieldLoader::OpenResultFile(145) [Trace]: Load field images succeed. Fields: 56.
2024-6-12 13:47:14.467 AMICS::Common::CAMICSFieldLoader::UpdateScanRect(212) [Debug]: Get scan rect x = -89843, y = -4695, width = 10938, height = 9370
2024-6-12 13:47:14.473 AMICS::Datastore::MineralGroupingListTable::ReadMineralGroupingList(63) [Trace]: read 2 mineral grouping from database
2024-6-12 13:47:14.475 AMICS::AMICSTool::CAMICSToolDoc::OpenMeasureResultFile(253) [Trace]: Measured application version is 3.2.1.261
2024-6-12 13:47:14.547 AMICS::AMICSTool::CAMICSToolDoc::ImportIADImageFile(1301) [Trace]: Open file succeed: E:\AMICS_Test_Data\White Lines\VL-22206-001RR-Map\VL-22206-001RR-Map.mre

But in AMICS Process:-
2024-6-12 13:49:30.486 AMICS::AMICSProcess::CMainFrame::OpenResultFile(5627) [Trace]: Start to open file: E:\AMICS_Test_Data\White Lines\VL-22206-001RR-Map\VL-22206-001RR-Map.mre
2024-6-12 13:49:30.536 AMICS::AMICSProcess::SpectrumTreeLayout::ResetContent(163) [Info]: resetting content for [0] clusters
2024-6-12 13:49:30.690 AMICS::Datastore::MineralTagTable::ReadMineralTagList(34) [Info]: There are no mineral tags.
2024-6-12 13:49:30.693 AMICS::Datastore::MineralGroupingListTable::ReadMineralGroupingList(63) [Trace]: read 2 mineral grouping from database
2024-6-12 13:49:30.862 AMICS::CommonData::MeasureResultDataContainer::LoadAllFields(1459) [Trace]: Start to load field images (56)
2024-6-12 13:49:30.862 AMICS::CommonData::CMeasureResultFileManager::LoadAllFields(2165) [Trace]: Try to read total 56 fields ...
2024-6-12 13:49:36.336 AMICS::CommonData::MeasureResultDataContainer::LoadAllFields(1423) [Trace]: Load field images succeed. Fields: 56.

So it shows it is successfuly but AMICS Process then crashes and exits.

**Comment by ChiLyMan** [comment]
It could be linked to the stitching of the fields.

**Comment by MarkGuo7** [comment]
@ChiLyMan Hi Chi

Tried on the two samples you shared, but couldn't repeat this issue.
Could you give it a try let me know how to repeat it? Thanks

**Comment by ChiLyMan** [comment]
Tested on 3.3.1, which was still producing white lines:-
<img width="939" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0toQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d7ccd632f1e565368c1a372045cf4d3c0e3ef76a/image.png" alt="image.png" />

Tested the same data set on 3.3.2
<img width="969" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd09oQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--70a2a6391c8a19a017691e89abad89d6dfa42985/image.png" alt="image.png" />


Seems to have been fixed.
