### ISSUE TITLE
BUG - MAJOR - AMICS 3.2.0.222 - PROCESS - BATCH - Batch BSE export not working 

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#189]
Exporting BSE images using the batch process does not work - it just stalls on the first sample (see pic).

Export of mineral images works OK.

![image](https://user-images.githubusercontent.com/84986921/146292534-295925c3-8e53-4e4b-aa77-5417ac283a45.png)

**Comment by jonathan-knapp** [comment]
From Matt: **Think this has been fixed several times but then creeps back in somehow: more often than not, the batch BSE image export fails. It seems to be a bit random - sometimes it works but mostly just sits at the first sample apparently doing nothing for several minutes (10+) until either crashing or I lose interest and kill the batch. It also sometimes cycles through all of the samples and gives an "Export failed" message.
When it does work, the images export in ~10 seconds i.e. it's not the samples that are the issue.

BSE Batch Export Fails hasno dependencies
**

**Comment by jonathan-knapp** [comment]
@Matt-Power is this still happening?

**Comment by Matt-Power** [comment]
It worked just now but it is random so let me monitor for a bit (used to be >90% of the time it would fail and the bug was certainly still there recently).

**Comment by ChiLyMan** [comment]
Been testing this on build 1854 and I cannot get it to fail, yet. I'll close this for now and we can reopen if it starts happening again.
