### ISSUE TITLE
Mineral classification using current mineral grouping

### ISSUE THREAD

**Issue by Portaspecs** [Bruker-Amics/bugs_features#199]
Recently added minerals to the common standards list can't be used when classifying minerals in the spectrum tree, without reclassifying first. This is very time consuming and counter productive. Wasn't an issue in previous versions (refer to V3.1.1.1222).

**Comment by MarkGuo7** [comment]
![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/018da289-dda4-49a4-a884-56303d643336)

**Comment by jonathan-knapp** [comment]
@Portaspecs we are working on a more elegant solution that will be in 3.3.1 or 3.3.2

**Comment by MarkGuo7** [comment]
Now, the Assign To mineral list will be same with current oretype mineral list, so you don't need to reclassify it before showing it in spectrum tree.

![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/a5b6f02b-3f98-456f-b61a-810062c5f531)

**Comment by GGloy** [comment]
Why is all the matching 0? I don't think this is working properly.
