### ISSUE TITLE
BUG-MINOR_AMICS-3.3.0.1158_PROCESS_EXPORT: Secondary Channel Not Exporting 

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#202]
When exporting the secondary channel image of sorted particles, the exported image is the primary channel image. The exported image should be the same as the image in the current view.

**Comment by GGloy** [comment]
When exporting the line-up view it is still the BSE image not the second channel (3.3.0.1158)

**Comment by jonathan-knapp** [comment]
Testing on 2/9/2023 on SU3900 at UQ did not export the secondary image.

**Comment by Matt-Power** [comment]
v 3.3.0.1701
Fixed.
Secondary channel is exported and if the secondary channel is selected during a batch, all images are from the secondary image.
Thank you!
