### ISSUE TITLE
No scale bar on sorted images

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#203]
When particles are sorted, the exported image has no scale. All images should have a scale bar (or at least there should be an option for including a scale bar).

**Comment by MarkGuo7** [comment]
Maybe Van already fixed it :)

![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/3e92e2a4-a2b2-4068-85b0-2bcd66248e4c)

**Comment by Matt-Power** [comment]
@MarkGuo7 Hi Mark, it's actually the scale bar on the exported image that is missing (normally runs along the bottom edge). Hopefully Van fixed that too but try hitting Export - I think you'll find that the scale along the bottom of the resulting .png file is only present on the unsorted images and not the sorted ones.

**Comment by MarkGuo7** [comment]
@Matt-Power Thanks for clarifying. I guess Van is the best person to answer it :) @van-amics

**Comment by ChiLyMan** [comment]
Scale Ruler along bottom edge is present...though a scale bar would be better.
