### ISSUE TITLE
Hitachi FlexSem II Use

### ISSUE THREAD

**Issue by PMC-Labs** [Bruker-Amics/bugs_features#204]
I am just wondering if anyone is successfully using the Hitachi FlexSem II with Amics. 
If so, I would like to know how you are standardizing your SEM conditions for measurements. (ie. Specimen current or Count rate)
If you are having a substantial amount of beam drift which seems to be initiated by running AMICS measurements.

**Comment by jonathan-knapp** [comment]
Thanks for the question. We will have Patrick reach out. We are working on a BSE stability workflow that will use a standard. We only have one other FLEXSEM II user, but many FLEXSEM I users.
