### ISSUE TITLE
Processing subset of particles

### ISSUE THREAD

**Issue by ChiLyMan** [Bruker-Amics/bugs_features#205]
Hi All,

Just wondering if anyone know if there is a way to select a subset of particles to do processing on. For example, being able to do a grain size distribution, and selecting all grains >x um, then do bulk mineralogy, liberation, association etc. processing only for those grains.

Might be useful to mimic metallurgical processes, i.e. following the concentration or gangue through various physical or hydrometallurgical processes. I've tried to mock something up in the image.

Apologies if this is already possible, I've not been in AMICS for a little while.

![image](https://user-images.githubusercontent.com/84643841/155441311-398697e6-301b-4de2-a4e6-e7abf51037d9.png)

**Comment by MarkGuo7** [comment]
Hi Chi

That's a really good question.
I guess the BiFrost project will do all these needs.

For the moment, you can select these grains, and choose the "selection" data set. Then all the calculations will base on the selected grains.
It is only One selection available for the moment. Maybe we can keep a selection tree, then you will be able to keep all these subset.

![image](https://user-images.githubusercontent.com/84481724/155451761-42386383-82f8-4d13-9cf7-4bd7841a021c.png)
