### ISSUE TITLE
Copy details from one mineral in a list to another - when close and open file - property data lost

### ISSUE THREAD

**Issue by GGloy** [Bruker-Amics/bugs_features#206]
When I use the function "copy properties to..." to copy the details of an existing mineral to a new mineral (added as a new standard using spectrum tree) it seem to copy the data and I can reclassify etc without issues, but when closing and opening the file again, all the properties that have been copied are lost.

![image.png](https://images.zenhubusercontent.com/60af4a22d2c5ea1082755c53/d29385fb-7718-4690-9e2b-7efb01a24d25)

![image.png](https://images.zenhubusercontent.com/60af4a22d2c5ea1082755c53/13e7481a-72ab-4f67-bc64-1cc8995c8c65)

**Comment by GGloy** [comment]
I think this problem now solved but created a new one - the first new mineral that I add (spectrum tree or collected) will need a couple of attempts to copy the data - it does not work on the first try (this tested with vs 3.3.0.1158)

**Comment by ChiLyMan** [comment]
Just tested and mineral standard copied over the first time, and was still there after shutdown and restart. NOTE I did save my data before shutting down.
