### ISSUE TITLE
Extra >  Toggle Background Unexpected Behaviour

### ISSUE THREAD

**Issue by jkabel** [Bruker-Amics/bugs_features#207]
In prior versions it was possible to have the background colour in mineral maps to be set to black.  This makes targeting of rare phases for followup analysis in other instruments fairly straightforward with an exported image.

Currently (3.2.0.40) there appears to be no way to change the background colour of mineral images making it very difficult to pick out grains for correlative analysis on other instruments.

**Comment by GGloy** [comment]
It is still not working.....or I am doing something wrong!
