### ISSUE TITLE
Area select shape to add to background

### ISSUE THREAD

**Issue by knapp-amics** [Bruker-Amics/bugs_features#21]
With M4 (and block measurement) cannot filter before the measurement. This is adding a filtering step after the measurement, particularly for samples that are smaller than the measurement area.

**Comment by MarkGuo7** [comment]
We can select rectangle and circle. 
If not good enough, we'd better understand it more and select smartly.

**Comment by knapp-amics** [comment]
Yes, need more information on this one

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by knapp-amics** [comment]
He is looking to add the freehand draw of shape...

**Comment by AHM-amics** [comment]
@MarkGuo7 Yes. The freehand shape selection would be useful to be able to remove "background data" especially for the M4 analysis. For example, in M4, it is only possible to measure a rectangle area. If the sample is non-rectangular it be would be great to select the area of the sample and re-save as a new .mre or to just change the other data to background. Let me know if you need an example.

**Comment by jonathan-knapp** [comment]
Andrew... With a freehand selection do you cut through segments to make them smaller? That is an issue. Selecting and saving as a new measurement seems to be a different issue. If so, can you please open a new issue and describe in full what you want with diagrams. Getting ready to knock a bunch of them out.

**Comment by AHM-amics** [comment]
Hi Jonathan.  The idea is to select areas within a rectangle to remove the background.  As you know, often there are irregular shapes analysed in the M4 (and also SEM).  However with M4 each pixel is a segment, that is there are no segments like with a SEM, and so there is no need to cut through segments.  Ideally, my idea is that this is a short cut to quickly select all the relevant pixels with which to classify within AMICS.  I will open a new issue / feature request.
