### ISSUE TITLE
Testing Esprit API - Connection Reset

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#210]
This one will solve the issue of hardware connection failure.

Need new scan box and not compatible with old Esprit version.

**Comment by jkabel** [comment]
Is this what's happening in my runs at the moment?  AMICS seems to get caught on some fields when setting xray points.  Log file attached
[Investigator32_2022_06_22_16_52_17.log](https://github.com/Bruker-Amics/bugs_features/files/8969145/Investigator32_2022_06_22_16_52_17.log)
.

**Comment by MarkGuo7** [comment]
Hi Jacob

From the log file, I can see there some issues of collecting xrays.
It happens often on the old version firmware scanbox.
When AMICS noticed this issue, it will try to reset the communication to see if can keep going.

You can search “Will try to reset SEM communication” from your log. It happened many times until at some point, still failed after 5 times reset in a row.
Then AMICS will failed the measurement.

**Comment by MarkGuo7** [comment]
Need to check the firmware of the scanbox first. Sadly, there is no easy way to upgrade it.

**Comment by jonathan-knapp** [comment]
It may be worth investigating. If you have some measurements that fail if you can send them to Mark with the log file that is a start.



-Bruker Confidential-

**Comment by jkabel** [comment]
I went through the whole support process.  General agreement seems to be that it is indeed a hardware issue of some kind, but no resolution has yet been presented (last contact was back in July).

I can confirm the issue still crops up on V3.3.0.1315.
