### ISSUE TITLE
Batch file log and datasheet are only written if batch is successful

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#214]
When running a batch file, the log and / or datasheet are only written if the whole batch runs successfully. If the batch fails for any reason, no data is recorded and it is not easily possible to figure out where the batch failed. For larger projects, this is really problematic because the chances of it failing are very high and it takes ages to find out which measurement is corrupt.

At the moment, the batch seems to hold all of the information in memory and only writes out at the very end of the batch which is not good. 

Please change so that it writes out and appends the log after each sample is complete. That way, it is easy to find out where the corrupt measurements are and also when running a long batch (>50 samples / 30 mins plus), you can easily take a copy and see the data before the batch is finished.

Above applies to both the batch log and to the batch calculated data tables.

**Comment by ChiLyMan** [comment]
Checked on version 3.3.0.1508 and log is updating during batch processing (via the PM panel). Plus a final Batch log is generated listing status of all samples in the batch (OK, Failed, Pending)
