### ISSUE TITLE
Background in some fields tagged as mineral

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#215]
Occasionally (maybe 1 every 20 or so samples), the background in one or more fields is tagged as a mineral. There are usually several segments of background and each may be tagged as a different mineral. The initial measurement seems OK - this only happens once the data have been reclassified. The error stays even when reclassifying more times and / or with a different ore type.

It can also creep in at any reclassification step. Once it appears, the only way to get rid of it is to delete all of the background segments in that frame (often difficult and time consuming).

It is very difficult to notice in some samples so all images have to be really carefully checked.

**Comment by Matt-Power** [comment]
This is still present in 3.3.0.1246. Example below.

![image](https://user-images.githubusercontent.com/84986921/186792391-2453d097-ab3a-4f71-8fb7-aee8eb384489.png)

This is a significant issue as it is difficult to check for, can be quite subtle and in the frame affected, can actually cause some of the mineral IDs for the frame to be wrong (it almost looks like the correlation between the X-ray spectrum and the segment has got confused  / corrupted).

**Comment by MarkGuo7** [comment]
@Matt-Power Hi Matt, I guess I will carry this issue afterward, so could you send me this result again? Many thanks

**Comment by Matt-Power** [comment]
@MarkGuo7 Hi Mark, not sure if I sent you the file but I will send a link again just in case. I was getting this error again today (but I had rolled back to 3.2). It is random but once it appears in a measurement, you have to go back to the original and start again. I think that there is an offset in the segment ID and the Xray or mineral associated with it because some of the minerals in the field are wrong (the spectrum looks OK but it doesn't always match the mineral i.e. a bit of pyrite can have a quartz spectrum).

**Comment by MarkGuo7** [comment]
@Matt-Power Thanks Matt

I will take a look after downloading.

**Comment by MarkGuo7** [comment]
@Matt-Power Take a look of your result.

These segments in field 19 should be background but be assigned as minerals.
Their origin identification is un-xray, which not right either.

Not sure this issue came from Investigator, or the Processing.

I will keep digging next week.

**Comment by Matt-Power** [comment]
@MarkGuo7 I've just seen this happen again (3.2.1.261) and it seems to happen if a batch reprocess fails for some reason. A batch just failed on me (AMICS crashed) and it seems that the final field gets corrupted. The only way to fix is to reload the original measurement. Hope this helps track down.

**Comment by jonathan-knapp** [comment]
@ChiLyMan can you please follow-up and get some examples? We need to figure out exactly what is happening and have the measurements it is happening on.

**Comment by ChiLyMan** [comment]
@Matt-Power I've been trying to recreate this behavior, and even force a crash of AMICS on version 1911 but can not seem to make it happen. Did you still have the data set with the issue I can have a look at and test?
Have you tried it with 3.3.0.1701?

**Comment by Matt-Power** [comment]
@ChiLyMan to be honest, it happens with almost all projects - it's just a case of batching enough samples for it to happen. If you create a dummy set of 50 measurements and batch process that (from the ore type), you'll probably see the issue. It's easier to see with segmented measurements of cuttings - it can be subtle though. 

I'll try to give 1903 a test here overnight to see if it is still happening. 

A quick way to find the corrupt measurements is to you look at the batch file progress window and open up any measurements where the number fields processed is less than the total.

Also, when you are running the test, try extracting the BSE images out too as you'll probably see a few measurements with a random missing field.

**Comment by ChiLyMan** [comment]
Thanks @Matt-Power, that seems to have done the trick. 
TESTED on 1911=>
@MarkGuo7 I can send you a link, but you can probably reproduce yourself by just copying a measurement (I chose a segmentation map) and duplicate 50-60 times. Then do a batch reprocess picking any dictionary from the common OreType. I chose to export the BSE and Mineral Map images as well just to test and the results were...strange.
This is the extracted BSE image which looks fine, and I checked all the duplicates, and all are exported correctly: -
![image.png](https://images.zenhubusercontent.com/62f264fb4831bda01fb7d454/6ecdc3fc-2f86-40f9-a783-ec5e91c92cb1)
But the mineral map images are all wrong, with background not being correctly ID and most minerals are wrong. The good news is it was not random, EVERY image was wrong in exactly the same way.
![image.png](https://images.zenhubusercontent.com/62f264fb4831bda01fb7d454/745a8575-cfc5-4879-bd3d-7ce2c576b313)
![image.png](https://images.zenhubusercontent.com/62f264fb4831bda01fb7d454/477b9dd5-5ee8-4584-85e1-6bc32c2c8f84)
Just in case it was a dictionary issue, I tried it again using a dictionary I tested beforehand that would generate only about 25% unknown, so 75% of the sample should be colored correctly (plus this time I only exported the primary list not the group list, in case it is related to groups). 
This is what it should look like when reclassified with the selected dictionary: -
![image.png](https://images.zenhubusercontent.com/62f264fb4831bda01fb7d454/2fefb452-b59a-4df7-8a46-b7cef41d6064)
But when I do a batch reclassification and export of the BSE and Mineral Maps I get the same issue, the BSE looks fine, but the mineral maps are consistently wrong (key word is consistently)
![image.png](https://images.zenhubusercontent.com/62f264fb4831bda01fb7d454/fbea22e1-6baf-4cf3-87fe-86506d3b2733)
![image.png](https://images.zenhubusercontent.com/62f264fb4831bda01fb7d454/c2a6d5f0-9a3c-47ee-be18-dc9872157210)

Let me know if you want the summary logs, but they are not very helpful as they all registered as been successful with no errors. I also checked the AMICS logs, and no errors were reported in the AMICS logs either.

**Comment by Matt-Power** [comment]
@ChiLyMan glad you managed to reproduce it!

It is pretty unusual to see it in all of the batch though (and the fields are usually random) so just wondering if that measurement was corrupted from the outset? Once the issue appears, you can't reprocess to fix it - you have to start again with the original measurement - so if I sent a corrupt example, it will always show. Maybe try reproducing with a different measurement just in case?

**Comment by ChiLyMan** [comment]
@Matt-Power If I do a reclassification within AMICS of the same data set the results look fine. I can reclassify with any OreType from the common OreTypes and everything works fine, no matter how many times and whichever dictionary I use.
But once I do it in a massive batch process, it all messes up. If I got back into the measurement in AMICS manually the results are still wrong. But if I do a reclassification with current dictionary (refresh) the final result is suddenly ok again.

**Comment by Matt-Power** [comment]
@ChiLyMan Hmmm, interesting - that behaviour is a little bit different to my experience (at least for the original bug)- wonder if you are seeing a slightly different but related issue.

**Comment by ChiLyMan** [comment]
Tested on build 1940, and did a bacth reprocess of a large bunch of Matrix mapping results and both the weird results I saw before are gone, and I didn't see any missing fields either.
@Matt-Power could you try the new version and let me know if you see the issue anymore (I'll send you the link)

**Comment by Matt-Power** [comment]
@ChiLyMan I'm afraid it looks like it is still there- or at least something broadly similar. The issue I just came across (in 1961) was that a random field looks like it is from a different measurement. It corrected itself as soon as I reclassified (against current standards). This was a block measurement with no porosity / background so not sure if exactly the same. I'll see if I can recreate.

**Comment by Matt-Power** [comment]
@ChiLyMan and @MarkGuo7 This is still happening (although as mentioned above, it might be slightly different twist to it) - it almost looks like the wrong fields are being read during reclassification. I'll send a link to an image showing the odd fields, the Process log (there will be a lot of other junk in there but if you match up the image time stamp to the log, you should get close - i ran the image extraction batch immediately after the reclassification batch), and the measurement. When I refresh the measurement, the issue is fixed. (This is a little different from the original issue which would be permanent once it appeared.)

**Comment by ChiLyMan** [comment]
Tested this with 3.3 branch and this behavior seems to have be resolved. Tested with a 66 batch reclassify and export of BSE and Mineral Map images.
