### ISSUE TITLE
Sample Image Replaced by Particle Grid

### ISSUE THREAD

**Issue by jkabel** [Bruker-Amics/bugs_features#219]
Version is 3.2.0.242

Steps to reproduce unknown.  Occasionally the sample image will be replaced by a particle grid when changing tabs.

This seems to happen more when editing the mineral groupings while on another tab (calculation tables for example).

![amicsSampleImageGone](https://user-images.githubusercontent.com/12158231/163433143-32cce929-35d1-4252-8399-be956b19ec42.png)

**Comment by jonathan-knapp** [comment]
I see the issue is that the Sort DIrection is set to Descending by Area. Can you see if this is happening spontaneously or if it is associated with action?

**Comment by MarkGuo7** [comment]
It is in sorting mode. 

![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/ea9a4d09-4412-45e8-ade1-6b1eae53b17f)

Most likely by switching between Particle Grid and Sample Images with Linking Tabs option:
![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/3d4b5945-e3bb-4d5c-b31b-8b9016ad6e75)
