### ISSUE TITLE
AMICS Quantification: M4 Data

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#221]
The ability to Quantify data within AMICS is not working. This has been testing with both and "Online" and "Offline" AMICS licence on an offline laptop. The issue appears to be that the software is always looking for the EDS detectors and then fails when it can not "detect" or communicate with the EDS detectors.

Offline quantification will be very useful and can not be tested until this above issue is resolved.

AMICS version v3.2.0.241

**Comment by jonathan-knapp** [comment]
We have started a major project for quantification. This will be completed in Q4.
