### ISSUE TITLE
Batch Processing

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#223]
When Batch Processing using "ore type" it is not possible to select the values for the fitting factor for the "high", "normal" and "low" priority standards.  It applies the "default" values.  These default values are not visible in the "options" list to change.  

A possible work around is to use to batch process with "current sample".  That is, select a sample, re process it with the desired ore type and fitting factors, and then select Batch Processing and use "current sample" and the correct fitting factors will be applied.

**Comment by Matt-Power** [comment]
Just to add to this (and this issue has been raised a few times), the batch dialogue also needs to include all of the steps including spectrum tree and touchup steps. The way it is done at present is clunky and not transparent - it is not clear what steps are included and at what stage. For instance, are spectrum tree steps included in the "Classify with standards..." part or the "Apply mineral grouping..." part? 
Currently the only way to apply steps (and to be sure that they have actually been applied) is by reclassifying the current sample before the batch (and then using current sample settings for the batch) and even then the touchup steps are not always applied; they also do not subsequently appear in the individual measurements after the batch is done (i.e. when you open a file after the batch is complete, the touchup steps list is empty).

**Comment by GGloy** [comment]
@van-amics Has anything been changed or is the solution just to use the current sample?

**Comment by van-amics** [comment]
Hi Gerda,

The #223 fix was to add options to set default high/normal/low threshold for any default processing. You can set them in the Options box.

Let me know if you have any problems using it.
Thanks,
--van




-Bruker Confidential-

**Comment by GGloy** [comment]
What about the second part of Matt's request? Has it been added as a separate feature request?
