### ISSUE TITLE
Energy Channel Ranges: Software Crashes and Automatically closes

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#224]
Very often when entering energy channel ranges in standards, at the end of the selection and clicking enter, the software just automatically closes. Software v3.2.0.249

**Comment by MarkGuo7** [comment]
@AHM-amics Could you show me how to repeat this? Thanks

**Comment by jonathan-knapp** [comment]
@AHM-amics have you shown to recreate this?

**Comment by jonathan-knapp** [comment]
I am closing this because I was unable to repeat this issue. @AHM-amics if this is still happening can you make a step-by-step report that shows how to repeat this? We can open it as a new issue.

**Comment by AHM-amics** [comment]
@knapp-amics Agreed. In the later versions I have tested, it seems to be stable. Specifically v3.2.1.0
