### ISSUE TITLE
Include the reclassification values in the batch summary txt file

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#225]
It would be really helpful to have a record of the % criteria for the classification match (the high, medium, low % values) used when batch processing, what steps were included, and any touchup steps applied to the batch. 

Just a simple line recording what these are at the start of the batch txt file is enough.

Currently, the only way to figure out which values were used is to find the sample from which the batch was started (not easy at all, especially for bigger projects) and look at the reclassify dialogue.

**Comment by GGloy** [comment]
@van-amics The classification values are shown but applied touchup steps are not listed

**Comment by Matt-Power** [comment]
Just to give this one a nudge again - it would be really useful to have the criteria recorded in the text file that goes with a batch. The correct values used by the batch are only recorded in the sample from which the batch was started - the samples processed during the batch do not record the values used during the batch, only the AMICS default ones (and actually, it would be even more useful if the most recent reprocessing values were shown in the reclassification dialogue).

**Comment by GGloy** [comment]
@MarkGuo7 Lets discuss this one soon.

**Comment by jonathan-knapp** [comment]
Tested on 2/9 -
The results show the default values, not the values used. @MarkGuo7, we need to update this. I am putting this in as a bug since it is partly done but not correct.
