### ISSUE TITLE
Display error in mineral grouping editor

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#229]
The formatting of the Mineral Group editor popup window is corrupt (see right hand window of the screen shot). The little "+" sits over the mineral group name. Still works but difficult to see the mineral group names.

In version 3.3.0.926

![image](https://user-images.githubusercontent.com/84986921/167738693-006b48b7-b80e-452d-8b44-0c7a19e96a21.png)

**Comment by jonathan-knapp** [comment]
Test: 3.3.0.1382. This is still happening. 
![image.png](https://images.zenhubusercontent.com/60a274843870252752494569/7dff744b-5dc7-4382-92b9-34e9d5d4c30d)
The "+" is the expansion. Looks to be a padding issue on the UI. 

*steps to reproduce* 
- open the grouping editor
- add any group
- collapse the group 

*impact*
Annoying.

**Comment by MarkGuo7** [comment]
Double checked this issue, it is from our UI lib, BCGSoft.

Will spend some time to see if can fix it or not.
