### ISSUE TITLE
AMICS skips position (out of range) (v3.3.0.911)

### ISSUE THREAD

**Issue by avdhandt** [Bruker-Amics/bugs_features#230]
We just got AMICS running on a JEOL JXA-iHP200F electron microprobe. When trying to run particle analysis, the software skips all frames and does not collect any data.

There seems to be a mismatch by an order of magnitude between stage positions of the frames generated by AMICS and the stage limit definitions in Esprit (see attached log file). However, stage positions are correctly read in as well as driven to from within the AMICS Investigator interface during set-up.

Esprit itself has also been working correctly when using Jobs or Image Extension. 

[Investigator32_2022_05_19_11_48_36_Debug_1st try.log](https://github.com/Bruker-Amics/bugs_features/files/8734717/Investigator32_2022_05_19_11_48_36_Debug_1st.try.log)

Thoughts?

**Comment by MarkGuo7** [comment]
Please try to un-tick the option of "Limit Stage Travel". Or you can adjust the travel ranges.
This option is for stage protection. You also need to double check the stage travel limit in Esprit.

![image](https://user-images.githubusercontent.com/84481724/169421100-fe2c3905-02ec-42c9-b38f-ce2d51eb44b2.png)

![image](https://user-images.githubusercontent.com/84481724/169421381-24e221ac-975c-4e0f-9981-99360dfe4a08.png)

**Comment by avdhandt** [comment]
Hi Mark,

Thanks for the prompt reply. 

Unchecking the "Limit stage travel" flag did the trick to get the measurements going. However, the positions are not correct and it went off the designated area. I think there is still a problem between the conversion of EPMA/SEM stage positions to AMICS positions.

The stage range values in Esprit are correct.

**Comment by MarkGuo7** [comment]
Do you have Teamviewer?

You can try this:
1) Mark the position (if you already know the SEM position on the stage, you don't need to do this)
2) Find the supposed position on stage, right click "Sync the HW position".
It will match your stage position to SEM.

You also need to confirm the chamber setting to match your SEM.

![image](https://user-images.githubusercontent.com/84481724/169422890-27bfcef2-4f97-450a-9160-e473f9f5927f.png)

![image](https://user-images.githubusercontent.com/84481724/169423133-5eebf98d-6ae1-4704-8ff9-0b0ad41822e4.png)

**Comment by avdhandt** [comment]
Hi Mark,

I think I traced the problem to the sample holder designer in AMICSTool. When I create a new holder, save the file and reopen it, the center position of the holder has shifted.

I had setup the following coordinates
![SMM32x3_Setup_correct](https://user-images.githubusercontent.com/64916634/169590000-f4a1d87c-cec0-436a-85cf-4e9237d053f6.JPG)

And after reopening the file, it has changed to this:
![SMM32x3_Setup_incorrect](https://user-images.githubusercontent.com/64916634/169590098-8c587e65-7544-41fd-baca-7d1bc83ee882.JPG)

This shifts the holder center to outside of our stage range 
![JEOL iHP200F stage setup](https://user-images.githubusercontent.com/64916634/169590798-3fad078a-d4fd-4144-aa7c-db3a4efe990a.JPG)

Even when the correct coordinates were present in the holder parameter file, upon opening, the file in AMICSTool, the incorrect coordinates are filled in.
