### ISSUE TITLE
Collection Fails - Quanta 600 / MLA 600

### ISSUE THREAD

**Issue by jkabel** [Bruker-Amics/bugs_features#231]
I'm running version 3.2.0.236 on an older FEI Quanta 600 (ex-MLA) and AMICS regularly fails on thin section collections.  Esprit (2.3, 32 bit server and client) will often have an error in the background and hard crash.  I finally managed to get Esprit to spit out service files without needing to kill it off.

AMICS logs and Esprit dumps attached.

[Investigator32_2022_05_19_09_43_28_Debug-failure.txt](https://github.com/Bruker-Amics/bugs_features/files/8736178/Investigator32_2022_05_19_09_43_28_Debug-failure.txt)
[fail-2022-05-19.zip](https://github.com/Bruker-Amics/bugs_features/files/8736179/fail-2022-05-19.zip)

.

**Comment by jonathan-knapp** [comment]
Thank you for submitting this. The issue has been referred to service and will be addressed with new hardware as needed.
