### ISSUE TITLE
Mineral properties not copied over (vs3.2)

### ISSUE THREAD

**Issue by GGloy** [Bruker-Amics/bugs_features#233]
When adding minerals to a list and using the right-click "copy data and name" or "copy data" in same cases the information is not copied on the first try but only on the second or third attempt. It seems more likely to happen after a reclassification and then adding another mineral.

**Comment by jonathan-knapp** [comment]
I tested this in 3.3.0.1832 and did not have the issue. I am closing this. If this issue is still occurring, please let me know.
