### ISSUE TITLE
Incorrect Xray Assignment at Field Edges (3.2.0.229)

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#234]
There appears to be an issue that accentuates field edges by assigning incorrect spectral matches.

The first image is as-measured (reclassified but the field boundary corrections are those applied by Investigator during measurement). At the field edges, spectra appear to be assigned to incorrect or poorly matching standards despite better matches being present and identified.

The screenshot shows the selected Xray point's EDS spectrum has no Ca in it. However, it is matched to a reference spectrum (in this case called Dolomite_Liz) which has a substantial Ca peak. The list on the right indicates that there is a 95% match to the Lizardite (and Dolomite_Liz) does not even appear on the list.

There are no spectrum tree steps or clean-up steps applied and the confidence limits are set to 95-65-45 (so the lizardite standard should be good down to 65 i.e. well within the confidence limits).  

![j4BB71MPzS](https://user-images.githubusercontent.com/84986921/171683431-d962b54e-13e9-4d76-af1b-63d3ee5499d5.png)

If I clear all field adjustments (see image below), you can see what is going on (the same Xray point is marked). The Xray point is now correctly assigned to the lizardite standard.

I have no idea where the Dolomite-Liz match is coming from (are spectra combined in some way at frame edges?!? - I hope not as this will create a whole raft of other problems).

This issue is really challenging to deal with and causes significant mis-matches at field boundaries, especially where segments are poorly defined (in this case, due to low BSE contrast and to an extent, the issue with poor Xray point placement. 

![image](https://user-images.githubusercontent.com/84986921/171686215-de10fbce-4a21-46d1-ad24-7fa36ebdc152.png)

**Comment by van-amics** [comment]
Hi @Matt-Power. Could you also please send us this very measurement data so we can reproduce the issue and hopefully fix it. Thanks.

**Comment by jonathan-knapp** [comment]
@Matt-Power was this addressed before Van left?

**Comment by Matt-Power** [comment]
No but I think Mark was working on it with some success. Not had a lot of difficult samples like the example so haven't checked to see well it works.

**Comment by jonathan-knapp** [comment]
Understood. If it is OK with you, I will close this one for now. If it comes back up can you submit a new issue with a link to the measurement?

**Comment by Matt-Power** [comment]
Yup, no problem. Thanks.
