### ISSUE TITLE
Unpredictable Matching

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#235]
I'm still getting a lot of unknowns that should be classified but are not (unknowns in black).

In the image below, the area circled has got a bunch of spectra that should match to the ankerite standard. The discrimination is set to 60 for "normal" spectra which the ankerite standard is. The Xray points all indicate that they match to that standard at a confidence of over 60 and, in this case,  to almost 68.

When I try to generate a spectrum from the unknown, I get the usual warning that it is a duplicate entry. In this case, the new entry matched the ankerite standard at a confidence of 42 (I'm assuming the difference is largely due to the averaging and inclusion of some poorer matches?). 

I come across this pretty much daily and it results in a heap of additional standards that I shouldn't need. I guess the questions are what is going, why are so many spectra not matching when everything indicates that they should, and why is there such a big difference between the match shown in the image below and the match indicated when a new standard is generated from it?

It is entirely possible to work-around by creating lots of new standards but this is always very time consuming and it appears that it is unnecessary given that the existing spectral references should work (assuming that the match value shown is correct). 

![image](https://user-images.githubusercontent.com/84986921/171742256-47321c96-2732-49c9-8dfe-70315c72ea22.png)

**Comment by MarkGuo7** [comment]
@Matt-Power Sorry about that, Matt

May I have this result with issue location bookmarks.
If the result too big, you can cut the issue frames out in Tool.

By the way, I am working on bug fixing this two weeks. Please let me know if there any other issues that you want me take a look first.
I will take a look of the xray position issue you reported before. Sorry for delay.

**Comment by Matt-Power** [comment]
@MarkGuo7 No worries and thanks. I've processed that particular project up so that particular issue has been worked-around. I'll tag up some other measurements which show it and send over.

Thanks!

**Comment by jonathan-knapp** [comment]
I am going to close this issue because we have a solution in the works with Robb. We will have a prototype to test soon.
