### ISSUE TITLE
Scan or beam deflect on stage move

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#237]
Can you include a function to either deflect the beam (as in the pause function on the 3900), blank, or at least keep the beam scanning during stage movements please?

When running at high beam current, the beam burns a massive hole at the centre of the field and also deep lines all over the sample (mostly in the resin but I worry about some minerals too). So much so that you can see the lines with the naked eye on the sample after measurement.

There is already a lot of time used during stage movements and between frames so whichever is the quickest, simplest option is best.

**Comment by MarkGuo7** [comment]
@Matt-Power 

Hi Matt, just want to confirm that you want to blank/freeze the beam while the stage moving?

**Comment by Matt-Power** [comment]
@MarkGuo7 
Short answer is yes, I would like the beam to be blanked / frozen while the stage is moving. (I am assuming that freezing deflects the beam into the side of the column.)

The slightly longer answer is, I want to avoid the beam sitting on one spot at any time e.g. after the Xray acquisition is finished, during stage moves, during BSE segmentation / before Xray acquisition etc. Each of these steps involves a short delay where the beam is at the centre of the frame and stationary. You could either blank / freeze the beam or alternatively rapidly scan the beam. Time is always an issue for us so whichever has the least impact on the overall run time would be best but if there is no time difference, blanking / freezing is preferable.

**Comment by MarkGuo7** [comment]
Got it, Matt. It makes lots of sense and very important.
I will take a look and get back to you

**Comment by avdhandt** [comment]
Hi, I am adding my voice to the choir. We are also very concerned about the focused beam burning lines into the sample during stage movements. 

This is on a JEOL JXA-IHP200F electron microprobe. I don't think that there is a beam blanking option per se for this instrument. Just going into the fast beam scan before stage movement might be the best solution for us but this issue has definitely a high priority for us too.

**Comment by MarkGuo7** [comment]
@avdhandt Thanks for making the point.

Basically, we should keep the beam on when collecting image and xray, other time the beam should be blank or in fast scan mode.
Is it right?

**Comment by MarkGuo7** [comment]
Is it possible that the sample got burned while collecting xrays? 
Say, 6000 xray by 10ms will cost over a minute to collect.
In that way, we need to reduce the xray collection count per frame.

I will try to blank the beam while not collecting images and xrays.

Any other suggestion?

**Comment by Matt-Power** [comment]
The beam moving across the sample to the various Xray points doesn't seem to be a problem. It's just the static beam before / after the acquisition phase and during stage moves that seems to be the issue. 

There is no need to change the acquisition settings and I certainly don't want to reduce the xray collection times or number of points - that can be managed in other ways. 

As well as looking at blanking / fast scanning when the beam is idle, could you have a look at minimising the beam idle time please? There are a bunch of times where the SEM is doing nothing while other processes are going on (e.g. while the matching takes place after a frame is measured, while the BSE image is being segmented etc) - if these could be reduced (e.g. having the option to move the stage to the next frame while the matching takes place), it would save a lot of time (seconds and even milliseconds really rack up over the course of a large batch with lots of frames). 

For reference, here's a crappy picture in CL of the burn marks in the resin. The centre hole is really burned (more than the lines associated with the stage movement).

![image](https://user-images.githubusercontent.com/84986921/174123242-37c5c51d-3542-4a9b-a140-3f27e1811c7c.png)

**Comment by MarkGuo7** [comment]
Thanks Matt

I will take a look

**Comment by MarkGuo7** [comment]
@Matt-Power Hi Matt
I break down one frame time from the result you send me. Here is the info:

Field 8 time analysis of [VL-22166-008-Seg]
Stage movement: 2.541
Image collection: 17.589
Image processing: 2.271
Xray collection: 15.008
Classification & Saving: 2.131 

Time info from log file:
Start moving stage: 2022-6-15 5:03:28.828
Start to read image (2 channels):  2022-6-15 5:03:31.369 
	800 * 600 by 16um
Read image done: 2022-6-15 5:03:48.958
Image processing done: 2022-6-15 5:03:51.229
Xray collection done (1948 by 6ms): 2022-6-15 5:04:06.237
Processing done (including saving files): 2022-6-15 5:04:08.368

**Comment by MarkGuo7** [comment]
I think it is a good idea to move the stage to next frame while doing classification.
Thanks

**Comment by MarkGuo7** [comment]
First step, the beam will be in fast scan while not reading images.

![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/7c7c5daf-e747-419d-84c4-16e69222c238)

**Comment by MarkGuo7** [comment]
Is fast scan is good enough to avoid the damage?

Need someone give me bit light here :)

**Comment by Matt-Power** [comment]
Hi Mark, Yes, I think that will work fine, thank you.
