### ISSUE TITLE
Batch Extraction of Mineral Size Data Jumbled 

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#239]
Extracting the mineral size data in a batch produces very strange results. It looks like the size columns are repeated multiple times but not in any particular order. The resultant datasheet is totally unusable.

**Comment by Matt-Power** [comment]
I think that the extraction process is getting garbled because blank rows above and below the data are omitted (see issue 256).

If the data for all of the size bins are extracted by default for every sample, each data row will align and match up no matter how many samples are in a project or how variable the size data is.

**Comment by jonathan-knapp** [comment]
I am going to close this and focus on the core issue or preserving the blank lines.
