### ISSUE TITLE
Copy function improvements 

### ISSUE THREAD

**Issue by knapp-amics** [Bruker-Amics/bugs_features#24]

**Comment by knapp-amics** [comment]
@AHM-amics can you give some specific examples for this one?

**Comment by AHM-amics** [comment]
@MarkGuo7 This relates to the copy function, especially in the visual workspace. For example, when copying an image it copies the whole work space, rather than just a area which encompasses the sample of interest. This results in all copied images having to be cropped in a separate software before the can be used.

**Comment by MarkGuo7** [comment]
Is it something like the save as function in Tool?

We can talk about what need to save and in which way and how to show the saved results.

![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/4ee1f010-d94b-42ea-b02d-ba356275eba0)

**Comment by knapp-amics** [comment]
@AHM-amics can you see above?

**Comment by AHM-amics** [comment]
@MarkGuo7 , @knapp-amics thanks for the reminder. I will check it tomorrow and provide feedback.

**Comment by AHM-amics** [comment]
@MarkGuo7 Yes. I guess similar to this. As I understand it, this "save" in AMICS tool creates a separate .mre file of the selected fields.

For the copy of images I am referring to just the images, not the data. I would like to save either selected areas of the image or as a default, just the full sample image size not including the blank space in the AMICS workspace area. See attached sample....

![AMICS Image Capture](https://user-images.githubusercontent.com/84203995/121305559-02d9ab00-c8fe-11eb-8b15-977e6ac21e3b.JPG)

**Comment by knapp-amics** [comment]
@MarkGuo7  and @AHM-amics  - let me make sure that I understand. You do not want any white around the copy image? I think if you only want part of the image the snip tool from Microsoft works well. 
![image.png](https://images.zenhubusercontent.com/60a274843870252752494569/77fefe90-24aa-43f7-9263-8ce174fc8afd)
