### ISSUE TITLE
Incorrect number of fields being measured

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#240]
I have had a few instances now where Investigator does not measure the correct number of fields (i.e. the total measured area does not match that indicated in the measurement). In the latest instance, I specified an area with 110 fields but only 80 were measured. Interestingly the measurement settings were copied from one measurement to several others and only about half of them had the same issue with missing fields - everything else was identical. The fields are missing around the sides. 

All measurements are marked as successfully completed but if I hit "run" after the batch is completed, it will go back and measure the missing fields.

In other cases, it has measured way too many fields.

Doesn't happen a lot but that might be related to the fact that a lot of samples are measured with the same settings - I only notice it happening when I change things up a bit. 

@MarkGuo7 I'll send the log files and a screenshot from Investigator by email.

**Comment by MarkGuo7** [comment]
@Matt-Power Thanks Matt

I will take a look after downloading.

**Comment by MarkGuo7** [comment]
@Matt-Power Hi Matt, could you upload the mre file as well? I want to take a look of your settings. Thanks

**Comment by Matt-Power** [comment]
Just uploaded to that share (give it 10 mins though). Thanks.

**Comment by MarkGuo7** [comment]
@Matt-Power Sorry Matt, couldn't repeat it here. Not sure why. Let me know if it happens again. I can add extra log message to trace it on your system if needed.

**Comment by jonathan-knapp** [comment]
We could not recreate it. Mark has added additional logging. If it happens another time we need the file.
