### ISSUE TITLE
Washed out images: batch extraction of mapped images

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#241]
If I run a batch image extraction of mapped measurements, the images are washed out (a bit like the background when specific minerals are selected for viewing).

Extracting the images individually works fine. 

Example below.

![image](https://user-images.githubusercontent.com/84986921/174129336-58e703ea-63c3-4c4f-8850-880abf3c2edf.png)

**Comment by GGloy** [comment]
I think this ticket can be closed (tested with vs 3.3.0.1508)

**Comment by jonathan-knapp** [comment]
Gerda,
Feel free to just close it. Can you?



-Bruker Confidential-

**Comment by GGloy** [comment]
Some I can - this one I can’t.

**Comment by jonathan-knapp** [comment]
So strange.



-Bruker Confidential-
