### ISSUE TITLE
Duplicating Ore Type - Mineral Groupings Missing

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#242]
Whenever I duplicate an ore type, the mineral groupings are missed out. The steps are duplicated but groups are not. They can be imported from the measurement but if you forget and then try to import at a later date, the groupings are corrupt. 

Can you make it so that the mineral groupings are automatically copied across from the original ore type please?

**Comment by MarkGuo7** [comment]
@Matt-Power Sorry Matt, I will sort it out.
