### ISSUE TITLE
Common Standards: Exporting of ore types db

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#243]
AMICS v3.2.0.252
Common Standards: Exporting of ore types db creates a “db” file.  However, when trying to import from this file AMICS crashes making it impossible to use the db to import Ore Types.  This has been confirmed on multiple computers.

**Comment by MarkGuo7** [comment]
This should be sorted out by last meeting, isn't it? @AHM-amics

**Comment by AHM-amics** [comment]
Hi Mark,

Yes - I think it has been fixed.  I will test it to confirm. However, one of the issues/symptoms is that it takes an extremely long time to load a ore type when the database is large (i.e. there are numerous ore types stored).  I will do some tests to confirm what the times are and if the system still crashes.

**Comment by AHM-amics** [comment]
I have just tried to load a database in AMICS.
1. I changed my database to the default database with only 6 oretypes for MicroXRF.
2. I tried to load my most recent "autosaved" database.  This would have about 10-15 Oretypes.
3. After clicking load, a pop up window appears. This popup window has a "question mark" and a yes or no box. THere is no question or comment or information in the popup window.
4. After 30 mins of not knowing if it was loading or not, I clicked the cancel button after which a pop up button stating "deleting minerals" appeared.

The software version is v3.2.1.0

Let me know if you need more details

**Comment by AHM-amics** [comment]
Follow-up comment.  Loading "Ore Types" individually appears to work correctly.

To confirm: I can go to the "import" button (on the right with two arrows) and select a ore type from with the db (that I was trying to import above) and select 1 or more ore types and successfully and quickly merge into the loaded database.

The software version is v3.2.1.0

**Comment by AHM-amics** [comment]
Hi Mark.

Just a quick follow-up.

Has this bug been fixed? I did some testing las week and wrote some detailed notes in github.

If it is fixed, please advise in which version, so I can test and use it.

Thanks, and enjoy your week.

Saludos,
A

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jonathan-knapp** [comment]
Can you try the same procedure with 3.3 please?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
