### ISSUE TITLE
AMICS Issues with Large Number of OreTypes

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#244]
AMICS v3.2.0.252 (and others)
In my AMICS Common Standards I have lots of Ore Types, probably over 50. This causes a huge delay when opening any AMICS file, even extremely small datasets. For example, these datasets open instantaneously on other computers (i.e. the trainees, who have only a couple of ore types) whereas on mine it is at least two minutes with the screen stuck with the pop up window stuck at “Process 10% (Not responding) Loading User Standard file (Bruker M4 Plus)” and at the same time “Process 10% (Not responding) Reading Global Standards….”.

**Comment by Matt-Power** [comment]
Can I add my vote to looking at this issue too please?

I think that this manifests itself in a few places in AMICS and not just on opening samples. I believe it is also dependent on the number of standards in the ore types as well as the number of ore types so even a relatively small number of complex ore types (and almost all of mine are complex unfortunately) makes it very time consuming. 

The only way round this is to regularly delete out Ore Types regularly but this creates all sorts of problems managing projects.

**Comment by AHM-amics** [comment]
Hi Matt,

Thanks for the feedback, and you are correct. This problem does spill over into all “ore type” functionality where tasks such as duplicating an ore type or copying minerals from an ore type become extremely slow.

And an issue for myself is that I normally don’t have the luxury of deleting old oretypes as I must save them for clients, different M4 Systems (i.e. M4 vs M4+), training lists etc etc, so my database is excessively large.

Saludos,
Andrew

**Comment by MarkGuo7** [comment]
Thank you for reporting this, I will take a look of it. Basically, the oretype list shouldn't be listed unless necessary.

**Comment by jonathan-knapp** [comment]
All,
I want to change the way OreType Classification Methods work for AMICS 3.3. The Classification method needs to be part of the DataStore and included in the DatStore SQL. Only the selected Classification Method shuld be loaded into memory and saved with the file. Only a list of methos is loaded. This will speed it up and have much better functionality.

Our vision for the Datastore  is that it will be a container for:

  *   Reclassification methods that include everything that can impact a classification.
  *   Shared standard database
  *   Project and Repositories
  *   Samples and specimens

Each file will tan only have the most recent method, standards, etc. saved to it. We have a concept called a "package" that includes everything. This has not been implemented, but is on the roadmap.

-Jonathan



-Bruker Confidential-

**Comment by MarkGuo7** [comment]
Now the common standards in Process will not automatically loaded if un-check "Compare Result Mineral" option:

![image](https://user-images.githubusercontent.com/84481724/176845486-66a38bb4-c84c-4ed9-8447-c2ca5b28a46d.png)
