### ISSUE TITLE
Common Standards area: Graphical interfaces 

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#245]
AMICS v3.2.0.252
Common Standards area: Graphical interfaces when right clicking on mineral list. For example, if I right click “remove minerals” and then my mouse hovers over a mineral in the background of the pop-up window, then the pop-up window itself becomes deactivated and does not work.

**Comment by jonathan-knapp** [comment]
@AHM-amics can you add some screen shots? Will you check that this is still happening on version 3.3?

**Comment by jonathan-knapp** [comment]
Seems to be fixed in 3.3.1.1812
