### ISSUE TITLE
BUG-MAJOR-AMICS-3.2.0.252_PROCESS_MIXING: needs to keep density and formula correctly  

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#246]
AMICS v3.2.0.252 (and others)
Common standard areas. Generate Mix. During this process, there is the option (tick box) for mix elements. If NOT selected then the software keeps the element information for the dominant mineral in the mix.  This is correct and perfect.  However, in addition to keeping the correct elements, it also needs to to keep the correct density (which is still mixed) and the correct formula (which isn’t necessarily the dominant mineral in the mixing (it seems to be random).  These two factors should also be link to the mixed elements tick box.

**Comment by GGloy** [comment]
Mark, the formula is not correct, it is only using one throughout. Density is ok now.

**Comment by ChiLyMan** [comment]
Tested on build 1854 and density is correctly mixed and the formular is the dominate mineral.
