### ISSUE TITLE
Pixel Spacing Value Error

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#247]
AMICS v3.2.0.252
When importing a bcf file the value recorded as the pixel spacing shown in the information area is incorrect. Nevertheless, the value used in the calculations is correct!

**Comment by jonathan-knapp** [comment]
@AHM-amics can you please check with version 3.3.0.X and tell us if this is still happening? If it is can you provide some screen shots?

**Comment by AHM-amics** [comment]
@knapp-amics 

Under v3.2.1.0: The data imports correctly - see image. The visual display and scale are correct. Each pixel is 10 um. However the value recorded under "X-Ray" variable "space" is 50um.  I am not sure if this value is used in any calculations.

Under v3.3.0.1315: The data imports correctly - see image. The visual display and scale are correct. Each pixel is 10 um. However the value recorded under "X-Ray" variable "space" no longer is visible.  I am not sure if it has just been removed or corrected.  The import question is whether it is just hidden and / or used in any calculations.

![XRay Info v3-2-1-0](https://user-images.githubusercontent.com/84203995/198576788-267a07b4-e736-4230-beb4-9043c3f2def3.PNG)
![XRay Info v3-3-0-1315](https://user-images.githubusercontent.com/84203995/198576789-a65fdfe7-747d-4d10-8759-892773b5046e.PNG)

**Comment by GGloy** [comment]
@MarkGuo7 Lets discuss this later...

**Comment by MarkGuo7** [comment]
Should be ok now :)

**Comment by GGloy** [comment]
@MarkGuo7 is the step size supposed to show now? It is giving a min segment size and not step size....

**Comment by GGloy** [comment]
@MarkGuo7 I think its ok to close this one....
