### ISSUE TITLE
Energy Channel Calibration Issues

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#248]
AMICS v3.2.0.252
The ability to use the Energy Calibration component in the Common Standards is several compromised.  That is 9 times out of 10, the popup window does not appear and the AMICS software freezes resulting in a hard reset (i.e through Task manager).  This is confirmed on numerous different computers.

**Comment by jonathan-knapp** [comment]
@MarkGuo7 and @van-amics I think this needs to be fixed in 3.2

**Comment by MarkGuo7** [comment]
@AHM-amics Hi Andrew, is it still the case?

**Comment by MarkGuo7** [comment]
Let's close it for the moment.
