### ISSUE TITLE
High Priority Reclassify option

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#249]
AMICS v3.2.0.252

When using the reclassify option and I have High Priority standards, they do NOT use the fitting factor number entered into High Priority, but rather the fitting factor for the normal standards.

**Comment by van-amics** [comment]
Since I cannot reproduce the issue with my small samples, can you please send me the very measurement that caused this problem, so I can reproduce it and hopefully get to the bottom of this one. Thanks.

**Comment by jonathan-knapp** [comment]
@MarkGuo7 and @van-amics I think this needs to be in 3.2 before it is sent to production.

**Comment by GGloy** [comment]
Can be closed.
