### ISSUE TITLE
Export legend function legend has error "missing program"

### ISSUE THREAD

**Issue by knapp-amics** [Bruker-Amics/bugs_features#25]

**Comment by knapp-amics** [comment]
Error:
![image.png](https://images.zenhubusercontent.com/60a274843870252752494569/8ce0ee7a-780a-4621-8f8e-4f70c142ee82)

**Comment by AHM-amics** [comment]
@markguo, @knapp-amics FYI: This legend copy function is working in my version v3.1.1.2227
