### ISSUE TITLE
Investigator - make noise reduction, secondary channel acquisition available in measurement

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#250]
Is is possible to make some of the global settings available at the measurement level? This would make it way easier to measure mixed batches of samples and make Investigator a lot more versatile.

For instance, I sometimes use noise reduction to make up for poor sample polish (e.g. on thin sections where repolishing is not possible).  I therefore have to stop a run before / after the suspect sample to change the setting back.

Similarly, I sometimes acquire the secondary channel but often don't need / want it for all samples in a holder. To get around this, I have to either live with the time overhead or stop the measurement to change the settings. 

Needless to say, I often forget about leaving one or other of the settings enabled / disabled thereby trashing a run (especially problematic with the noise reduction).

**Comment by jonathan-knapp** [comment]
It is a close-in objective to move as many settings as possible to the measurement level. @Guo, Junfeng ***@***.***> may have already done this.



-Bruker Confidential-
From: Matt-Power ***@***.***>
Sent: Tuesday, June 28, 2022 3:05 PM
To: Bruker-Amics/bugs_features ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Bruker-Amics/bugs_features] Investigator - make noise reduction, secondary channel acquisition available in measurement (Issue #250)

**EXTERNAL EMAIL**

Is is possible to make some of the global settings available at the measurement level? This would make it way easier to measure mixed batches of samples and make Investigator a lot more versatile.

For instance, I sometimes use noise reduction to make up for poor sample polish (e.g. on thin sections where repolishing is not possible). I therefore have to stop a run before / after the suspect sample to change the setting back.

Similarly, I sometimes acquire the secondary channel but often don't need / want it for all samples in a holder. To get around this, I have to either live with the time overhead or stop the measurement to change the settings.

Needless to say, I often forget about leaving one or other of the settings enabled / disabled thereby trashing a run (especially problematic with the noise reduction).

-

**Comment by MarkGuo7** [comment]
@Matt-Power @knapp-amics Do you think these settings should be with each sample settings?

**Comment by Matt-Power** [comment]
@MarkGuo7  I would like to see them at the measurement level please (sample level would be OK but measurement level would be way better / more versatile).

**Comment by MarkGuo7** [comment]
@Matt-Power Thanks Matt, could you make a list of parameters you want to put in Measurement? We need to think about how to show them, because there already many parameters there. More parameters, easier to forget. :)

**Comment by jonathan-knapp** [comment]
It has to be at the measurement level. We can have global defaults, but we need to have granularity and measurement control. All x-ray, imaging, etc. Needs to be set at the measurement.

**Comment by Matt-Power** [comment]
Agreed.

As for which settings - it's basically as many as you can so that the user can tailor their settings to their instrument, workflows etc. Ideally I would like to have the channel cut off in there too but (at least so that it gets carried through to Process).

Personally, the more control you can give me, the better. I'd really like to be able to optimise scan settings, segmentation etc. To go hand in hand with this though, you need to be able to export / import saved conditions so you can iteratively optimise without fear of screwing everything up (and an ability to reset to instrument defaults together with at least one set of warning messages or even a password to discourage and prevent unauthorised fiddling).

**Comment by jonathan-knapp** [comment]
@MarkGuo7 is this done?

**Comment by GGloy** [comment]
@knapp-amics yes, currently can set the noise reduction and channel selection per measurement, but currently that's the only parameters included at this stage
