### ISSUE TITLE
Investigator - add maximum segment size limit

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#251]
Can you add a maximum segment size limit to the measurement parameters please? (And add a shape factor if at all possible.)

With the current segmentation area factor, you can only adjust the comparative difference in size (low values = can have very big and very small segments, high values = all segments are close in size but larger). I need to have small segments to capture fine textures in the matrix or groundmass so I have to use low values but this means I also get very large, often irregular segments in areas of similar BSE. This quickly becomes a problem when there are minerals and materials of identical BSE such as dolomite, quartz and albite (all very commonly occur together) or when you have to track solid solution which does not produce a significant change in BSE (e.g. Mg in calcite). This commonly gives rise to really obvious mineral changes across a field boundary (extreme examples look like a checkerboard) and also really obvious artificial grain boundaries which are actually segment boundaries. This is exacerbated by the issue with the placement of the Xray points as they commonly hit inclusions.

The ability to fix the maximum segment size would mitigate some of these issues. Similarly, being able to change the shape factor parameters (to allow / prevent irregular or elongate segments), that would be really useful, especially for zoning and other textures which are really challenging with the currently available settings.

**Comment by jonathan-knapp** [comment]
Great idea.

**Comment by GGloy** [comment]
@knapp-amics  for the shape factor part - this would be quite difficult - can you creat a new feature request for that part (using shape factor)?
