### ISSUE TITLE
Right Click on Mineral Standards Not Working 3.3.0.1155

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#252]
The right click functionality in the Standards tab does not work e.g. if I create a new standard, switch to the Standards window, compare to existing an standard and find a match, the menu does not appear when I right click on the match to copy the data / colours across.

**Comment by MarkGuo7** [comment]
In Investigator or Processing, or both?

I will take a look

**Comment by Matt-Power** [comment]
Appears to be just Process. Thanks.

**Comment by MarkGuo7** [comment]
Got it, thanks Matt.
The fix will be ready today :)

**Comment by Matt-Power** [comment]
Wow, thank you!
