### ISSUE TITLE
New standard not automatically selected when created - Process 3.3

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#253]
If I create a standard from a measurement, switch to the standards tab, the standard (or most recently created standard) is not automatically selected in the standards list. The spectrum is shown and it is still possible to find a match and copy the data and name, but the entry in the ore type remains blank.

To get it to work, you have to scroll down and specifically click on the new standard before searching for matches or applying properties etc (a time consuming and needless extra step).

If you forget to select the standard before matching / assigning properties, you can "rescue" the work that you have done by selecting the spectrum and hitting the normalise button - the information will get updated to the ore type at that point.

This behaviour is present in all versions of 3.3 that I have seen (but not in 3.2).

**Comment by MarkGuo7** [comment]
@Matt-Power The fix will be in next build. Let me know if you want to try first.

**Comment by GGloy** [comment]
@MarkGuo7 This issue is still there- let me know if I need to show you.

**Comment by GGloy** [comment]
@MarkGuo7 I think we can close this one
