### ISSUE TITLE
It is possible to create standards with identical IDs and names

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#254]
I think that this may be related to Issue 253 but it is now possible to mistakenly create multiple standards with the same name and ID (even though the reference spectrum associated is different). This causes errors in the grouping manager window and I'm sure creates all sorts of problems elsewhere.

I have not been able to check exactly how to recreate yet but I suspect that if a standard is not specifically selected when properties are defined (as in issue 253), it does not trigger the automatic renaming (to _1 etc) and so duplicates are created.

**Comment by Matt-Power** [comment]
This is still present in 3.3.0.1315.

It causes the groupings dialog to throw an error - basically it doesn't seem to be possible to group until the duplicate is renamed. I think the grouping uses the mineral name rather than the ID? Suspect this will also be a problem in the spectrum tree.

**Comment by jonathan-knapp** [comment]
I was able to reproduce this in 3.3.0.1382 - it still needs to be fixed.

**Comment by Matt-Power** [comment]
This appears to be closely related to Issue #305 and therefore leads to loss of ore types. I've now junked two ore types potentially resulting in many hours of lost work or worse.

It also leads on to various other issues (inability to group minerals etc) so this is a much more serious issue than it seems on the face of it.

**Comment by GGloy** [comment]
@knapp-amics I think this is fixed. If you can try and close.

**Comment by jonathan-knapp** [comment]
I'll try tomorrow. Thanks.
