### ISSUE TITLE
Over-ride spectrum in Process. (Modify spectrum not working properly in Tool.)

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#255]
I have a lot of measurements where disseminated inclusions are being inadvertently hit by Xray points for the surrounding much larger segments. This means I have a lot of really large segments which have an inappropriate spectrum assigned. Could you add an "over-ride" function in Process where specific segments could be assigned to a different mineral please? 

I noticed that there is a modify Xray function in Tool but this does not work correctly - I can select a mineral from the list but the segment then gets re-assigned to a completely different one (or not at all). (In case it matters, my ore type has more than 255 entries due to the complexity of the ore body.) There also does not appear to be a way to save the measurement in Tool (the save as button is always unavailable).

**Comment by MarkGuo7** [comment]
@Matt-Power Did you try to use 3.3 Investigator to measure? It seems the xray positions are better than 3.2. 

The assign xrays to given minerals in Tool is quite old. I can bring it to Process if needed. But this function need to be approved by Jonathan @knapp-amics

**Comment by jonathan-knapp** [comment]
We do want to bring this to process asap. However, we have the problem that any assignment would be overwritten during reclassification. We have never defined how we want this to work. I see the following options as being feasible: 
(1) manual assignments are added as a classification step that can be turned on and off like a spectrum tree step. 
(2) manual assignments are persistent unless clearing assignments is selected in the classification menu. 

I'm open for other options. It is my objective to incorporate all request vacation steps into the method and thus eliminate the classification menu. However, we have not fully implemented classification steps.

**Comment by Matt-Power** [comment]
These are mostly older measurements where I have used 3.2 (not tried 3.3 yet but will do once the latest project is through the instrument). I've got a massive backlog of similar measurements that I work up when I have time so this will be a recurring theme for me (and I suspect that even with the better Xray placement, there will still be a need for the override).

It is a last resort function but would save a lot of hassle (and time re-running samples). As an example, in the latest batch of samples up to a quarter had massive segments of incorrectly identified minerals which will need to be rerun using a map (or with the improved placement in 3.3) so hopefully you can get approval.

Just a thought: would it be possible to combine segments with the option to select which of the standards is assigned to the merged one? Or is that no easier than an override?

**Comment by Matt-Power** [comment]
@knapp-amics I think my preference would be for your option 2 so that it works in a similar way to the BSE adjuster etc. This gives the option of clearing adjustments if they are not needed / incorrect but are otherwise persistent.

**Comment by jonathan-knapp** [comment]
@Guo, Junfeng ***@***.***> please implement. This has been requested many many times. Let me know if you have questions.

Get Outlook for iOS<https://aka.ms/o0ukef>


-Bruker Confidential-

________________________________

**Comment by Matt-Power** [comment]
Thanks

**Comment by MarkGuo7** [comment]
Ok, I will give it a try.

The first step would be manually change one/many selected xrays to given mineral. So these changes should be your last step to polishing your data. You need to do them again after reclassification.

The next step we may consider how to keep them persistent. We need to discuss what if the given mineral changed, or disappeared etc.

How does it sound?

**Comment by guo** [comment]
Please don’t use @guo. It tagged wrong person. Thank you!

**Comment by Matt-Power** [comment]
Sounds good but persistence is important to include asap please. I've lost track of the number of times I've had to reprocess things after I thought that I was finished e.g. to correct a density or other minor tweak - having to go back and polish the data again afterwards would be pretty frustrating.

Not sure how to figure out the disappearing / changing mineral but I guess that wouldn't happen too often, especially if you are only doing as a final clean up so maybe just a warning saying that the standards changed and overrides will have to be re-done will be enough in that case.

Merging segments and choosing which Xray spectrum to use might actually work more predictably (assuming that merging segments is possible). Both override and merge would be good and I can see where each method may have specific advantages (and from a scientific point of view, I'm a little more comfortable merging segments than overriding as the latter could be put to slightly dubious use).

**Comment by MarkGuo7** [comment]
@Matt-Power Thanks Matt, got it.
