### ISSUE TITLE
Preserve the no data rows in calculation tables

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#256]
Rows where no data exists are excluded when I copy out to excel. This makes extracting large volumes of data really time consuming as every table has to be re-formatted and re-arranged.

For instance, if I extract size data and particles in one sample where the mineral size ranges from 3 microns to 100 microns, only the size buckets within that range are copied out (the larger and smaller size buckets are omitted). The next sample in the project will have a different range of sizes (say, from 1 to 200 microns) - this means that condensing the data into a single table requires a lot of work involving moving cells around so that they line up.

If all size data, even the blank rows is copied out by default, the array will be the same size every time and the data will be in exactly the same format which means it is very easy to edit (multiselecting and deleting blank rows is much, much easier than inserting individual cells to shift everything around). 

I strongly suspect this is the problem with the batch size extraction - the omission of the blank rows is plainly causing an issue and resulting in the jumbled datasheet.

**Comment by GGloy** [comment]
@knapp-amics this has been fixed for the batch, but for individual export it still only exports the relevant data. Can you follow up with Matt if that is good enough for him?

**Comment by ChiLyMan** [comment]
Just confirm individual exports will retain the "zero" mineral lines, on version 3.3.0.1508
