### ISSUE TITLE
Control Stage Height on Zeiss system

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#258]
Rio wants to keep the same working distance and control stage height.

**Comment by ChiLyMan** [comment]
Similar request from UBC.

**Comment by Matt-Power** [comment]
Ditto for me please - option to set using either Z or WD at the per-sample / per-measurement level would be really handy.

**Comment by ChiLyMan** [comment]
@Matt-Power I think you can already set WD per sample/measurement right now. All you need to do for each sample/measurement is collect HW data again. Or is it more you want the option to do Z or WD focus?

**Comment by Matt-Power** [comment]
Option for to choose between Z or WD please.

**Comment by MarkGuo7** [comment]
For the newer version, you should possible to control both working distance and stage height. 
Sorry, I don't have much chance to test it yet. Please let me know if it has any issues.

![image](https://user-images.githubusercontent.com/84481724/193707404-961e6501-2f34-4ba8-80c9-bff3f0a500ab.png)
