### ISSUE TITLE
After re-ordering a mineral list the Area% values is no longer displayed in the properties window

### ISSUE THREAD

**Issue by GGloy** [Bruker-Amics/bugs_features#263]
After the order has been changed for a mineral list (ore Type) the Area% values is no longer displayed in the Properties window. 

![image.png](https://images.zenhubusercontent.com/60af4a22d2c5ea1082755c53/7ca57b97-5e69-4ae9-81c6-cdf2645578a39) Vs 3.2 and 3.3.0.1181

**Comment by jonathan-knapp** [comment]
Can you check and make sure this is still happening in 3.3? If so, can you add screen shots?

**Comment by GGloy** [comment]
All good now
