### ISSUE TITLE
Exporting RAW image without smoothing

### ISSUE THREAD

**Issue by ChiLyMan** [Bruker-Amics/bugs_features#266]
Is there a way to export image at full resolution (RAW) without any smoothing? I've tried exporting as BMP, PNG and TIF and the final output seems to have been smoothing during the exporting process.
I've attached an example of a BMP exported versus the sample feature captured via screenshot directly from AMICS. So before I use to export the RAW SQLite database, and just manually extract the pixel map one pixel at a time, but was there a better why of doing this?

![BMP(Left) - ScreenCapture(Right)](https://user-images.githubusercontent.com/84643841/182267375-6851cc9d-859e-4aa7-956e-93474d9e04e9.png)

**Comment by ChiLyMan** [comment]
PS: Otherwise is there a way to give clients a temporary AMICS license so they can open the data file themselves? I think we've discussed this before not sure if there was any outcome yet one this.

**Comment by MarkGuo7** [comment]
@ChiLyMan Hi Chi, may I have the result to take a look? Thanks

**Comment by ChiLyMan** [comment]
Mark,
Here is the database I got the image from.
[Sample_3-BSE_1.zip](https://github.com/Bruker-Amics/bugs_features/files/9238249/Sample_3-BSE_1.zip)

**Comment by MarkGuo7** [comment]
Thanks Chi @ChiLyMan 

Here is the image from Processing:
![image](https://user-images.githubusercontent.com/84481724/182274196-bd013927-10e0-414b-bd25-6b6eb85094a5.png)

Here is the looking opened in Image Viewer:
![image](https://user-images.githubusercontent.com/84481724/182274300-ac73ba38-21d7-4bc1-8ab6-6f3d0b394828.png)

When you open in ImageJ, it looks like:
![image](https://user-images.githubusercontent.com/84481724/182274469-43a99bf2-db48-425a-a02f-8508e3b263ce.png)

Seems the Windows Image Viewer smoothed the looking for you :)

Let me know if you still have any question.

**Comment by MarkGuo7** [comment]
> PS: Otherwise is there a way to give clients a temporary AMICS license so they can open the data file themselves? I think we've discussed this before not sure if there was any outcome yet one this.

We discuss this question before. There are couple of options, one is that they can run Processing as a read-only Viewer even without a license.

Need @knapp-amics to make the decision.

**Comment by ChiLyMan** [comment]
Thanks Mark.
Windows shoots me in the foot again. Thanks for figuring this out.

**Comment by ChiLyMan** [comment]
Issuer cause by Windows viewer and not the exported image. Solution is to use a more basic image viewer such as ImageJ.
