### ISSUE TITLE
Move selected mineral grouping item up/down in group editor

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#267]
![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/f1119f5b-4b95-43a3-ba68-10d1bc61b1be)

**Comment by ChiLyMan** [comment]
Hey Matt,
I was testing this on 3.3.0.1315 and you can shift group order in the "Current Result Standards" using the up and down button. The ordering does not seem to need reclassification to stick, and the order survives reclassification (even if the new oreType does not match, you just get left over species at the bottom). I also modified the list, and after modification there was no need to reclassify to make the new modify list work, and it also stuck and survived reclassification.
Additionally, if you modify the order in the "Current Results Standards" and then go back into the pop-up group editor, the new group position is reflected in the pop-up.
I know your request was specific for functionality in the pop-up menu but does this utility meet your needs? Or am I missing something?

**Comment by GGloy** [comment]
@MarkGuo7 This is not working in vs 1508

**Comment by jonathan-knapp** [comment]
Tested on 2/9 - still not working

**Comment by ChiLyMan** [comment]
Just tested on 1854 and is working to move groups up and down the list. Still issue with taking primary material out when modifying groups (this works when creating a new group only, but will list is on a separate bug report.
