### ISSUE TITLE
Command line to process data

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#268]
Processing should accept more command line parameters to processing data

- Do classification
- Do stitching
- Exporting calculation results
- ...

**Comment by jonathan-knapp** [comment]
@MarkGuo7 I am wondering what you mean by command line? Are you talking about an API or just the step to make an API possible?

**Comment by jonathan-knapp** [comment]
@MarkGuo7 can you please tell me more about this? Is this better moved to a long-term API project and to do this by the API and not a command line? Is this required for an API?

**Comment by MarkGuo7** [comment]
This is different from the API. It's command line parameters when you start application. For example, if you pass in parameter to Processing, then it can open file like you double click the project management item.
