### ISSUE TITLE
Database density calculation 

### ISSUE THREAD

**Issue by knapp-amics** [Bruker-Amics/bugs_features#27]

**Comment by MarkGuo7** [comment]
Andrew supposed to show us how to calculate from the formula, then we can implement it.

**Comment by knapp-amics** [comment]
@AHM-amics can you post the calculation and we can think about this together

**Comment by MarkGuo7** [comment]
This is about the automatically calculate Density property from Formula string.
Nothing about our result calculation.

![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/f7b86dc0-489e-40bd-a9fe-ecf622485c27)

**Comment by Sperrylite-MattNg** [comment]
The formula can be found in Gaines et alia (1997, Dana's New Mineralogy - 8th edition; pg. xxix). Formula is D = (Z x M)/(N x V); D: specific gravity/density; Z: number of formula units in unit cell (crystallographic param = look up in a reference book); M: formula weight of compound (calculated from the quant); N: Avogadro's number (look up in a book, always the same value); V: volume of the unit cell (look up in a reference book, but may need to be calculated using crystallographic params in reference books). Volume of unit cell formulas can be found in Tilley (2006, Crystal and crystal structures; pg 36 Table 2.5).

**Comment by MarkGuo7** [comment]
Wa, that's amazing to see someone in this group really know it. :)
I still need bit more help do implement it. Say, if I have a formula string as CuFeS2, what the D should be?

**Comment by Sperrylite-MattNg** [comment]
Ok I'll write it up and send it to you.

**Comment by Sperrylite-MattNg** [comment]
[Chalcopyrite Calculated specific gravity worked example.pdf](https://github.com/Bruker-Amics/bugs_features/files/6551299/Chalcopyrite.Calculated.specific.gravity.worked.example.pdf)
Uploading a worked example for chalcopyrite as a PDF file. (Hope this works)

**Comment by MarkGuo7** [comment]
That's awesome. I will give it a try for sure.
Well let you know if need any further helps. (most likely will :))

**Comment by AHM-amics** [comment]
Thats Great! 
Some comments to think about:
How do we search the reference database for the unit cell parameters? By formula or name? Or both. WhatiIf someone has a non-standard formula?
Also, the database is for minerals. What about for alloys or other man-made phases?. Is it somehow possible to have default unit cell parameters for different types of phases, e.g. metal oxides, slags etc

**Comment by MarkGuo7** [comment]
@bernie1034 

Here is the latest build with mineral density calculation. Please give it a try to see it is make sense.
https://bruker-my.sharepoint.com/:u:/p/junfeng_guo/EcRJDME8x_tNrRvBTulW4i4BwwXfrcItoVYhG9hfMfeYfw?e=CG4bLK

Please try the Average Atomic Weight as well.

For some reason, I couldn't @Sperrylite-MattNg. 

Test steps:
1) Change Formula
2) Click the Parser button
The Density and Average Atomic Weight will update.

![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/9aba7b21-e978-43c1-a0bf-d4b465346eee)

**Comment by Sperrylite-MattNg** [comment]
@MarkGuo7 Chalcopyrite's mean atomic number should be around 23.5. Ok, I'll calculate it out for you and send it to you.
