### ISSUE TITLE
BUG - MAJOR - AMICS 3.2_ - PROCESS - Image Export of Specific Mineral - BSE Underlay Shows

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#272]
When I export images of only selected minerals, the exported image shows the BSE underlay even though the viewed image in Process does not. There is apparently no way to disable the BSE underlay in the exported image (I tried toggling the underlay etc etc).

The exported image should be identical to the one shown in Process (i.e. white background by default or BSE underlay only if it is enabled).

Issue is in 3.2 and 3.3.  

Slight correction: Not sure it is the BSE underlay that's showing - see below - but it's a dark layer of some sort. Either way though, needs to be exactly the same as the image shown in Process.
![image](https://user-images.githubusercontent.com/84986921/186947960-b7ffbe65-2634-48d5-8e4f-ea6f6cb4ad9f.png)
What it should look like:
![ScreenImage](https://user-images.githubusercontent.com/84986921/186948301-87ffe38c-6b4a-41ae-b0f0-4ef107eb6445.png)

**Comment by ChiLyMan** [comment]
Hey Matt,

I just checked this on the upcoming build and seems to have been resolved (at least for me :))

Here is what the Process image looks like with Albite_1 highlighted. NOTE Albite_1 is Primary List
![image](https://user-images.githubusercontent.com/84643841/187747642-c901b03d-5dbe-41b4-bdfc-6e0a32c0849c.png)
Here is the exported image.
![SampleH01-Particle_2_Mineral_Albite_1_Image](https://user-images.githubusercontent.com/84643841/187747699-8f2d624b-050a-460d-8731-10650414254f.png)

Here is the same area with BSE Underlay enabled
![image](https://user-images.githubusercontent.com/84643841/187747926-2cb7d04e-93e1-4139-925c-627f70a04de2.png)
Here is snippet of the exported image (GitHub didn't like the large file size :))
![image](https://user-images.githubusercontent.com/84643841/187748023-960148fe-980f-4c34-a2c3-479bd94d01d9.png)

If you want to I can figure out a upload location if you want me to try on your data? And promise I will download and test it!!

Chi

**Comment by ChiLyMan** [comment]
PS: If anything the BSE Underlay image does not look like AMICS. The Alpha channel setting seems off. I'll talk to Mark tonight to see where we can change this so the BSE is more visible.

**Comment by ChiLyMan** [comment]
Tested this out with some more of Matt's data and it would seem when exporting a "Block" measurement is different from "Particle" measurements.

When I export the block image from test data from Matt, the outcome look the same with and without BSE Overlay (even though Process shows a difference).
![image](https://user-images.githubusercontent.com/84643841/187995761-3d2ec188-82a5-4e17-ad06-c3f1d99474bd.png)

However, when exporting  Particle measurement the export image are correct, tested on Matt's data and also my test data.
![image](https://user-images.githubusercontent.com/84643841/187996722-174fef14-f1c8-4269-8fcd-dba5bf95902e.png)

Is there a difference in the export setting for "Block" versus "Particle" measurement?

**Comment by GGloy** [comment]
@ChiLyMan - I tested this in version 3.3.0.1864 and seems fine - please confirm and close the issue if ok. Thanks!

**Comment by GGloy** [comment]
@MarkGuo7 I think we can close this one
