### ISSUE TITLE
Add Comment Field to Each Spectral Reference in Ore Type

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#273]
Not urgent but can a comment field / text box be included for each reference spectrum please?

This will allow user comments such as which sample collected from, whether collected directly or generated from the measurement, details such shaping speed, etc etc. This will really help keep track of the reference spectra, their quality etc.

**Comment by ChiLyMan** [comment]
Hey Matt,
I'm actually working on updating the material reference library right now, to both expand the number of "base reference" spectra but also expand the descriptors for each species.

I'll make a note we need to add some descriptors at the base spectra level as well.

**Comment by Matt-Power** [comment]
Great, thanks. Can we have the ability to sort the spectra by priority / state too please? It would be great to be able to see which are the priority ones quickly without scrolling through the list (or should I log this as separate item on Git hub?)

**Comment by ChiLyMan** [comment]
Let me start a new "issue" where everyone can through in all the new ideas for spectra, since we are making the changes anyway.
I'll close this one for now.
