### ISSUE TITLE
Ability to Duplicate Standard Within Current Ore Type

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#274]
It would be really useful to be able to duplicate standards within an ore type so you can use the same standard but with a different "State". There are workarounds but they are clumsy and usually involve making a series of completely new standard entries. It is possible to duplicate but only to a different ore type (the current one does not appear in the list).

**Comment by Matt-Power** [comment]
Looking at this further...

Is the logic:
1. The spectra are parsed through only standards with a "High" state first, then only those with a "Normal" state, and then with a "Low" state or
2. The spectra are parsed first with only the High state ones, then both the High and Normal, and then all standards at the lowest confidence?

I think that the logic should be the first scenario - would make most sense and be the most predictable but in the example below, it would imply logic is the second case. This pic shows that although the apatite standard is set to High, it is matching below the threshold of the high state (set to high=95, normal=60 and low=40).

![image](https://user-images.githubusercontent.com/84986921/187747682-c959e4b1-7ee4-4723-8641-f05a81bb21bf.png)

But... conversely, there are plenty of examples in the data where this is not the case. In the example below, the first 3 matches are all above the threshold for the low state (the standards all have a Normal state) - this would fit with the first logic scenario. 

![image](https://user-images.githubusercontent.com/84986921/187748404-fe3a8024-c2d6-4105-832c-6c9f318bdedc.png)
 
Whichever logic case is being used, it certainly appears that there is an issue and may well be related to issue #271

**Comment by MarkGuo7** [comment]
@Matt-Power Hi Matt, thank you for the suggestion. I will make the same oretype duplicate available shortly.

And I fixed one issue yesterday which make cause the classification matching bit off.
Simple reason is we normalize the standards before matching. If you classified with same result, the standards will be normalized twice. Each normalization will change the spectrum bit by rounding from double value to integer value.

So the matching may a little bit different between each normalization. 
Gerda found this issue, and that's may your case as well.

**Comment by MarkGuo7** [comment]
By the way, I am working on classification issue now. If you have any questions, please let me know.

For your case, you can send me this frame with the issue xray. Or you can try to classify with the same standard list but from Oretype to see if this issue still there.

I fixed this issue and you can try the latest build if you like.

**Comment by Matt-Power** [comment]
Hi Mark,

This measurement was classified straight from the ore type so I don't think it's the rounding issue you describe. I'll send over an example over with spectra that don't make sense bookmarked.

**Comment by MarkGuo7** [comment]
@Matt-Power Hi Matt

I am confused the logical. Let's make it clear. 

Let's say, you have three standards:
S1: High
S2: Normal
S3: Low

The Matching settings are:
High: 95
Normal: 60
Low: 40

One spectrum match S1 by 89, match S2 by 75.
What's your expectation?
Currently, this xray still classified as S1. Is it right?

**Comment by Matt-Power** [comment]
@MarkGuo7 Hi Mark,

For the case you describe, I would expect the result to be S2 (S1 may be the best match but it does not meet the High threshold so is rejected).

In the two screenshots I've included, I would expect the result to be Apatite in the first example (Apatite_Std does not meet the 95 threshold so rejected and instead Apatite is selected as it is a Normal standard and matches best above the 60 threshold). In the second example [slight edit - assume that all are set to Low], there are 3 standards that would exceed the Low threshold of 40 so rather than Unknown, the result should be Chlorite_(Ca) - best match and above the Low threshold. [In the actual screenshot, the standards are all Normal so the classification to Unknown is correct.]

**Comment by MarkGuo7** [comment]
@Matt-Power Thanks Matt

I will send you an update to try when you have time.

**Comment by ChiLyMan** [comment]
@MarkGuo7 Was an updated version sent to Matt? 
@Matt-Power If sent have you been able to test it?

**Comment by Matt-Power** [comment]
@ChiLyMan and @MarkGuo7  Just tried it in 1508 and it works, thanks.
