### ISSUE TITLE
Update to reference Spectra

### ISSUE THREAD

**Issue by ChiLyMan** [Bruker-Amics/bugs_features#275]
All,

As we are already looking at updating the material library, i.e. expanding "standard" base species and expanded detailed information on each species. Please use this add your suggestions here on new idea/features which would make your life easy or more efficient with the material library. I will use this to reference back as we build what the new library will look like and how it functions.

Matt has already suggested added a comment linked to each species to understand origins or level of certainty etc for each collected spectra

He has also suggested adding a priority for each spectra which can be used to sort which spectra is more "important".

**Comment by Matt-Power** [comment]
I'd like a quick sort feature directly in the mineral list pane please (and all lists e.g. current and ore type, grouped etc and regardless of which tab you are on). Something like clicking on a header to sort by mineral name, priority, ID, order created (or just an X to undo any ordering) etc etc would be good.
Currently to order the list, you have to go to the Standards pane, open up a dialog box, and do in there (way too many clicks and buried).

**Comment by Matt-Power** [comment]
Ability to move standards up and down in the Ore Type (i.e. in the common standards list) - and add the ability this (and any sorting applied) to be saved / persistent. This would really help organise Ore Types and make them easier to "read".

**Comment by Matt-Power** [comment]
As above but a drag and drop function would be really handy.

**Comment by Matt-Power** [comment]
And drag and drop standards across mineral groupings. Using the pop-up window is much less interactive and blocks off things (like the ability to view the spectra) as you work which makes things clunky and slow.

**Comment by jonathan-knapp** [comment]
I think it will be useful to have a relational link to samples. In the future we want to have standards as a database object, so we can include any metadata around the sample in that object. I also like the idea of more "notes" fields that are stored in many areas.
