### ISSUE TITLE
 X-ray data with calibration image and other calibration image requirements automation 

### ISSUE THREAD

**Issue by GGloy** [Bruker-Amics/bugs_features#278]
It has been requested (Adelaide Uni) that when we capture the calibration image to also include the x-ray data. 

I understand that that particular X-ray data will be valid only for those specific parameters and will be removed if parameters change.

**Comment by MarkGuo7** [comment]
@GGloy  We can capture a xray with calibration image for sure, but we don't know how to use it. 
So need to make it clear what's their needs.

**Comment by jonathan-knapp** [comment]
We need to write a requirement for all calibration image requirements that @ChiLyMan will need for image pre-processing in Python.

**Comment by ChiLyMan** [comment]
If we want to complete a correct flatfield correction need to include a workflow process to capture a true flatfield. Would also be good to capture a darkfield as well to do darkfield correction of the images.

**Comment by jonathan-knapp** [comment]
OK. We need to make a document with the full requirements. Step-by-step procedure for example. We can have a meeting to discuss in a few weeks.

**Comment by jonathan-knapp** [comment]
Did we start a document for this? We will not do any automation steps in 3.3.1 (save for 3.3.2), but getting the document requirements done is important.

**Comment by GGloy** [comment]
I Just clarified with Adelaide what they want - I will put something together from my side - this is just calibration image requirements not Flat field correction
