### ISSUE TITLE
How to differentiate version 3.3 with 3.2?

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#279]
Their desktop short cuts are same:
Should we use version number in the names like Esprit?

![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/20385787-7623-44bf-81f0-92ea07f2da72)

And how about the installed folder?
Seems we use "AMICS-" as 3.3 folder. It doesn't show which version.
We may have version 3.4, 3.5 later, so need to make these names and folders more specific.

**Comment by jonathan-knapp** [comment]
Yes. Let's also update the icon for AMICS 3.3 to be something that looks different. The "i" is hard to see.
