### ISSUE TITLE
Assign Project and Repository Before Measurement

### ISSUE THREAD

**Issue by jonathan-knapp** [Bruker-Amics/bugs_features#282]
Request from the University of Adelaide (and me!). In the sample, the grid be able to assign a project and repository before measurement so the sample will be saved to the appropriate folder.  

![image](https://user-images.githubusercontent.com/84199532/192842487-3b73553b-4298-446d-b677-7f002a0052c4.png)

**Comment by GGloy** [comment]
@knapp-amics I believe this one can be closed as well
