### ISSUE TITLE
Mineral on-off, Modal Percent, and Direct Selection of Mineral Groupings

### ISSUE THREAD

**Issue by jonathan-knapp** [Bruker-Amics/bugs_features#283]
It is important to centralize some key features into the mineral "key" for the current mineral groupings. 
- The selection of the mineral grouping in this area should be the selection from the properties window. This means that changing the grouping updates the screen. 
- The minerals should include the current modal data. This moves it from the property window and allows it to be seen in all tabs. NOTE: THIS NUMBER WILL ONLY UPDATE UPON RECALCULATION AND WILL NOT REFLECT NEW STANDARDS. This also means that the number will only be updated for the mineral grouping if it is selected at recalculation. Perhaps we can add a "refresh" button that would update for groupings?
- The mineral toggles. To make this effective need to add an "all on" and "all off" button. 
- The "off mineral"  and "on mineral" transparency settings from the settings dialog box would also be useful. 

![image.png](https://images.zenhubusercontent.com/60a274843870252752494569/ee45aaff-981f-44fe-a804-3b451b96230b)

![image.png](https://images.zenhubusercontent.com/60a274843870252752494569/f177a28e-9b01-44cd-b712-af0e2a0b3010)

**Comment by jonathan-knapp** [comment]
@MarkGuo7 this is the next highest priority after you have finished working on hypermap mode. We need to make any changes to the look and feel ASAP so we can take screenshots and movies for the HTML help, training, and presentations. I very much want to make this update and any other *quick* updates to the UI library we can (like dark mode) soon.

**Comment by ChiLyMan** [comment]
The selection of the mineral grouping in this area should be the selection from the properties window. This means that changing the grouping updates the screen. 
**(Changing Groupings will update the Sample Image and Particle view, but Calculation Table will not update unless you click away and back again)**

The minerals should include the current modal data. This moves it from the property window and allows it to be seen in all tabs. NOTE: THIS NUMBER WILL ONLY UPDATE UPON RECALCULATION AND WILL NOT REFLECT NEW STANDARDS. This also means that the number will only be updated for the mineral grouping if it is selected at recalculation. Perhaps we can add a "refresh" button that would update for groupings?
**(Completed and working)**

The mineral toggles. To make this effective need to add an "all on" and "all off" button.
**(Completed and working)**

The "off mineral" and "on mineral" transparency settings from the settings dialog box would also be useful.
**(Not available)**

**Comment by ChiLyMan** [comment]
Tested on build 1854 still the same behavior.
