### ISSUE TITLE
BUG_MAJOR_AMICS-3.3.0.1315_PROCESS_BATCH: report live does not work any more

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#287]
Process ver 3.3.0.1315
The report live function no longer works in the batch process. It goes through all samples but does not report the selected mineral(s). (I looked in the excel log file and it is not in there either.)

I tried this several times with just the default "Unknowns" selected and also a few other random phases selected but nothing worked.

**Comment by scarlett-01110011** [comment]
Same

**Comment by Matt-Power** [comment]
Still not displaying in 3.3.0.1508

**Comment by GGloy** [comment]
@MarkGuo7 lets look at this on Monday - the values are not the same as from the results....

**Comment by GGloy** [comment]
@MarkGuo7 there is a reported value now, but it's not the same as in the result...You should be able to repeat with the batch files I shared.

**Comment by ChiLyMan** [comment]
Version 3.3.1
Reporting but value is still showing minor deviation from value reported in Process less than 5 percent.

**Comment by AlexeiDolgolyov** [comment]
@ChiLyMan, I think it's linked to #1171. Should we close it too?
