### ISSUE TITLE
Particle export - add option to export particle images as "real size" or "fixed size" and the ability to specify the pixel size for fixed size. 

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#288]
Ver 3.3.0.1315
I've been using the new particle export function (potentially great!) but all of the particle images come out exactly the same size regardless of the particle size. In this case 55 x 55 pixels (not sure what dictates that size). This means that the particles all look the same size. In the images below the top grain is 100 microns in diameter, the lower one ~3 microns in diameter. This also means that the larger particles are not only substantially down-graded but the single pixel particles are over-sampled.

The images should be exported with the same pixel dimensions as the original image. (Or if each image has to be the same
dimensions, this needs to be set based on the widest and highest particles in the set.)
  
![47663-min](https://user-images.githubusercontent.com/84986921/193937737-0800aedf-5bbe-4870-8d17-5f95603ca480.png)
![6389-min](https://user-images.githubusercontent.com/84986921/193937875-076ee5c1-acf4-4a99-b2e5-28f0c924afe1.png)

**Comment by jonathan-knapp** [comment]
@ChiLyMan this was a feature that we needed to train an ML classification model. I have slightly re-framed the issue.

**Comment by MarkGuo7** [comment]
Now will export the real pixel size of each item

:)

**Comment by Matt-Power** [comment]
Great, thank you!

**Comment by GGloy** [comment]
@ChiLyMan this one can be closed
