### ISSUE TITLE
Exporting Calculation Table via Batching in PM

### ISSUE THREAD

**Issue by ChiLyMan** [Bruker-Amics/bugs_features#289]
Can we add an option in the batching export to export an excel file containing calculation tables (i.e. Modal, grain size, element dist. etc).

Maybe in the option page you can select the grouping list, and also check box for calculation data you want to export.

And export it into a single excel file with each tab containing a different calculation table.

**Comment by MarkGuo7** [comment]
If current exporting can do that already, then we can give it a try.
If not, better do it next version.
