### ISSUE TITLE
Unique ID should NOT change every time a mineral is changed! 

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#296]
If I change anything in a standard (colour, density, BSE trigger, whatever), the unique ID changes. This is the unique ID visible in v.3.2 but now hidden in 3.3.0.1315. Is this correct and as intended? It seems like it will cause problems - surely, the unique ID should be assigned when a standard is created and then remain the same after that? 

For instance, if the unique ID is used to define the input to the spectrum tree and the grouping manager, this will mean that any tweaks to a mineral will break the workflow.

Similarly, a unique ID is not assigned when I create a standard, only when one of the properties is edited. For instance, if I create a standard and copy data and name from an existing entry, no unique ID is assigned. If I then change the colour (or any other property), a unique ID will be assigned at that point. Surely, every standard should be assigned a unique ID when the reference spectrum is created?

**Comment by jonathan-knapp** [comment]
@ChiLyMan we need to resolve this so it will work with BIFROST. Let's write up a specific requirement for Mark so he can implement UIDs that work.

**Comment by MarkGuo7** [comment]
Since need to understand more about what's the UUID means for Minerals and in what case the UUID should be kept or change. For the moment, there is an option in Tool Options to change it every time or not.

![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/57d1aec8-900a-431c-86a9-6e4c7229f311)
