### ISSUE TITLE
BUG-MAJOR_AMICS-3.3.0.1315_PROCESS_SPECTRUM TREE: steps have lost the mineral assignments

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#297]
v 3.3.0.1315
All of the spectrum tree steps associated with my ore types have lost their mineral assignments in v 3.3 so do not work.

Is this because the 5 digit ID is now being used to refer to the standards (rather than the names)? If so, great, makes much more sense and is more reliable (and if you rename a standard, it doesn't break the tree). If using unique ID though, this is going to cause issues as it changes all of the time (see #296).

If this is because of changes to the way spectrum tree works, can you implement a way to copy across old trees and preserve the assignments please?

**Comment by MarkGuo7** [comment]
@Matt-Power Hi Matt

Is it possible that you can show me an example?

**Comment by jonathan-knapp** [comment]
@Matt-Power did you get an example to @MarkGuo7?

**Comment by Matt-Power** [comment]
Not a specific example but I suspect if you open up any of the previous examples that I have sent over for other issues, you'll see that many (possibly all) or the steps embedded in those have lost the assignments. I'll try to send an example when I start the next project (I rip all of the dead entries out of the current ones so nothing useful to hand right now).

**Comment by Matt-Power** [comment]
OK, I've looked into this in a bit more detail:
To reproduce, take any measurement and reclassify through a different ore type (and certainly one that has steps and was created in 3.2 or before). On the example I used, I enabled various steps - but because the branch assignments are missing, this causes the various standards used in the steps to be assigned to unknown. 
If you reclassify again but without the steps enabled, and then look at any of the steps in the spectrum tree tab, you can see that the branch assignments are gone.

**Comment by Matt-Power** [comment]
Just checked and this is still happening in 3.3.0.1508

**Comment by jonathan-knapp** [comment]
@Matt-Power this item has been added to the "In Progress" queue.

**Comment by GGloy** [comment]
@MarkGuo7 this is still an issue - let me know if I need to show you how to repeat.
