### ISSUE TITLE
Energy Range for Standards

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#298]
AMICS Version: 3.2.1.0

Issue.  When using the Energy Range for augmenting the standards definitions there is an issue with low values.

Specifically: it is not possible to enter a low "minimum" value of zero, even though it is possible that the pixel has zero in the specified region. If a value of zero is entered then it defaults to 0.01.

This causes issues as a pixels value of 0.01 which equal the minimum of "0.01" are classified as "failed" when it should be true.  This could be because extra decimal points are compared than shown, or that the minimum value is a greater than, rather than greater than or equal to.

Of course, this does not solve the zero issue which is always classified as failed when it should be true, as a minimum of zero is not permitted to be entered.

**Comment by AHM-amics** [comment]
I have found a solution.  Negative Numbers are allowed!!

**Comment by ChiLyMan** [comment]
We need to add a note to the use (or info tooltip) specifying "-1" should be used to turn off the minimum range.

**Comment by knapp-amics** [comment]
Please reopen this - not working with a 0 is a bug. If no number is entered it should see this as a -1 - this is just to quarks for a user to understand. For now, let’s also make a note in Tips and Tricks in matter most.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MarkGuo7** [comment]
I will push this to next release. Let me know if someone want to bring it back.
