### ISSUE TITLE
Couldn't build

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#300]
![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/08583322-7e1a-444c-8fce-d5225bffea5d)

**Comment by MarkGuo7** [comment]
There is not much information, and seems not space limit issue.

![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/4bdc1f24-607d-4850-a00e-4b5c2707f669)

**Comment by MarkGuo7** [comment]
Still got problem. Seems caused by UTF-8 coding. May need helps from Rob.

![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/2c3a1d1c-2196-4e3d-a973-b3d156e05d03)

**Comment by robbmcleod** [comment]
I switched the Python script to be back to UTF-16 on loading resource files. There are, however, some errors with building CommonLib that I think are not related:

```
C:\local\AMICS\deep-ci\deep-source\CommonLib\ImageMatchCalc.cpp(67,25): error C2352: 'SiftStitchCalc::CalcKeyPoints': illegal call of non-static member function [C:\local\AMICS\deep-ci\deep-source\Commo
       nLib\CommonLib.vcxproj]
         C:\local\AMICS\deep-ci\deep-source\CommonLib\ImageMatchCalc.cpp(76,25): error C2352: 'SiftStitchCalc::CalcKeyPoints': illegal call of non-static member function [C:\local\AMICS\deep-ci\deep-source\Commo
       nLib\CommonLib.vcxproj]
         C:\local\AMICS\deep-ci\deep-source\CommonLib\ImageMatchCalc.cpp(81,29): error C2352: 'SiftStitchCalc::MatchKeyPoints': illegal call of non-static member function [C:\local\AMICS\deep-ci\deep-source\Comm
       onLib\CommonLib.vcxproj]
         C:\local\AMICS\deep-ci\deep-source\CommonLib\ImageMatchCalc.cpp(178,25): error C2352: 'SiftStitchCalc::CalcKeyPoints': illegal call of non-static member function [C:\local\AMICS\deep-ci\deep-source\Comm
       onLib\CommonLib.vcxproj]
         C:\local\AMICS\deep-ci\deep-source\CommonLib\ImageMatchCalc.cpp(187,25): error C2352: 'SiftStitchCalc::CalcKeyPoints': illegal call of non-static member function [C:\local\AMICS\deep-ci\deep-source\Comm
       onLib\CommonLib.vcxproj]
         C:\local\AMICS\deep-ci\deep-source\CommonLib\ImageMatchCalc.cpp(192,29): error C2352: 'SiftStitchCalc::MatchKeyPoints': illegal call of non-static member function [C:\local\AMICS\deep-ci\deep-source\Com
       monLib\CommonLib.vcxproj]
```

**Comment by MarkGuo7** [comment]
Thanks Rob

I can take care of these building errors for sure.

**Comment by MarkGuo7** [comment]
@robbmcleod Hi Rob

Need your help again. 
I updated the resource file CommonLib.rc and the build is ok on my computer.
But the build script failed seems there are invalid letters.

With thanks,

![image](https://user-images.githubusercontent.com/84481724/196597341-8fb4b6d3-ba06-4e76-9600-7e889963bf74.png)

**Comment by robbmcleod** [comment]
Hi Mark,

You clearly changed `CommonLib.rc` and `AMICSResource/res/AMICSResource.rc` from UTF-16 to UTF-8, because two of the three .rc files are half the size.

![file_sizes](https://user-images.githubusercontent.com/5999769/196992414-5f915959-e401-45ea-87b9-bf8e1b0fbe29.png)

Do you have settings in Visual Studio that are causing these files to be automatically changed? It may be the `.editorconfig` file or something else?

I usually use Visual Studio Code to change text file types. E.g.

https://github.com/Bruker-Amics/deep-source/commit/88177947fb1d50c10378700858d8bd352a81f7b6

**Comment by MarkGuo7** [comment]
@robbmcleod Thanks Rob

No ideas why. I will double check today.
