### ISSUE TITLE
Batch processing from project level causes crash

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#301]
v3.3.0.1315
Been playing with the project manager and have created a test project of 4 samples.
If I double click on a measurement to load it / make it active then go to batch process, select "From Project Level", Process closes almost immediately. 
Btw, the ore types had already been loaded at this point too.

If I do the same without having loaded a measurement, it seems to work - the measurement picking box comes up as expected.

**Comment by MarkGuo7** [comment]
@Matt-Power Thanks Matt

I will take a look of it.

**Comment by ChiLyMan** [comment]
Could this be the issue with processing an open file we had discussed before with Van?

**Comment by GGloy** [comment]
@knapp-amics sorry, another one that can be closed.
