### ISSUE TITLE
Cross field mineral touchup

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#303]
Will do mineral touchup cross field.

![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/c0067924-d940-4716-b3c5-1aa234fdc76c)

**Comment by ChiLyMan** [comment]
Seems to be working about 95% of the time for both mapping and particle analysis. The final 5% will still need some manual touchup.
