### ISSUE TITLE
Match Status of Reliability Distribution

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#304]
Show the Match Status, with different unknown matching reliability distribution table.
Can pick the segments of selected cells and go to spectrum tree to pull the selections.

![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/00cd3edd-952c-469d-bce5-9d840be9f97b)

**Comment by GGloy** [comment]
@knapp-amics Is this what Rio wanted? If good enough please close. Tx
