### ISSUE TITLE
Load only current ore type with measurement

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#308]
Related to the original request to not load all ore types and issue #305 (corruption of ore types if you do not load) - is it possible to automatically load the current ore type when a measurement is loaded? 

If I am working on a project, I usually want to work on just the current ore type so I don't need the whole library to be read / loaded but I do need the current ore type to be available. The loading of all ore types takes a lot of time, especially if I am trying to work through several samples quickly. 

If the other ore types are needed, maybe there can be a button or tab where they are selected (and only those selected are read in)?

**Comment by jonathan-knapp** [comment]
@MarkGuo7 this is something that both Matt and Andrew feel strongly about. Ideally, the ore type would be visible in the list, but only load when selected.

**Comment by MarkGuo7** [comment]
This is a good one. Should we do it with 3.3?

**Comment by jonathan-knapp** [comment]
We are going to include this as a requirement for AMICS 4 when we switch to a shared resource file. It will be much more efficient.
