### ISSUE TITLE
Improved beam calibration

### ISSUE THREAD

**Issue by knapp-amics** [Bruker-Amics/bugs_features#31]

**Comment by MarkGuo7** [comment]
Need more clear. 
The issue facing and suggestions etc.

**Comment by knapp-amics** [comment]
Yes. Let's discuss.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Matt-Power** [comment]
I think that this relates to the feature I raised on Teams:

Allow beam calibration at multiple mags and scan rates to compensate. Add ability to use a combination of BSE and EDS to determine offset - e.g. X-ray line scan over the edge of the Cu standard to ensure BSE image and beam position are synchronised.

Currently missing a lot of bright phases even at 32 µs scan rate despite very little apparent image shift. Potentially have to re-do calibration every time a new mag or scan rate is used. Problematic even in normal runs where disseminated pyrite is routinely missed.

**Comment by MarkGuo7** [comment]
Should we have an option to calibrate at the beginning of each measurement?
Let's give it a try.

**Comment by Matt-Power** [comment]
Yes, I think that would be useful, thanks. 
I don't think that the offset changes much over time so it would be great to add a calibration routine where a series of magnifications and scan rates are done as part of an automated routine - a calibration table of offset for each scan rate and mag could then be constructed and used during measurement. The idea would be to run this as part of a monthly calibration routine.
The calibration at run-time option would be great for making sure that critical runs (e.g. precious metals) are successful and the calibration table would be great for more routine measurements where placing the beam isn't quite so critical (but still important).

**Comment by MarkGuo7** [comment]
Thanks Matt, I will give it try.
@knapp-amics Somehow, I couldn't @Matt-Power from this page.

**Comment by Matt-Power** [comment]
Great, thanks - good luck!

**Comment by MarkGuo7** [comment]
@Matt-Power One more question, Matt, do you notice that the beam offset may relate to the mag?
I will find some machine time to test that, but guess you already know that. Thanks

**Comment by Matt-Power** [comment]
I'm pretty sure it's related to mag (as well as scan speed) but I haven't done any careful testing / checking. Patrick may know better though.
