### ISSUE TITLE
Upgrade BCG soft package

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#310]
We bought the new BCG UI package. 
Need to upgrade the AMICS UI component.

**Comment by jonathan-knapp** [comment]
No hurry.



-Bruker Confidential-
From: Mark Guo ***@***.***>
Sent: Monday, October 24, 2022 7:55 PM
To: Bruker-Amics/bugs_features ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Bruker-Amics/bugs_features] Upgrade BCG soft package (Issue #310)

**EXTERNAL EMAIL**

We bought the new BCG UI package.
Need to upgrade the AMICS UI component.

-
