### ISSUE TITLE
BUG - MINOR - AMICS 3.3.0.1315 - PROCESS -  Importing standard from spx file hangs until progress bar widget is "wiggled" with mouse

### ISSUE THREAD

**Issue by jkabel** [Bruker-Amics/bugs_features#314]
Importing a spectrum file or files of a standard will hang until the displayed progress bar is grabbed with the mouse and moved around slightly.

**Comment by Matt-Power** [comment]
Just to add: I've also seen this behaviour at various other times / places - usually when doing something with standards or ore types though. I'll try to make a note of where.

**Comment by MarkGuo7** [comment]
Still the case?

**Comment by jonathan-knapp** [comment]
Can we check this one to see if it still happens after the UI update?

**Comment by ChiLyMan** [comment]
Tested on build 1854 and do not get any hang up requiring widget wiggling when importing SPX or MSA spectra files. Though as my license is offline license, I do get a "Need Online license to control the machine!" message, but the spectra still import correctly.
Maybe the import function is triggering a similar operation as Collect so it is looking for the machine?
Guess this can be closed for now.
