### ISSUE TITLE
Run Fail due to fail to drive stage to position 

### ISSUE THREAD

**Issue by Aoife-Adelaide** [Bruker-Amics/bugs_features#315]
Hi, 
I have now had this issue a few times where my run will fail because it stops being able to drive the stage to the correct position. When it fails it doesn't turn the beam off. This one failed at 8pm on a Friday so the beam sat on until 9am Monday morning. 
Log file attached. 
[Investigator32_2022_10_28_11_25_19-RUN FAILED DUE TO STAGE UNABLE TO MOVE.log](https://github.com/Bruker-Amics/bugs_features/files/9897003/Investigator32_2022_10_28_11_25_19-RUN.FAILED.DUE.TO.STAGE.UNABLE.TO.MOVE.log)

**Comment by jonathan-knapp** [comment]
@ChiLyMan can you check the Esprit settings? I want to make sure this is a bug and not a settings issue.

**Comment by jonathan-knapp** [comment]
@ChiLyMan can you check the Esprit settings? I want to make sure this is a bug and not a settings issue.

**Comment by ChiLyMan** [comment]
Once you get IT to allow remote access let me know and we can check the system set up.

**Comment by jonathan-knapp** [comment]
Any progress on this?

**Comment by MarkGuo7** [comment]
Couldn't see it yet. Need to repeat it first.

**Comment by ChiLyMan** [comment]
Still waiting for IT to prove remote access to the system.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Aoife-Adelaide** [comment]
Apologies, IT are taking forever to allow us to remote access. I’m hoping it will be working this week.

Aoife

**Comment by jonathan-knapp** [comment]
@ChiLyMan did this ever get resolved? I will close it now. Please have run as a service issue if still present unless a bug is found.
