### ISSUE TITLE
Spectrum Tree - Decimal resolution in display - V3.3

### ISSUE THREAD

**Issue by scarlett-01110011** [Bruker-Amics/bugs_features#316]
Thank you for adding the ability to make cuts in the spectrum tree using decimal places (V3.3.0.1315).

Could you please enhance the display to show the same resolution for **percentage** as displayed in **absolute**, under binning properties?

Currently the spectra display only shows integers for percentage.

![image](https://user-images.githubusercontent.com/117055041/198923844-8e2f234d-8bd8-4c48-9c44-8a2ccdfb51de.png)

**Comment by MarkGuo7** [comment]
Sure, Scarlett, I will give it a try.
By the way, any other properties you want to do the same?

**Comment by scarlett-01110011** [comment]
Thanks, Mark, 
I mainly use **Count Clustering** at the moment. 
Although since you asked, I think for **Energy Filtering** and **Ratio Clustering** it could also be useful to visualise the data in this way.

**Comment by MarkGuo7** [comment]
@scarlett-01110011 Hi Scarlett

From my version, it seems already been cut by two decimal points:
![image](https://user-images.githubusercontent.com/84481724/199652689-599fc20b-7ab0-4168-88bb-c42e7e464dfa.png)
