### ISSUE TITLE
BUG-MAJOR_AMICS_PROCESS_CALCULATION: different Values in Calculation Tables for Segment vs Particle

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#319]
v3.3.-.1315
Only tried on mapped measurements so far but I get slightly different values if I switch from segment to particle layer. When I switch back, the data remain the same i.e. don't change back to what they were before. Why is there a difference in the first place and why does the difference go away once the particle layer has been selected?

To reproduce: select the segment layer first, then go to the calculation table. Then switch to the particle layer - the data will change slightly. If you then switch back to the segment layer, the values do not change again i.e. the values shown by the particle layer are preserved, even though the data are recalculated when switching between the two.
Switching to the grain layer makes no difference, it is only switching to the particle layer where the change happens.
One cleanup step is enabled.

**Comment by jonathan-knapp** [comment]
@MarkGuo7 take a look at this. Perhaps we fist just need to understand what is happening.

**Comment by GGloy** [comment]
@MarkGuo7 I noticed that there is still a change when I convert a block mode mapping sample - maybe something in the process of that conversion, maybe when stitching fields?

**Comment by MarkGuo7** [comment]
@GGloy Thanks Gerda, could you show me when you have time, today or next year :)

**Comment by ChiLyMan** [comment]
Just tested on build 1508 and it looks like it might be a rounding issue? Moving from Segment to Grains seems ok, its only when you move from Grain Layer to Particle/Frame. Looks like the numbers being rounded from 2dp to 1 dp are causing the issue...for the most part.
[https://app.zenhub.com/files/368966218/e704e67a-ad07-43bd-b6c5-821bcd851b95/download](https://app.zenhub.com/files/368966218/e704e67a-ad07-43bd-b6c5-821bcd851b95/download)
[https://app.zenhub.com/files/368966218/c80fb453-9172-4b0a-9431-1e11f9370436/download](https://app.zenhub.com/files/368966218/c80fb453-9172-4b0a-9431-1e11f9370436/download)

**Comment by GGloy** [comment]
@MarkGuo7 With a converted mapping measurement there are differences between the frame layer and Segment/grain, and it is not just a rounding error.

**Comment by ChiLyMan** [comment]
For case of switching layers, the calculated values seem to be the same now on version 3.3.1
