### ISSUE TITLE
M4 Particle de-agglomeration needed

### ISSUE THREAD

**Issue by GGloy** [Bruker-Amics/bugs_features#320]
I am sure this is issue has been raised multiple times, but I cant seem to find it so I am just adding it again.

With the M4 data we added the ability to "particulate" the data but there is no ability to de-agglomerate touching particles.

Measured particles:![image.png](https://images.zenhubusercontent.com/60af4a22d2c5ea1082755c53/9d890cc9-e42b-47e1-afef-731280205234)

Line-up of particles showing the issue with touching particles.![image.png](https://images.zenhubusercontent.com/60af4a22d2c5ea1082755c53/af6abc3c-5aca-4d44-85ae-527c96b11b7f)

**Comment by ChiLyMan** [comment]
@GGloy Would it be possible to get a copy of the M4 data for me to try/test. I've only got SEM data.

**Comment by GGloy** [comment]
Hi Chi

Here is an example.

https://1drv.ms/u/s!AkdTTtfgGtY6oGEw9pPpsiiWkZUj?e=v2d9EQ

Regards!
Gerda

**Comment by ChiLyMan** [comment]
@MarkGuo7 Has this been resolved with the new build allowing for measurements to be fully converted from "Maps" to "Particles"?

**Comment by GGloy** [comment]
I think this can be closed, yes, we can now de-agglomerate the particles.
