### ISSUE TITLE
Measurement area is not saved when reopening Investigator

### ISSUE THREAD

**Issue by scarlett-01110011** [Bruker-Amics/bugs_features#321]
Drawn measurement areas in Investigator (V3.3.0.1315) work well in the same instance. 
However, when the .ivst file is opened again, the measurement areas are not in the same position - even after saving the file. 
The overview is saved correctly. Usually the number of fields remains the same, as in the screenshot, but it is clear in this sample because it has a small surface area, that the measurement area was shifted.

![image](https://user-images.githubusercontent.com/117055041/200716266-4be9d214-a5e6-481c-ac62-49f0c93c42f3.png)

**Comment by GGloy** [comment]
@knapp-amics I believe this issue can be closed
