### ISSUE TITLE
Cut lower count percentage by details in Spectrum Tree count clustering

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#325]
This request is from Rio. If they focused on small percentage of count range, they want to see bit more details to cut.

**Comment by GGloy** [comment]
@knapp-amics Jonathan, can you follow up with Rio if these changes are good enough for their needs or need further tweaking?

**Comment by jonathan-knapp** [comment]
I definitely see what they're talking about now. Let me see if I can get some screenshots from them and demonstrate. Essentially they're just not showing the bars between the integers. So the majority of the display on the lower part doesn't show up.
