### ISSUE TITLE
Save Before Applying Stitching - Changes Not Saved

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#326]
V 3.2.1.261
When stitching fields, if you hit Save before toggling / applying the field stitching, the result is not saved. Once save is hit, it is greyed out so it looks like the stitching is saved (but in reality, is not). The save button remains greyed out even after you apply the fieldstitching so you do not have an option to re-save. This is a significant "gotcha", especially when stitching lots of measurements (= brain is switched off). 

The Save button should only become active after the stitching has been applied (and not during the stitching process). Or, if the intention is to allow users to save mid-way through stitching (i.e. to create a save point in a big measurement), a dialog box should be included (only when saving before applying), asking if stitching should be applied or not (and apply the stitching before saving if the answer is yes).

**Comment by GGloy** [comment]
@MarkGuo7 This has not changed - let me know if you need me to show you.

**Comment by ChiLyMan** [comment]
tested on build 1854 still same behavior.

**Comment by GGloy** [comment]
@ChiLyMan in build 1961 this seems to be doing the right thing?

**Comment by ChiLyMan** [comment]
I’ll check this tomorrow, new build already…

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ChiLyMan** [comment]
@Matt-Power The system will spit a warning out now preventing the data to be saved while still in field adjust mode.
