### ISSUE TITLE
Investigator - not all fields measured (and sometimes too many)

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#327]
Thought that I'd logged this previously so apologies if a duplicate. 
Ver 3.2.1.261
For certain projects (no idea why but some projects are prone to this way more than others), when I specify an area of 9x11 fields, the first few samples will run OK and all 99 fields will be measured but then for subsequent samples, an area of 8x10 will be measured (i.e. a column and a row are missed). This is even though I copy all settings from the first measurement so that all are identical. All are marked as having completed successfully (even those with the missing fields).

If I terminate the measurement and restart, Investigator will go back and measure the "missing" fields. However, for some samples, it will go back and start again (even though the measurement has been marked as completed successfully). 

I have tried re-creating the block holder file etc but this keeps on re-appearing although for some projects, it seems fine.

Let me know if you need the logs and I will send.

**Comment by ChiLyMan** [comment]
Matt,
Could you send the logs through for the failed projects please.
Chi

**Comment by Matt-Power** [comment]
Ok, just sent you a link - there are a couple of instances in there.

**Comment by ChiLyMan** [comment]
Thanks Matt, just going through the logs now. Looking at the MRE data looks like you rerun the same to "infill" the missing field?

**Comment by Matt-Power** [comment]
That's mostly a function of the bug. I think that the sequence of events was that I saw the missing fields thing happening, so I stopped the instrument and cleared the offending measurement (there were some successful ones earlier in the batch which I left). When I restarted, it went back to one of the previous measurements (which are marked as "succeed") and started measuring the extra adding fields around the edge.

I may have tried to force it to do the extra fields too but I can't remember. Either way, the only way to prevent it adding extra fields to those marked "succeed" is to switch them off before restarting.

**Comment by ChiLyMan** [comment]
Thanks Matt, it looks like all the 22177-00x measurements all terminated after 35 field without error. It is as if the measurement loop set it to loop to i = 35. This will need to wait for Mark to get back from break. Let me follow up with him when he gets back from leave.

**Comment by ChiLyMan** [comment]
@Matt-Power Is this still happening?

**Comment by ChiLyMan** [comment]
@Matt-Power I will close this for now if you have not seen this behavior recently. We can open again if we see it again.

**Comment by Matt-Power** [comment]
@ChiLyMan I do see it regularly but not installed any of the more recent 3.3 builds (just installed 1983 on the 5000 and will do the same on the 3900 today) so go ahead and close for now and I'll reopen if it is still happening.
