### ISSUE TITLE
Secondary channel not acquired

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#329]
Ver 3.3.0.1399
Both Channel Images tick box is selected but only the primary channel is collected. 
Ch2 is shown in Esprit so it is being acquired (by Esprit at least) and Investigator Ver 3.2.1.168 works fine.

**Comment by GGloy** [comment]
Secondary image works fine in vs 3.3.0.1811 - however I noticed that if both channels are not selected in Esprit, AMICS will not acquire both images. This ticket can be closed.
