### ISSUE TITLE
MicroXRF and BSE values - Spectrum Tree BSE Failure

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#332]
MicroXRF and BSE values that are assigned when the data is imported into AMICS and the "pesudo-BSE" image is created (i.e. the total X-Ray intensity image)
 
From a cursory look hovering around the image, the so called BSE values are really useful. That is, low signal areas like resin or pores or vesicles are dark and minerals are various grey shades. This is great.
 
However, when trying use the BSE values in the spectral tree, the software always fails and I am not sure why.
 
The ability to use these values in microXRF would be great and could be classified as a new capability. The ease of which to remove a background and particulate would be fantastic.
 
So question is: is this possible? What is the issue with using these values in the spectrum tree? Is it a small bug because it is "microXRF" data? Or something more fundamental. Could it be "missing data", that is, are some pixels missing BSE Values?

**Comment by ChiLyMan** [comment]
Just checked with M4 data from Andrew and it is possible to use the pseudo-BSE value from M4 in both version 3.2 and 3.3. 
It could be a PC issue preventing Andrew from processing the M4 data this way.

version 3.3
![image](https://user-images.githubusercontent.com/84643841/212977687-071d0d2c-5ce8-4254-a3b0-bf9e432d6d62.png)

version 3.2
![image](https://user-images.githubusercontent.com/84643841/212977854-01a2d11d-e753-43a7-978b-44d787f1724e.png)

**Comment by AHM-amics** [comment]
Hi All,

I can confirm that this does seem to be the case.  Currently it is working for me also.

It is strange, but I do seem to have issues that appear to be computer related rather than AMICS related.  Any bugs I observe I will try to verify on a separate PC.

Salduos,
Andrew
