### ISSUE TITLE
Particles Not Combined Across Frame Boundaries

### ISSUE THREAD

**Issue by scarlett-01110011** [Bruker-Amics/bugs_features#334]
Large particles are not being combined correctly across frame boundaries, even after stitching.
Screenshots show a single particle that is being treated as two separate particles in AMICS.

AMICS version 3.3.0.1508

![image](https://user-images.githubusercontent.com/117055041/211466436-fc807628-04a3-40bf-a7df-82a38c66f613.png)
![image](https://user-images.githubusercontent.com/117055041/211466942-c507ccae-1070-4c57-b76b-bc6fa17194ff.png)

**Comment by jonathan-knapp** [comment]
@MarkGuo7 I have seen this. They have big particles, and I don't know what impacts it. Let me know if you have any questions.

**Comment by MarkGuo7** [comment]
Hi Scarlett, could you use shift key + mouse to select this particle to see how many there?

Not sure how it happened. After you selected the particle, could you try to remove deagg-points?

![image](https://user-images.githubusercontent.com/84481724/211468078-cfbfd005-2087-4275-b9f9-fcd6c6bdaa40.png)

**Comment by MarkGuo7** [comment]
If anyone can share an example with me, that would be great.

**Comment by scarlett-01110011** [comment]
Hi Mark, thanks for your reply.

There are many particles as you can see by the blue lines. 
I have also included the red frame boundaries to show that it doesn't happen on all frame boundaries within a particle, but only some.

I tried the remove deagg points for that middle particle and it didn't fix it. It actually re-agglomerated that smaller particle at the top (circled in green).

![image](https://user-images.githubusercontent.com/117055041/211469162-70e87913-aa73-42d7-9dc1-00e7ade75dd9.png)

**Comment by MarkGuo7** [comment]
Hi Scarlett

Could you to change this parameter to see if it helps?

![image](https://user-images.githubusercontent.com/84481724/211472425-200be797-efdf-4280-b250-6bb7f0d4bcd1.png)

**Comment by scarlett-01110011** [comment]
When I change the number it doesn't apply, it always changes back to 1000000

**Comment by MarkGuo7** [comment]
Hi Scarlett, is it still there? Any updates? I will close it for the moment. Let me know if you need to discuss.

**Comment by scarlett-01110011** [comment]
Hi Mark, changing the particle size limit to -1 fixed the problem and I haven't seen it since. Thanks

**Comment by MarkGuo7** [comment]
@scarlett-01110011 Thanks Scarlett
