### ISSUE TITLE
Export Screen exports a different image when particles are sorted

### ISSUE THREAD

**Issue by scarlett-01110011** [Bruker-Amics/bugs_features#336]
In the Sample Images tab with a Sort Direction applied (e.g., Descending by Area), the Export Screen option doesn't export the same image from the AMICS screen.

V 3.3.0.1508

![image](https://user-images.githubusercontent.com/117055041/211719814-8f75ab7b-42e2-45fa-aac6-8ab48334a899.png)
![image](https://user-images.githubusercontent.com/117055041/211719877-f3bbd990-1f11-4377-9956-c5c92ad619f0.png)

**Comment by ChiLyMan** [comment]
Confirming that the Export Screen does not function correctly, and will send further update as some of the other tabs also seem wrong.

@scarlett-01110011 you can export the sorted particles by using the Export Image instead (but you will get all particles.

**Comment by GGloy** [comment]
@MarkGuo7 still not exporting the lineup when screen is selected (vs3.3.0.1838) This function also does not work in last 3.2 version BTW

**Comment by ChiLyMan** [comment]
Tested on build 1854 and exporting the screen still not working as expected.
This is the screen, and the grains displayed are what is expected to export when "Export Screen" is selected:-
![image.png](https://images.zenhubusercontent.com/62f264fb4831bda01fb7d454/681f9ca9-2900-4bea-8b81-167e5e3fd245)
But this is what is exported when selecting export screen:-
![VL-22177-004-Seg_Mineral__Image.png](https://images.zenhubusercontent.com/62f264fb4831bda01fb7d454/ea002563-d352-466e-bf08-5ddfe2844e31)

**Comment by GGloy** [comment]
@MarkGuo7 I think this can be closed
