### ISSUE TITLE
BUG-MAJOR_AMICS-3.3.0.1508_PROCESS_GROUPING: Images not updating when mineral grouping colours are changed

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#337]
v 3.3.0.1508
First off, I love that the panel on the left is now being used to switch the view in the main image, thanks!
But... if you make changes to the group (e.g. change colours, add new groups etc), the main screen image does not update. You have to cycle back to another mineral group and back or toggle BSE on / off to see the changes. Ideally, the image should refresh to show the new colours when the editor is closed. (It would be even better if the main image changed while the editor window is open and as the edits to the groups are done in real time but I'm assuming this would be slow / difficult.)

**Comment by MarkGuo7** [comment]
Thanks @Matt-Power , I will fix it.

**Comment by jonathan-knapp** [comment]
@Matt-Power this item has been added to the "In Progress" queue.

**Comment by ChiLyMan** [comment]
Just checked in build 1854, and still the same behavior.

**Comment by GGloy** [comment]
@ChiLyMan in vs 1858 - if you change the colour, it does not update immediately, but if you select and unselect any mineral it will update

**Comment by MarkGuo7** [comment]
Didn't update the grid grouping color on the left

**Comment by ChiLyMan** [comment]
Checked in 1911 and the grouping color is changing in the left hand panel, but the main screen still does not automatically recolor the image when the editor is closed. You still need to wake it up by causing an action to force an update (switching to BSE, changing group, selecting a mineral on and off...etc)

**Comment by ChiLyMan** [comment]
Checked in build 1940 and working in both Matrix Mapping and Segment Mapping mode colors will change once exited from edit po-up window.
