### ISSUE TITLE
BUG_MAJOR_MAJOR_AMICS-3.3.0.1508_PROSCESS_CLASS: unresponsive after reclassification

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#339]
v3.3.0.1508
When I reprocess a sample through a new ore type, AMICS completes the reclassification but is unresponsive. It shows the BSE image and the lower banner shows that the measurement has been successfully loaded but when I click on anything in AMICS, I get the Windows "bong" sound. Seems that there is a dialogue box open somewhere but I can't see it or get to it by using Alt-tab, Win-tab etc etc. 
I have to kill AMICS and reload the measurement (and the ore types) to get back to where I was - really time consuming.

I have AMICS set so that Progress on top is disabled.

**Comment by Matt-Power** [comment]
I have tried fiddling with various options (progress on top, docked side panel) with no success. After every time I reclassify a measurement, I have to kill Process in task manager and then restart, reload the measurement, and then load the standards. This takes upwards of 10 minutes each time which makes it pretty much unusable except for viewing the measurements.

Seems like there is a message box hiding somewhere but I can't get it active / can't see it etc. Tried escape and various other keyboard inputs but no luck.

**Comment by ChiLyMan** [comment]
Matt, I'll have to catch up with you tomorrow. I just downloaded the sample you uploaded and reclassify with another oretype, and had no problem reclassifying. And Process remained responsive.

Maybe need to have you show me so I can see what you are doing that is different from me. Could it be a touch up step or classification step?

**Comment by ChiLyMan** [comment]
OK finally was able to replicate the issue both on 3.3.0.1508 and also on newer build 3.3.0.1537. The AMICS Process will only encounter this freeze after reclassification when using the single reclassification option. The funny thing is when I was trying this before it would not freeze on me, but now it will freeze every time regardless of if I reclassify using the same OreType (i.e. refresh) or use another OreType from the common library. See attached video.
It's unclear to me, but this behavior happened after I made modification to one of the OreType in the standard library, but the freeze now happens even if I reclassify using a completely different library.

The workaround I've found for this is to reclassify using the Batch processor, which seems to avoid the final freezing of AMICS Process. I'm going to do some more tests, including removing and reinstallation of AMICS, as I did not encounter this issue at client site recently and we reclassified many databases multiple times.

https://user-images.githubusercontent.com/84643841/217327416-ad57c6a2-dae5-472f-b6e0-f79320f61f4c.mp4

**Comment by ChiLyMan** [comment]
Update:
* Did an uninstall of both 3.3.0 and 3.2.1 from the system, and then reinstalled 3.3.0.1537 but still encountered the same freezing after reclassification issue.
* Uninstalled 3.3.0 again, but this time I did a manual wipe of all AMICS related files in the ProgramData folder as well as the Program Files folder.
* Reinstalled 3.3.0.1537 plus 3.2.1.270 (as 3.3.0.1537 is still looking for the ProgramData/AMICS folder for "shared" resources). Reactivated my license, and after fixing the missing the UserSTD.db file and permissions issues with the OreTypes.db file, AMICS Process is now back to "normal".
* In fact the system seems to be working faster, and the progress bar is working normally again. I noticed now that when 3.3.0 became faulty, the progress bar (loading samples, reclassification etc) didn't report percentage progress and the bar itself was jumping around like crazy. But after this refresh, the percent progress is once again being reported and the bar slowly progresses matching the reported percent progress.
* It clear a file in the ProgramData folder became corrupted which somehow only affected version 3.3.0 and not 3.2.1 (I tested 3.2.1 reclassification and it worked even though 3.3.0 didn't).
* I will continue to try breaking 3.3.0.1537 again to try to figure out which file became corrupted.

**Comment by ChiLyMan** [comment]
@Matt-Power Did the above refresh resolve the reclassification issue on your version?

**Comment by Matt-Power** [comment]
@ChiLyMan Yes, this did resolve the issue. I have no idea what caused it initially so I suspect it will happen again but all good at the moment.

As a note for others, make sure you back up your license and UserSTD.db files first. The UserSTD.db does not contain spectrum tree steps or groupings, only ore types, so you will lose those - you have to reload from archived measurements.

**Comment by ChiLyMan** [comment]
Thanks Matt, 
I've going park this issue to a backlog while I continue to try to figure out what is getting corrupted, as this will take a lot more work to figure out as it not repetitive bug during normal AMICS Process operations.

But I'll leave a "troubleshooting" note.
Chi

**Comment by jonathan-knapp** [comment]
Hey guys, this has been parked as high priority since Feb 8th. Is it still active as an issue>

**Comment by ChiLyMan** [comment]
I've not had this issue reoccur after rebuilding AMICS, and even after several updates. Also not heard similar issues from any users so unless Matt you have encountered this again we will add it to our user manual troubleshooting guide and close this one.

**Comment by Matt-Power** [comment]
Not seen this one for a bit so I think it is fixed, thanks.
