### ISSUE TITLE
Measurement file copying exe to allow and assist in copying files from multiple SEMs and work station PCs

### ISSUE THREAD

**Issue by Sperrylite-MattNg** [Bruker-Amics/bugs_features#34]
The exe will help to keep the files together. Especially when 1 large project may be measured on multiple SEMs. Files are then copied to a central location (server) and then to workstation PCs for QA/QC checking and then copied back onto the server.

**Comment by MarkGuo7** [comment]
Is it means free version Result viewer?

**Comment by knapp-amics** [comment]
Not quite. Let's discuss in detail. The changes we discussed today to the file would make this as easy as copy and paste.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
