### ISSUE TITLE
Hybrid Segmented / Bright Phase Measurement

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#342]
Would it be possible to include bright phase functionality into the normal segmented or mapped analysis? The standard segmented mode (and certainly the mapped mode) is insufficiently detailed to catch small bright phases or if you crank up the detail, the measurement takes far too long so it's way quicker to do two measurements but this involves a lot of duplicated instrument time.

For instance, if I want to image a block sample to get the broader rock fabric but also get additional detail for any small bright phases such as Au or PGM, I currently have to run using a segmented or mapping mode and then rerun using a BPS mode. This means that I collect 2 sets of BSE images, often at the same resolution which means there is a significant time overhead.

If there was a hybrid mode, the sample could for instance be run with a decent BSE resolution and a low res map, and if any bright phases are present in the field, that detail can be "upgraded" in the area of the bright phase.

**Comment by jonathan-knapp** [comment]
I think this falls into the "drive back" workflow, but I am not sure. Do you think this is a trigger that happens when the SEM is on that frame or at the end it will drive back to that location?

**Comment by jonathan-knapp** [comment]
I think this falls into the "drive back" workflow, but I am not sure. Do you think this is a trigger that happens when the SEM is on that frame or at the end it will drive back to that location?

**Comment by Matt-Power** [comment]
I don't think this requires driving back - it's just a BSE trigger in the current field (exactly the same as the BPS) so the additional mapping of over the bright phase happens immediately after the main segmented or mapped image is acquired. So really just merging existing BPS with the Map and Particle modes.

Notionally it would be:
BSE image acquired as normal
BSE image is segmented for mineral imaging as normal (or gridded for mapped measurements) 
Bright phase recognition is done using same BSE image (i.e. no need to re-acquire)
Mineral image is acquired based on segments as normal
Detailed imaging of the bright phase is done
Go to next frame etc etc

Could be an option in the map and particle modes (e.g. "Include BPS" tick box in the menu on the right and if enabled, you get the same options as currently in the BPS).

This goes hand in hand with the image binning too - you could do a detailed BSE for the bright phase but that image is binned for the segmentation of the mineral image to save time (the BPS uses the full res BSE). This would give major time savings over doing two runs.

I'm mainly thinking of block mode BPS measurements where a small swatch surrounding the bright phase is imaged but I think the granular measurements would benefit too.

**Comment by MarkGuo7** [comment]
@Matt-Power Hi Matt

Do you think the Segment trigger option will work for this request?
Basically, you can do fine mapping on any bse range or triggered minerals.

![image](https://user-images.githubusercontent.com/84481724/216851775-15a02616-5d40-47cf-aa78-3142cdf3e871.png)


![image](https://user-images.githubusercontent.com/84481724/216851792-d5a55912-ffae-4645-adad-1443b2b7d826.png)

**Comment by Matt-Power** [comment]
I guess it might do for closely sized, very fine particulates but I don't think that it would work for much else as it would take too long. 

For instance, I'm looking for PGMs in exploration samples so running mainly unsized or block samples and need basic modals and mineral images (from a coarse map or fairly rudimentary segmented image) but I need detailed information about the PGM - associations etc as well as the composition. Using the triggers, I think that the whole field would be measured in detail which is way too time consuming (I haven't used it so I might be missing something though). The block mode BPS where a small area is segmented in detail works very well for this (although I'd like more control over the bounding box size) but it does mean that every sample has to be run twice - a significant time overhead during measurement as well as in post-processing (two sets of images so stitching, processing etc is repeated).

You could merge the functionality into the triggers settings but for PGM and other really small stuff, the 1 micron size limit is going to be a problem in a lot of cases. The option for a segmented mode as well as the map would also be handy (and vice versa, I don't think that there is a mapping mode in the current BPS which would be useful).
