### ISSUE TITLE
BSE Image Binning

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#343]
Currently the segmented image is based on the high resolution BSE image but there are many times where I need a decent resolution BSE image (e.g. 1 micron per pixel or better) but don't need a correspondingly high resolution mineral image (and in most cases, I don't have the time / instrument capacity to run at higher resolutions).

Can we have a mode where the BSE pixels are binned (options for 2x2 and 4x4 would be good) and the mineral segments are derived from the binned, lower resolution image but the original high resolution BSE image is kept as the BSE layer Process?

**Comment by jonathan-knapp** [comment]
Yes, this is a good idea. I think this fits into a larger workflow to pre-process the BSE image in some way before applying segmentation.

**Comment by MarkGuo7** [comment]
@Matt-Power Hi Matt

I think showing image with option 2x2 or 4x4 is easy, but need to think how to present it because you loss details.
You want to average value? 
And what to do if two xrays fall in same merged pixel?

**Comment by Matt-Power** [comment]
@MarkGuo7 Hi Mark,

I think an average value would be appropriate but there is probably something more intelligent out there (something along the lines of a sharpening algorithm or whatever). 

On the other point, given that binned image will be used for the segmentation, the X-rays should never fall in the same pixel or am I overlooking something?
