### ISSUE TITLE
Re-classification slower vs 1537

### ISSUE THREAD

**Issue by GGloy** [Bruker-Amics/bugs_features#345]
Re-classification in the current build is slower that using vs 3.2 - more noticeable when using large files. In my specific case classification in vs3.2 took ~5minutes, while the same file in 3.3.0.1537 took ~17minutes.

(result file already shared with Mark)

**Comment by Matt-Power** [comment]
@GGloy @MarkGuo7 
I've come across the same / a similar issue but it seems to be related to investigator: samples acquired using 3.3.0.1537 reclassify way slower than those acquired with 3.2.1.261. (In both cases, I am reclassifying using 3.3.0.1508.)

The samples that I am running at the moment take ~3 mins to reclassify if acquired with 3.2 but well over 30 mins to reclassify if they are acquired with 3.3. This bad enough for a single sample but is an absolute disaster if running more than a couple.

**Comment by Matt-Power** [comment]
Done of bit of testing and comparison - it looks like this is two separate issues - reclassification is generally a lot slower in 3.3 vs 3.2 but there is also a massive difference between which version the measurements were acquired on. I'll raise this as a separate issue.

**Comment by jonathan-knapp** [comment]
@MarkGuo7 seems this is the same issue. I added the mission-critical tag to this, but let's remember they are linked.

**Comment by jonathan-knapp** [comment]
Thanks all. We have the separate issues open
