### ISSUE TITLE
Cleanup un-x-rayed segments for mapping measurement - error message

### ISSUE THREAD

**Issue by GGloy** [Bruker-Amics/bugs_features#346]
When selecting cleanup un-x-rayed segments from a mapping measurements it causes an error message- (mapping measurements do not have un-Xrayed segments) This causes a lot of issues when running particle and mapping measurements with a cleanup step for un-X-ray segments in a batch - need to handle this better.

![Cleanup un-xrayed.PNG](https://images.zenhubusercontent.com/60af4a22d2c5ea1082755c53/52b9a741-e69d-4af7-8d3c-902effb07292)

**Comment by MarkGuo7** [comment]
It shouldn't clean unxray for mapping results.

**Comment by ChiLyMan** [comment]
Tested on build 1854 and Cleanup button is now greyed out for mapping results preventing users from accessing these options which are not valid for Mapping. Once converted to Particle (and saved) the Cleanup option becomes available and all work.
