### ISSUE TITLE
BUG_MINOR_AMICS-3.3.0.1399_INSTALLER: Cannot Be Installed Fresh

### ISSUE THREAD

**Issue by jkabel** [Bruker-Amics/bugs_features#347]
This versions complains of missing the UserStd database and the GlobalMineralFile.

**Comment by ChiLyMan** [comment]
@MarkGuo7 A fresh install of AMICS 3.3 creates a AMICS-3.3 folder in ProgramData, but installs a UserSTD.db.install and UserSTD_M4.db.install, which need to be renamed by removing the ".install" to make it work.
Plus when starting AMICS for the first time it will then create the shared resource folder AMICS in ProgramData, but does not copy over the "SystemData" folder. 
The work around right now is for the user to manually copy the Data and SystemData from AMICS-3.3. to AMICS in the ProgramData folder, and rename the two UserSTD file by removing the .install suffix.

If the user has already been using a previous version of AMICS, this should not occur, will only happen on a fresh PC build.

**Comment by jonathan-knapp** [comment]
@robbmcleod and @MarkGuo7 has this been fixed?

**Comment by ChiLyMan** [comment]
Just checked after complete uninstall and removal of all folders in ProgramData and fresh build now is OK
