### ISSUE TITLE
BUG-MINOR-AMICS_PROCESS_STANDARDS: become locked out

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#348]
If I duplicate an ore type to a new one, then add to it, the properties of the original standards can become locked so I cannot change the name, colour, BSE etc etc. If I then duplicate the standard within the new ore type, that entry is also locked so I can't even create a copy, edit and then delete the old standard.  This happens even after I have reclassified samples with it. 

It seems that this can happen quite a while after the new, duplicated ore type is created.

However, if I reload the ore type, the entries become editable again. This occurs even if I am only working on one sample (i.e. the ore type should not get out of sync). Not sure what triggers it (I will try to find out).

Not a big deal now that I know that reload clears it but one to watch out for.

**Comment by GGloy** [comment]
Can be closed
