### ISSUE TITLE
Spectral Reference "States" Not Preserved in 3.2 vs 3.3

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#349]
Ver 3.2.1.261
The state / priority of standards is not preserved correctly in the ore types (e.g. several of my high priority spectral references show as "Normal" in 3.2). Not tested but I think this is when an ore type is created (or possibly edited) in 3.3.

This is a snippet from 3.2:
![image](https://user-images.githubusercontent.com/84986921/219133172-2e5fc4ae-d279-4902-bd2a-9ff6c571d089.png)

This is the same list (and same sample) in 3.3:
![image](https://user-images.githubusercontent.com/84986921/219134908-02e1a4b8-b573-48a6-b6e8-76e67dabd5ad.png)

Could be a bit of a gotcha for anyone needing to flip between 3.2 and 3.3.

**Comment by MarkGuo7** [comment]
Hi Matt

Seems fine on my computer. May need you to show me.

**Comment by ChiLyMan** [comment]
@Matt-Power Is this still happening?

**Comment by ChiLyMan** [comment]
Tested this on v1983 and 3.2.0.252.
Made new dictionary in 3.2.0.252 and then opened in 3.3.0.1983, and priorities were retained. Then tried editing it in 3.3.0.1983 and priorities retained in both versions.
@Matt-Power Can you check this so we can examine further (maybe jump on your system) or close.

**Comment by ChiLyMan** [comment]
@Matt-Power Closing this for now, we can review if you see this behavior again.
