### ISSUE TITLE
Can measurement file size be reduced any more?

### ISSUE THREAD

**Issue by Sperrylite-MattNg** [Bruker-Amics/bugs_features#35]
Can measurement file size be reduced any more to help with file loading in AMICs' Process and also for "long term storage" once project is complete.

**Comment by MarkGuo7** [comment]
I guess the real request is to reduce the xrays collected, which will speed up our measurements.
These xrays are zipped but too many.

**Comment by knapp-amics** [comment]
Mark, let's explore options for archive compression and other options.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by jonathan-knapp** [comment]
This will be addressed in three ways. First, we are looking at matching that can be done with less counts, that will speed up measurement and make file size smaller. Second, we are going to have the hybrid mode soon that will result in less x-rays. Third, we will try to make the entire file something that can be compressed. Thanks for the feedback, we know it is an issue.
