### ISSUE TITLE
MAJOR_BUG_Junk Mineral Size Data when Converted Block=>Granular

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#350]
3.3.0.1508

When a block measurement is converted to a granular measurement, the mineral size distribution data is incorrect (looks like the finer size groups are missing). The retained % does not add to 100% and the cumulative starts at a high value which does not match the retained %.

**Comment by MarkGuo7** [comment]
Hi Matt, is it still so with the latest version?

Could you take a look of this latest version? https://bruker-my.sharepoint.com/:u:/p/junfeng_guo/EYFFpjFOZQJPoXRH3QwuDUYB6pTLxSXujC0ro_fTtIWixw?e=2Q5afX

Please let me know if still have it.

With thanks

**Comment by ChiLyMan** [comment]
@Matt-Power have you had a chance to test using 3.3.1? I don't have appropriate test data to test this bug.

**Comment by Matt-Power** [comment]
Yes, think this has been fixed now, thanks.
