### ISSUE TITLE
BUG-MINOR_AMICS_PROCESS_CALCULATION: Mineral Associations Not Available in Block Measurements

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#351]
3.3.0.1508

Mineral association is not available in any of the layers in block measurements. I'm pretty sure that this was available in v3.2, if not, it's a significant omission.

You can convert the measurements to granular but this causes issues elsewhere.

**Comment by MarkGuo7** [comment]
This calculation should be in the frame layer. Please give it a try and reopen this if still have issues.
