### ISSUE TITLE
BUG-MAJOR_AMICS3-3.3.0.1537_PROCESS_CLASS_Reclassifying Measurements Acquired by 3.3.0.1537 are Extremely Slow (>30 mins)

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#354]
Reclassifying measurements that have been acquired using 3.3.0.1537 takes forever using Process 3.3.0.1508.

The same measurements acquired using 3.2 reclassify fine and measurements acquired using 3.3 but reclassified with 3.2 are also OK.

In all cases, the measurements are being reclassified against a new ore type (and the ore type used is the same). Both mapped and segmented measurements show similar behaviour.

Some example reclassification timings (same measurement):
Acquired 3.2.1.261:
Classified with 3.3.0.1508: 4:47
Classified with 3.2.1.261: 3:15

Acquired 3.3.0.1537:
Classified with 3.3.0.1508: 36:26 (not a typo - over half an hour)
Classified with 3.2.1.261: 3:20

Work arounds are not ideal as there are other bugs that mean that I can't classify using 3.2 (e.g. the matching is inconsistent - fixed in 3.3). Also had issues with 3.3.0.1537 junking measurements so not tried to reclassify with that.

**Comment by jonathan-knapp** [comment]
@MarkGuo7 let's mark this bug as mission-critical and address it ASAP.

**Comment by MarkGuo7** [comment]
@Matt-Power Sorry about that.

Could you try the newer version?
There is an option there to switch off the Unknown matching data:

![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/8bcfbf4c-e5a4-4012-8818-8cceb1cc51e5)

I guess most case you don't need it, unless want to understand the unknown matching.

Let me know if the classification is still slow.

**Comment by Matt-Power** [comment]
@MarkGuo7 
With the unknown matching switched off, the processing speed is back to normal (i.e. not super-slow). However, the unknowns are not displayed at all - all unknown segments disappear (no marks show, everything is white / background).

Unfortunately, this makes processing the data impossible.

**Comment by MarkGuo7** [comment]
@Matt-Power Terrible sorry Matt

The new option I added stops to identify the unknown.
It should be fixed with the latest version.
