### ISSUE TITLE
BUG-MINOR_AMICS-3.3.0.1660_PROCESS_VIEWER: Mineral On/Off - not all minerals enabled at group level

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#356]
v3.3.0.1660
Really like the mineral On/Off feature - massive time saver, thank you.

However, not all minerals have the option to be switched on / off when a grouping is selected though. For instance in the image below, both calcite and illite have no selection box despite being a major constituent of the sample. The individual minerals within the calcite group do have on/off selectors at the Primary Mineral List view level though (just the grouped view that does not fully work).

![image](https://user-images.githubusercontent.com/84986921/230988601-316f4f05-07c8-4d6c-ac05-3f3f4cbcb573.png)

**Comment by jonathan-knapp** [comment]
Thanks, Mark is working on this now.

**Comment by Matt-Power** [comment]
@MarkGuo7 and @knapp-amics this works much better in 3.3.0.1694, thanks!

Only slightly niggle is that you can only select one mineral at the grouped level - if more than one is selected, only the most recently selected shows. Also, if you then unselect some of the minerals, things can get a little odd (e.g. previous selected mineral shows or the currently selected one or neither). Multiple selections work fine at the primary level though.

Apart from that small issue, it's a really nice feature, thanks.

**Comment by jonathan-knapp** [comment]
Matt, we're going to update the UI library next week and that may sort out some of these issues. If not coming, we'll revisit this more soon. Thanks for the comment. I know Mark has been working hard on this.

**Comment by ChiLyMan** [comment]
Seems to be fixed in version 3.4.1 (master branch)
