### ISSUE TITLE
Duplicated mineral standards not showing

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#358]
v 3.3.0.0.1660
When I use "Dulpicate to here" the mineral standard is not automatically listed in the ore type. To get the duplicated standard to show, you need to reload the ore type which is time consuming.

This function did work in previous versions (e.g. v 3.3.0.1508).

**Comment by jonathan-knapp** [comment]
@Matt-Power this item has been added to the "In Progress" queue.

**Comment by GGloy** [comment]
Can be closed (vs 1846)
