### ISSUE TITLE
Keyboard Shortcuts for Expand/Collapse?

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#359]
v 3.3.0.1660

The keyboard shortcuts are a real help, thanks.

It would be great to assign a shortcut for expand and collapse of lists but I can't find it in any of the options (only those commands accessed from the toolbar tabs are shown). Is it possible to add some of the context specific items too (like expand/collapse) please?

**Comment by jonathan-knapp** [comment]
Perhaps think about it and make a list of missing commands?



-Bruker Confidential-
From: Matt-Power ***@***.***>
Sent: Tuesday, April 11, 2023 11:15 AM
To: Bruker-Amics/bugs_features ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Bruker-Amics/bugs_features] Keyboard Shortcuts for Expand/Collapse? (Issue #359)

**EXTERNAL EMAIL**

v 3.3.0.1660

The keyboard shortcuts are a real help, thanks.

It would be great to assign a shortcut for expand and collapse of lists but I can't find it in any of the options (only those commands accessed from the toolbar tabs are shown). Is it possible to add some of the context specific items too (like expand/collapse) please?

-
