### ISSUE TITLE
BUG-MINOR_AMICS-3.3.0.1660_PROCESS_GRAIN PANEL: Blank Image / Unsupported Layer error

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#360]
v. 3.3.0.1660

When switching to the Grain Panel, the image is blank and there is a label saying "Unsupported Layer" regardless of what layer is selected or what the measurement type is.

However, if you select the touchup steps and hit "Filter!", the images reappear and everything works as normal.

**Comment by jonathan-knapp** [comment]
Thanks Matt. We are going to investigate a lot of the tab issues in the next two weeks. Sorry this bug is presenting.

**Comment by ChiLyMan** [comment]
This is still the case in 1829, but this seems normal since the first time your select grain panel the user has not created any filter. Maybe rather than "unsupported layer" just have "No Filtering results."?

**Comment by ChiLyMan** [comment]
Just tried 1838 and Mark already changed the title :)
