### ISSUE TITLE
BUG - MINOR - AMICS 3.3.0.1660- PROCESS - BATCH - Batch files selection box is always blank

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#361]
and 3.3.0.1508 

If you open the batch file dialogue from the main toolbar, the combo / list box of batch files is always empty even when several exist. To load an existing batch file, you have to use the down arrow by the Create button and use the file manager dialogue to find it. If the batch is run again, the batch selection box is still empty and you have to repeat the process (i.e. there is no persistence and the list box never becomes populated). 

Batch calculations do work.

This did work in previous versions (e.g. 3.2).

**Comment by GGloy** [comment]
I think this can be closed.
