### ISSUE TITLE
Xray buffer fail error popup

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#362]
v. 3.3.0.1660

Not seen this one before but I now get it very regularly (only in 3.3.0.1660). It happens when I open up a measurement. However, it is random and usually happens after opening / closing several measurements one by one (e.g. to extract images out sequentially through a project - can't use batch because of the white line issue...). Once it occurs in an instance of Process, it happens every time I open a file. I have to close that instance and open a new instance of Process and start again.

![image](https://user-images.githubusercontent.com/84986921/231819518-17532123-f276-4095-9a88-0b4c8d6ee80b.png)

It means that certain things don't work. For instance, exporting images will often not work (the workflow appears OK but the file is not actually exported). It's not always consistent.

Note that it is independent of a specific measurement. 

It also might be linked to an issue where the batch image export fails (not logged as I think it is the same as this). The batch will start off OK but after a few samples (sometimes 5, sometimes up to 16 but rarely any more) it will fail and either stall the export or the batch will just keep going but will show 0 of 1 images exported. No error message boxes show when this happens though.

**Comment by jonathan-knapp** [comment]
@MarkGuo7 seems to be a memory issue

**Comment by Matt-Power** [comment]
Just to add, the image export fail will also happen without the error popup (e.g. after several measurements, the export will go through the motions but no image will actually be saved).

Also getting several more out of memory errors than usual (I've got 32Gb installed and these are not huge measurements).

**Comment by MarkGuo7** [comment]
Hi Matt

Is it still there? I will close it for the moment. Let me know if you want to discuss.
