### ISSUE TITLE
Unknown Segments Not Showing

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#363]
Measurements acquired in 3.3.0.1694 do not show unknown segments - they are shown as background and the Xray point markers are not shown. This makes processing the data impossible as you cannot see what is missing or how much. Investigator 3.3 is therefore not useable.

They re-appear if reclassified with 3.2 (but there are other issues with reclassification in 3.2 - now apparently fixed).

**Comment by MarkGuo7** [comment]
@Matt-Power Thanks Matt

Could you try the latest 1701?

**Comment by Matt-Power** [comment]
@MarkGuo7 Sure can - can you send me a link please?

Thanks!

**Comment by MarkGuo7** [comment]
Could you see this link: https://github.com/Bruker-Amics/core/releases/edit/V3.3

If not, I am uploading to my share drive now. Will let you know shortly.

**Comment by Matt-Power** [comment]
Get a 404 using that link. I'll download from your share once it's ready / I've got the link. Thanks.

**Comment by MarkGuo7** [comment]
Here is the link: https://bruker-my.sharepoint.com/:u:/p/junfeng_guo/EXfD6ZDIfHBFpzBGQF7N-CoBvZ46l9XjiEwHwOE5rYaaCg?e=v0AKZE

Let me know if it still doesn't work.

**Comment by Matt-Power** [comment]
All good, downloading now, thanks

**Comment by Matt-Power** [comment]
@MarkGuo7 Just reclassified with 3.3.0.1701 - unknowns are now showing as normal, thank you!!
