### ISSUE TITLE
BUG_MAJOR_AMICS DESKTOP 3.3.0.1785_PROCESS_Selected Mineral Export Not Working

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#364]
v3.3.0.1701
With the new mineral select functionality (which is great), unfortunately the export of images with specific mineral(s) selected no longer works - the exported image has all minerals showing (i.e. just a normal mineral image).

**Comment by jkabel** [comment]
This is also present on v3.3.0.1694

**Comment by MarkGuo7** [comment]
Yes, the mineral filter doesn't work with sorting and exporting

**Comment by ChiLyMan** [comment]
Exporting images with minerals selected will now generate an image with the selected minerals highlighted, but unselected minerals should be made transparent. Right now it just seems to change the color of the other minerals.
Original 
![image.png](https://images.zenhubusercontent.com/62f264fb4831bda01fb7d454/10ae4da3-1d14-485d-a3f9-3d32cf27f7e2)

With Calcite Selected (Blue)
![image.png](https://images.zenhubusercontent.com/62f264fb4831bda01fb7d454/168e724a-b5c5-46f9-a69f-a72bb089e818)
