### ISSUE TITLE
Batch: Change to Relative File Locations (vs Absolute Locations)

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#365]
Batch files use absolute file locations not locations relative to where the batch file is saved so if a project folder is moved (or a shared server location has a different drive letter on different computers etc), the batch files do not work and have to be replicated. For large projects where only specific samples are selected, this can be onerous.

Given that only measurements located in subfolders relative to the location of the batch file, there is no benefit in using absolute file paths and relative file locations would be much more flexible.

**Comment by MarkGuo7** [comment]
This change may also cause issue when you copy a batch file to another place without relocating the result files.
May need an option to let customer decide
