### ISSUE TITLE
Investigator: Warning when holes are out of sequence

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#366]
Training someone to use Investigator has reminded me of a few "gotchas" that need to be addressed. I'll raise an issue for each rather than listing here. This one is the worst and really needs to be addressed asap.

Order of holes in holder:
There has to be a warning box alerting the user if the holes are not in sequential order. Both for new holders and for ones where an older holder file is refreshed. Something like "Sample positions are not is order" with options "OK" or "Reorder" (with reorder sorting them from hole 1 sequentially).

This gotcha is really difficult to spot and results in sample mix-ups where a sample is assigned entirely the wrong name - obviously a really serious issue.

Bit of background in case it helps. If I create a holder file and automatically fill the hole positions, more often than not, they are in the wrong order (usually starting at hole 19 for some reason). If you manually select the holes, the order in which you click determines the order in which they appear in the list. This is fine if you know but for a new user (or if your mind is elsewhere), it's easier and quicker to click on the holes from the top down.

Similarly, if you re-use and refresh an existing holder (e.g. to re-use standard measurements) but one where the order has been changed for operational reasons, it is incredibly easy to miss and therefore mix the samples up.

**Comment by Matt-Power** [comment]
@knapp-amics can we nudge the priority on this one please? It is a serious problem for sample integrity / tracking as it is really easy to inadvertently mix samples up if the holes are not in order (it is super-easy to assign the wrong sample to a hole if they are not in order). This happened to me recently - no idea how the order was changed (must have been a rogue mouse click) but I was lucky to catch it.

**Comment by jonathan-knapp** [comment]
Yes. @MarkGuo7 let's change the priority on this one to critical and work on it after we work on the two export issues (lines between fields and not exporting the transparent image).

**Comment by Matt-Power** [comment]
Thanks

**Comment by MarkGuo7** [comment]
@Matt-Power No problem Matt

I am working on your list now. Will focus on Investigator side first, including this one.

Basically, you want the sample holes in orders, like 01, 02, 03 etc.
Or you need a way to sort the order by yourself?

Any suggestions?

**Comment by Matt-Power** [comment]
Yes, default for a new holder should be sequential 01, 02 etc. 

However, it is also important to be able to change the priority order so please retain that feature.

The main request is that a warning message box should be displayed (with options to keep as-is or reorder) if holes are not in sequential order both for when a new holder is created, and when an old holder file is refreshed / reused. 

(If the holes are jumbled and you don't notice, you get into all sorts of sample mix-up issues.)

It would also be good to nudge samples up and down the run order when the instrument is running (currently, you have to stop the measurement, reorder and then restart).

Thanks!

**Comment by MarkGuo7** [comment]
Hi Matt 

You can change the order any time, even while it is measuring:

![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/6cec4a73-c272-43e9-920c-1530280731e1)

And you can sort the samples on the stage by name, by hole, etc.
AMICS will automatically to pick up the next one to measure.

**Comment by Matt-Power** [comment]
Thanks, good to know that the run order is now dynamic. 

Still need a warning message box when the holes are out of order when the holder file is created or refreshed though. Let me know if you'd like to me to show you what I mean. Thanks.

**Comment by MarkGuo7** [comment]
Sure, Matt @Matt-Power 

I am trying to show this out of order message. Also will give you a way to reorder it.
We may have a meeting after this to review the changes I made in Investigator.

:)

**Comment by ChiLyMan** [comment]
Tested in build 1854, out of order warning still not present. Everything else works great though for sample ordering and sorting.

**Comment by Matt-Power** [comment]
@ChiLyMan and @MarkGuo7  

This is not fixed in 1983:

If you refresh an existing holder file in which samples are out of order, there is no warning and the incorrect order is preserved. This is the crux of the original issue and a massive problem.

Refreshing a holder that is out of order is the one instance where it is absolutely essential to have a warning - it is way too easy to blindly assume that the holes are in order and to then enter the sample names in the wrong place (i.e. if hole 3 is first, you would mix up sample 1 with sample 3 etc etc). This virtually guarantees samples are mixed up. 

When refreshing a holder file with holes that are our of order, please include a warning message box with an option to order by hole number (default) or keep the jumbled up order.

**Comment by ChiLyMan** [comment]
Warning about sample order when "Start" Allow user to manually change it themselves.

**Comment by Matt-Power** [comment]
@ChiLyMan I'm not sure this is entirely relevant to the issue i.e. when you get to "Start" it is almost invariably too late.

Just to confirm (and sorry if I'm labouring the point), the problem comes when an investigator layout file is created with the hole positions out of order (e.g. you click the hole pictures in the wrong order or you use "Renew Current Layout" but where the original layout is not in hole order) - that's where the warning needs to be placed i.e. basically any time when a holder table is created but out of order.

I don't really need a warning before starting a run because it's either too late or I know that I have re-ordered things.

The issue comes where a user is unaware that the layout table is out of order _before_ they populate it so they fill in the sample names from top to bottom (assuming hole order) even though the table is not sorted that way. I have lost count of the number of times I have done this and it is easily done but difficult to catch.

**Comment by ChiLyMan** [comment]
@Matt-Power OK then we need to think how/when we issue this warning(s). Because from your description you are thinking to issue the warning when importing and renewing an old ivst file. But what if you load an old ivst and then add samples which are not in order. Do we issue a warning when we add multiple samples? Or what if we only add one sample at a time out of order, do we issue a warning every time? Or what if someone moves samples out of order, and then adds a sample, do we issue warning?

As a big user of AMICS would love your input into when and how often we need to think about this warning to be helpful without being annoying.

**Comment by Matt-Power** [comment]
@ChiLyMan I think just a simple one - when a new run table is created in Investigator (either through renewing an old one or creating from scratch with the hole picker window thing). In both these cases, holes being out of order is not expected / assumed that all are in hole / numerical order.

In some cases, the user will want to preserve the "out of order" so it just needs to be a warning with and OK button. The user can then choose what to in Investigator itself.

In all other cases, I think that you can reasonably expect someone to be aware of what they are doing and expect them to be paying attention.
