### ISSUE TITLE
Sample and Measurement Name Issues (Unified) 

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#367]
When entering sample names into a holder, duplicates are not allowed (which is good) but there is no warning message which creates confusion.

For instance, if a sample name entered is a duplicate, either the name entered will revert back to default (or, if a holder file is refreshed, the name will just revert to what it was before). In some circumstances, the file name can be duplicated but it is then not possible to read the HW conditions. While this does prevent duplication or overwriting of data (which is great), there is no warning message so novice and even fairly experienced users are totally confused about what is going on. 

Instead of simply reverting the sample name back, there needs to be a message box saying why e.g. "Sample name already exists"

ALSO:
"Cannot edit sample name directly in the sample list (means there are a lot of unnecessary mouse clicks and movement to set up a holder)"

ALSO:
"V3.3.0.1701
When adding measurements from a pre-defined method, please use the method name as the default measurement name.

Currently, the measurement name defaults to the type of measurement (e.g. "Matrix Mapping") instead of the method name."

ALSO:
v3.3.0.1701 (although it is in all versions)

When a measurement is created, the default measurement name is a combination of the sample number and the measurement type (e.g. "SampleID123_Matrix_Mapping". However, the inclusion of the sample name is unnecessary as the measurement file name already includes the sample ID. If the defaults are used, the measurements are all labelled "SampleID123_SampleID123_Matrix_Mapping" i.e. needless duplication of the sample number and results in super-long file names. This means lots of unnecessary editing of measurement names (can be a real chore for 28 samples).

Measurement names also default back to this format when the mode is changed (e.g. from matrix mapping to particle mapping which can be frustrating.

Please just default to the measurement type for the measurement name and omit the sample name (as the sample name is included in the measurement file name anyway).

**Comment by jonathan-knapp** [comment]
@MarkGuo7 I have combined several issues about names into the same issue. I thought you may want to adress all of them at the same time and reduce clutter.

**Comment by ChiLyMan** [comment]
Just checked this in 1812 and the current sample naming behavior is still as Matt described.

**Comment by ChiLyMan** [comment]
Only one left is the warning about duplicate sample name.

"Cannot edit sample name directly in the sample list (means there are a lot of unnecessary mouse clicks and movement to set up a holder)" (Fixed in 1829)

When adding measurements from a pre-defined ...(e.g. "Matrix Mapping") instead of the method name." (Fixed in 1829, now uses Method name and not measurement type)

When a measurement is created, the default measurement name is a combination of the sample number and the measurement type (e.g. "SampleID123_Matrix_Mapping". ... real chore for 28 samples). (Fixed in 1829 - Now only SampleName + MeasurementType)

**Comment by ChiLyMan** [comment]
Just checked in Build 1854 and still no warning about duplicate sample name, just revert to the default (Sample<HOLENUMNER>).

**Comment by ChiLyMan** [comment]
<FIXED>
Checked in 3.3.1, warning message present
