### ISSUE TITLE
BUG_MINOR_AMICS DESKTOP 3.3.0.1785_Investigator: Copy HW settings between measurement types not working

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#368]
The HW settings from a segmented measurement will not copy across to a mapped measurement.

For instance:
I have some pre-existing measurements in various sample positions (all segmented) that contain HW data. I duplicate the measurement in the first sample position, change it to a map, then duplicate to all other positions. This means I have a bunch of measurements in all of the positions with HW data that relates to position 1 (so far so good) but....

If I then go to the existing segmented measurement in e.g. position 2 (which has correct HW settings), copy the settings across to the mapped measurement (with the HW settings box enabled), the HW settings are not copied. The WD stays the same as before (which is the WD from the original duplicate i.e. position 1).

**Comment by MarkGuo7** [comment]
Normally, each sample hole should have own hardware conditions and not suppose to copy over.

Any suggestions?

**Comment by ChiLyMan** [comment]
Matt are you mainly thinking about being able to transfer the focus on a sample even when you duplicate other settings from another samples.
So, you want to copy the BG Grey levels, Xray AC etc. over to a new sample, but somehow retain the WD on the new sample. Basically, WD (focus) is sample based and not measurement base?

**Comment by Matt-Power** [comment]
This is for when you are copying between measurements. 

In the case I outline, I have set up a run (or a run has completed) so that the HW settings are correct for each position.

However, if I want to add another measurement (e.g. a bright phase search), I set it up for position 1 and then duplicate it to all other sample positions. However, the copied measurements contain the HW settings for position 1 so you have to drive back to all positions and apply the HW settings which is a big waste of time.

Ideally, measurements duplicated from one hole to another should inherit the HW settings of the destination hole (not the HW settings of the source hole).

**Comment by Matt-Power** [comment]
To add: In the copy measurement settings option, there is a "copy HW settings" tick box. However, this does not do anything.

**Comment by MarkGuo7** [comment]
Thanks Matt

Done!

**Comment by Matt-Power** [comment]
Great, thank you!
