### ISSUE TITLE
Investigator: edit sample details from the measurement list

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#369]
Ability to edit sample and measurement names within the holder list is sorely needed, especially for systems that can take larger sample holders.

At present, the workflow is more time consuming than it could be but more importantly, requires a lot of long mouse moves / lots of clicking and so represents a very high RSI risk (I have first hand experience directly related to this and it's not just a minor discomfort...).

Currently, to change the sample and measurement name, the following steps have to be followed:
Bottom left of screen: select sample position
Top right of screen: select and edit sample name
Bottom left of screen: select measurement
Top right of screen: select and edit measurement name

Repeat for all samples and measurements. 

It is also not possible to use the cursor keys to minimise the mouse moves between samples because once the sample name is selected in the top right, that pane retains focus (and vice versa).

For a 28 block holder with one measurement per sample, that's upwards of 84 moves from bottom left to top right of screen - a lot of arm, wrist, head, and neck movement.

If the list could be edited directly, it would remove almost all of the mouse moves , speed up the process, and make it more intuitive. 

Add keyboard access so that cursor keys and a key combo would allow the edit of the sample and measurement names would mean you could do all without a mouse - really helpful when accessing a system remotely (TV with mouse without borders can be a real pain on a dual monitor setup).

**Comment by ChiLyMan** [comment]
Sample naming behavior was still the same in 1812.

**Comment by ChiLyMan** [comment]
Tested on build 1829 and is working as described. Sample name and measurement names can be changed on the table without going to the right-hand tab.
