### ISSUE TITLE
Re-introduce MLA measurement types and methods. Also make improvements to them.

### ISSUE THREAD

**Issue by Sperrylite-MattNg** [Bruker-Amics/bugs_features#37]

**Comment by knapp-amics** [comment]
Can you give us a little more information on exactly what measurement types you are looking for?

**Comment by Sperrylite-MattNg** [comment]
Here are just a few things I have so far:
- Do x-ray mapping in particle and bright phase search measurements and using various (improved) methods to trigger x-ray mapping.
- Various time-saving approaches for Bright phase search measurements such as MLA's SPL_DZ, SPL_Lt_Map etc
- Improving workflow for bright phase search
- Have area scan and point scan options for x-ray collection during measurement

**Comment by knapp-amics** [comment]
I am going to put each measurement mode in as a separate feature. A few questions: 
--> What parameters do you want to trigger x-ray mapping? 
--> Do you have some specifics on the improved workflow for bright phase search? 
--> By area scan and point scan do you mean trigger a esprit area and point measurement, or do you mean to have it map in a matrix?

**Comment by Sperrylite-MattNg** [comment]
@knapp-amics 
For the triggering of x-ray mapping, spectrum based trigger, BSE based trigger and a combined option too (for example you may want to x-ray map siderite or iron hydroxide but not hematite/magnetite).
Workflow for Bright Phase Search, post measurement a file can undergo a channel ROI peak searches (eg. Au peaks or Au and Cu peaks), identified grains can then be bookmarked with an "emoji icon" and the particles containing these grains can be saved as a new file.
Area scanning, the electron beam scans the whole segmented area. This is to 1) identify non-segmented minerals and trigger x-ray mapping; 2) for mineral sands work - to get the chemistry of the whole (excluding any segmented rims) sand grain.

**Comment by knapp-amics** [comment]
Ok. Our plan right now is to map out this x-ray trigger for combined mode and rare phase search mode and include some modes in this release and more in the next release.

-Jonathan

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
