### ISSUE TITLE
Remove Pores / Background for Particle Sorting and Deagglomeration

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#370]
Currently aggregated particles containing a lot of intergranular space are treated as a single particle - the space between them is classed as "pores" (or when measured, "epoxy" or whatever). Therefore, when the sample is sorted, viewed as particles in a grid, or deagglomerated, they are treated as a single, large particle. Similarly, if a sample has cemented in storage (e.g. gypsum or halite has precipitated and cemented particles together), even if the cement phase is included in a background grouping, the particles are still clumped together. Example below is after deagglomeration but as much of it is "pores", it still appears stuck together.

![image](https://user-images.githubusercontent.com/84986921/236890929-04335b56-0166-41a7-97b3-ed172a7d7491.png)

There needs to be some mechanism to exclude any phase during sorting, deagglomeration etc.

I guess this issue / request has been raised in several different ways but it all boils down to what is really needed is a true "background" grouping where any phase contained within the group is ignored i.e. it is essentially deleted so not included in any calculation etc etc. The advantage over simply deleting those segments is that it is much a much simpler workflow, quicker (selecting and deleting pores in a large sample can take over an hour), and more dynamic (assuming it is possible to group / ungroup).

**Comment by jonathan-knapp** [comment]
@Matt-Power we hear you loud and clear. It is our intention to have a big rethink of this early next year. We will have this "workflow" as a major discussion topic at the user group meeting at PDAC in 2024.

**Comment by jonathan-knapp** [comment]
Matt, 
We have a planned solution we will review with you at PDAC. @ChiLyMan this is in AP005 in the 3.5 plan for march.
