### ISSUE TITLE
Investigator: Global Reliability Settings

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#371]
v3.3.0.1701
It looks like the default settings for classification reliability have disappeared from the Options menu. I've looked in Investigator, Tool etc but can't see them anywhere.

**Comment by jonathan-knapp** [comment]
@Matt-Power did this relate to: "Measurement reliability settings – can’t set them properly in the measurement (defaults back to strange values) and no way to change the default values in either Investigator or Process" 
If so we can test in coming weeks.

**Comment by Matt-Power** [comment]
It's separate - for this issue there is no option to change the default / global reliability settings (you can change the other measurement default settings but not the reliability).

**Comment by ChiLyMan** [comment]
Fixed in 1829.

**Comment by Matt-Power** [comment]
Re-opening as I have figured this one out:

The reliability settings for measurements are only shown in Process - they are not available in Investigator.

Given that the instrument PC often doesn't get used for Processing (I never use it), the reliability settings should be accessible from Investigator and Tool (as well as Process).

**Comment by Matt-Power** [comment]
I should add, this is still the behaviour in 1838

**Comment by ChiLyMan** [comment]
Tested in build 1854:
Default reliability factors can be set in Process and Investigator
Reliability factors (low and high) are visible in Investigator.
