### ISSUE TITLE
Investigator: cannot change reliability settings in measurements 

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#372]
v3.3.0.1701
It is not possible to change the classification reliability settings in measurements. The values can be changed but revert back to the defaults (it only reverts when you click on a different sample and then back to the original).

This also means that any methods applied revert back to default (even if the method has specific reliability values). Similarly, copying settings between samples does not work.

Given issue #371, it is now impossible to change any of the reliability settings. If the defaults are messed up, this becomes really problematic.

**Comment by Matt-Power** [comment]
Bit more detail on this one:
If I change the high reliability settings (say, to 95) and then re-select the sample (click on a different one and then back to the original), the normal reliability will have changed to whatever was specified for the high reliability setting (in this example 95) and the high reliability will default back to 90.

**Comment by MarkGuo7** [comment]
@Matt-Power Thanks Matt

I will take a look of this issue today.

**Comment by MarkGuo7** [comment]
@Matt-Power Sorry Matt

Stuck with the UI upgrading these days. Will do it next.

**Comment by Matt-Power** [comment]
No worries. this one isn't hugely important to me as I usually reclassify offline. It may well be an issue for others that need final data direct from the instrument though.

**Comment by ChiLyMan** [comment]
Tested on 1829 and reliability factors will not revert back to defaults, and allows for copying of reliability factor to new samples. Also reliability factors set in method are also copied over when added to a sample.
