### ISSUE TITLE
Investigator: samples are added in rotation order not by hole position

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#373]
v3.3.0.1701
Using the 28 block holder, when populating a new holder file with all samples, the samples are added in rotation order, not by hole number. Therefore, the sample list starts at position 19, and the rest are in a weird order (e.g. 1, 2. 3, 15, 16 etc). With an inexperienced operator, this could easily cause sample mix-ups (sample number being assigned to the wrong hole etc). 

When the "all" samples button is used to fill the holder, by default it should be sorted by hole number.

**Comment by GGloy** [comment]
@Matt-Power with version 3.3.0.1864 if add "all" it should be added in order. If randomly added, click on the "sort" function and from the open dialog, click in hole column to sort by numerical order.

 ![image.png](https://images.zenhubusercontent.com/60af4a22d2c5ea1082755c53/dc091b5d-e918-4d0b-bdda-a62c5aab22d0)
