### ISSUE TITLE
Investigator: sample name is duplicated in the measurement file name

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#375]
v3.3.0.1701 (although it is in all versions)

When a measurement is created, the default measurement name is a combination of the sample number and the measurement type (e.g. "SampleID123_Matrix_Mapping". However, the inclusion of the sample name is unnecessary as the measurement file name already includes the sample ID. If the defaults are used, the measurements are all labelled "SampleID123_SampleID123_Matrix_Mapping" i.e. needless duplication of the sample number and results in super-long file names. This means lots of unnecessary editing of measurement names (can be a real chore for 28 samples).

Measurement names also default back to this format when the mode is changed (e.g. from matrix mapping to particle mapping which can be frustrating.

Please just default to the measurement type for the measurement name and omit the sample name (as the sample name is included in the measurement file name anyway).

**Comment by jonathan-knapp** [comment]
@MarkGuo7 please see my previous comments about adding functionality around the default specimen name and default measurement name templates for the specimen template and globally. We want to make an update for this.
