### ISSUE TITLE
BUG - MINOR (but annoying) - AMICS Investigator:  sample holes are not represented correctly.

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#377]
v 3.3.0.1701 and before

Rectangular hole shapes are not represented correctly in AMICS when a rotation is used. See example below:

![Thin section holder](https://github.com/Bruker-Amics/bugs_features/assets/84986921/d65b7110-eb71-49cf-9a80-840fd0eb8f76)

Holes 5 and 6 should appear on the holder in landscape orientation, not in portrait. It is correct on the detail view and the measurements work OK, it is just the block holder representation in Investigator that is wrong.

**Comment by MarkGuo7** [comment]
Yes, the rectangle sample holes with rotations may have problem to show its layout.

Let me know if it is important enough. Otherwise, I will leave it to next release.

**Comment by MarkGuo7** [comment]
Sorry Matt, for the moment, AMICS only support round samples if the stage has rotation.
In theory, we can have 90, 180, 270 degrees with rectangle samples, but need to design it properly.
