### ISSUE TITLE
BUG - MINOR (but annoying) - AMICS Investigator: hole orientations are wrong

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#378]
v 3.3.0.1701 SU5000
The little arrows on the sample holder view showing the way up (top) of the sample are incorrect - they are all rotated 90° from what they should be.

![Thin section holder](https://github.com/Bruker-Amics/bugs_features/assets/84986921/c7cd85ac-26d6-4429-88dc-388ab0db6d1a)

In this image the arrows for 1 & 2 point to the left but should point downwards, the arrows for 3 & 4 point right but should be upwards, 5 should be to the left, and 6 should be to the right (the orientation for 5 and 6 is incorrect on the image though - see issue #377).

Circular holes are the same - any markings on the block orientated in the same direction to the little markers will actually be measured 90° rotated.

**Comment by jonathan-knapp** [comment]
@ChiLyMan is this true on all holders?

**Comment by ChiLyMan** [comment]
I need to check I’ve not seen huge issues with holder I’ve used. Wonder if it’s the holder text file.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Matt-Power** [comment]
@ChiLyMan it's not the txt file (that is as expected / correct and if you alter it to match the image in Investigator, it doesn't work) but it does seem to be due to Investigator not displaying the rotation correctly.

**Comment by Matt-Power** [comment]
Just checked on a different, circular holder too and the arrows are also displaying incorrectly on that.

**Comment by ChiLyMan** [comment]
@Matt-Power OK let me run this down.

**Comment by Matt-Power** [comment]
Thanks. I was looking at the circular holder and it seems to be that Investigator is not factoring in the rotation of the holder at all so the arrows are rotated but assumes that the holder is not. So for a 9 position holder, the arrow migrates around the hole 40° for each sample. It should be the other way around - the holder rotates but the arrows always point north.

**Comment by Matt-Power** [comment]
In case it helps visualise - the little arrows on this should all be facing upwards not rotating around the blocks (the holder moves, not the blocks...)
![Circular holder](https://github.com/Bruker-Amics/bugs_features/assets/84986921/8fcd15dd-af09-49ab-8446-c3d9da84c270)

**Comment by Matt-Power** [comment]
V3.3.0.1983
This is mostly fixed in 1983, thanks. However, the little arrows should point to the top of the sample (and point towards the top of the resulting image) but they actually point to the right. Can you rotate them 90 degrees anticlockwise please?
Thanks!
