### ISSUE TITLE
Request .mdb or equivalent exported datasource from AMICS 3.3

### ISSUE THREAD

**Issue by scarlett-01110011** [Bruker-Amics/bugs_features#379]
The option to export to .mdb (Microsoft Access) was previously available in AMICS 3.2. Could we please have this .mdb export option re-enabled in AMICS 3.3?
Alternatively, if the same processed data and file structure were available to export to a newer format (such as SQL), this would be an equivalent solution.

Happy to provide an example of the file structure needed.

![image](https://github.com/Bruker-Amics/bugs_features/assets/117055041/47e1d6a5-ab7d-4d18-b86e-89d52524e13a)

![image](https://github.com/Bruker-Amics/bugs_features/assets/117055041/4e9d10d5-bc79-4f74-9fc5-e8da147ba831)

**Comment by MarkGuo7** [comment]
@scarlett-01110011 Hi Scarlett

We already discussed this request and I will bring the exporting mdb back first. Then we can discuss other options later.
Will let you know when it is ready.

Mark

**Comment by scarlett-01110011** [comment]
Thank you :)

**Comment by jonathan-knapp** [comment]
Scarlett,

Could it be ok to get a copy/list of the required tables you need?

Chi

**Comment by GGloy** [comment]
Can be closed

**Comment by MarkGuo7** [comment]
Thanks Gerda
