### ISSUE TITLE
Option to stop files opening on export?

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#381]
Exported images, batch results and several other processes automatically open files or folder windows but this is quite distracting as they invariably open on top of all other applications so extra clicks are required to move or close them. In almost all cases, I don't need the images (or a folder or whatever) to open. An option to prevent automatic opening of these files would be very welcome.

**Comment by jonathan-knapp** [comment]
@MarkGuo7 I don't think files should open automatically on export at all. @ChiLyMan ?

**Comment by ChiLyMan** [comment]
Agreed, it adds an extra mouse click to close it. And in the case of images, if user does not have correct image viewer software another mouse click to close the error message.

**Comment by jonathan-knapp** [comment]
Yea, this is a very big issue and very annoying.

**Comment by MarkGuo7** [comment]
It will be off from now on.

**Comment by Matt-Power** [comment]
v3.3.0.1961
This is still happening when starting a batch. In this case, a File Explorer window automatically opens (by the end of the day I can have 20 of these things hiding on my desktop). Realise that some users might like or need this so an option to disable / enable might be best (i.e. don't disable completely).

Exported images don't automatically open though (thank you!).

**Comment by ChiLyMan** [comment]
AMICS now lives in the background during batch processing and no windows are open in version 1996
