### ISSUE TITLE
BUG - MINOR - AMICS 3.3.0.1701 - Investigator: Random extra measurements 

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#383]
3.3.0.1701
I've seen this a few times so probably also exists in versions prior to 3.3.0.1701
In certain circumstances, Investigator will randomly re-measure samples - the data are written to the existing measurement but the field number sequentially increasing e.g. if 80 fields measured initially, the second "ghost" measurement will be 81 onwards. 
@MarkGuo7  I will send you the logs
 
In this specific example, I initially ran a BSE only scan on 6 samples.
After this I duplicated the BSE scan, changed the type to particle, and changed the measurement settings (e.g. resolution etc) but I kept the same overall area (153 fields).
The samples started off fine but after the measurement in position 3 was complete, it went back to number 2 and started analysing again (with a slightly larger area but broadly with the same parameters as before).
When I checked on the instrument and found out it was re-analysing the sample, I stopped the current measurement and allowed it to go to the next but instead of going to sample position 4, it went back to 3 and started re-analysing that one too.
Stopped that measurement and skipped to the next and all completed as expected.

**Comment by MarkGuo7** [comment]
@Matt-Power Thanks Matt for reporting it and the log files
I will try to repeat your steps to see if happens.

**Comment by ChiLyMan** [comment]
@Matt-Power @MarkGuo7 I will close this one and we can open again if we see this beahviour again
