### ISSUE TITLE
V3.3.0.1694 - Matrix mapping discards unknown points

### ISSUE THREAD

**Issue by jkabel** [Bruker-Amics/bugs_features#384]
The matrix mapping mode in V3.3.0.1694 of Investigator is discarding all point data that cannot be identified at the time of collection with the database on the collection system:
![1694-MatrixDataDetail](https://github.com/Bruker-Amics/bugs_features/assets/12158231/42ce9fed-3590-4aa7-b4ae-63efb703fdca)

The modal totals of this map show 0 unknown segments.

**Comment by MarkGuo7** [comment]
@jkabel Hi Jacob, could you try the version 1701?
We noticed this issue and it should be solved with 1701.

Let me know if you couldn't get it :)

**Comment by Matt-Power** [comment]
Just to confirm, this is definitely resolved with 1701.

**Comment by MarkGuo7** [comment]
Thanks Matt

**Comment by jkabel** [comment]
That's great! Could someone hook me up with a copy of 1701, assuming there's no other showstoppers?

**Comment by MarkGuo7** [comment]
Hi @jkabel 

Could you try to download from here: https://github.com/Bruker-Amics/bugs_features/releases/tag/V3.3Beta
