### ISSUE TITLE
BUG - MAJOR - AMICS 3.3.0.1701 - INVESTIGATOR Overactive binary image detection

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#387]
v3.3.0.1701 on SU3900, Esprit 2.5

Just trying to run some low res, whole block BSE only measurements on samples containing small chunks of rock. The measurement fails on the first field (which is resin). The frame is acquired but everything freezes up immediately afterwards. Looking at the logs, it appears that AMICS thinks it is a binary image and is trying to reset Esprit but nothing happens.

Looks like any sample that contains large areas of resin is going to cause significant problems.

**Comment by MarkGuo7** [comment]
@Matt-Power Hi Matt

Could you try this option to see how it goes?

![image](https://github.com/Bruker-Amics/bugs_features/assets/84481724/43ed42b9-2806-487f-a8f8-cc6ea964fd11)

**Comment by Matt-Power** [comment]
OK, thanks, will do.

Wonder if it is worth making that a specific option? e.g. add to the measurement-specific options (same as secondary channel and noise reduction) and default to off for BSE-only and the option to disable for other samples such as those that have a lot of resin  / blank fields around them that might trigger the freeze.

**Comment by MarkGuo7** [comment]
It's a long story :)

At some stage, the system is not that stable. Sometime it will start to capture binary images, look like the contrast dramatically changed.
This option is to avoid the system keep running with this useless collection.

**Comment by Matt-Power** [comment]
No worries, I understand - we do get the binary image issue occasionally too. I guess my request is: can we have a measurement-specific option to disable it? 
The global setting is fine but I know that when I turn off for a specific run that I will forget to switch it back on or that with mixed samples in a holder, the binary problem will re-appear. Not a big one though.
