### ISSUE TITLE
BUG - MAJOR - AMICS 3.3.0.1829 - PROCESS - Import database message error

### ISSUE THREAD

**Issue by GGloy** [Bruker-Amics/bugs_features#390]
When importing a database the warning message does not display correctly![image.png](https://images.zenhubusercontent.com/60af4a22d2c5ea1082755c53/1e9cca57-b885-452b-b10a-55ca46ec8353)

**Comment by MarkGuo7** [comment]
Hi Gerda, is it still so?

**Comment by GGloy** [comment]
Yes - vs1858
