### ISSUE TITLE
BUG - MAJOR - AMICS 3.3.0.1829 - PROCESS - Importing database issues!!

### ISSUE THREAD

**Issue by GGloy** [Bruker-Amics/bugs_features#391]
When attempting to importing a database (vs1812) the following error message pop up. 
![image.png](https://images.zenhubusercontent.com/60af4a22d2c5ea1082755c53/38c9f4e1-9ca0-4a3d-8eaf-0d6bb2cbceb7)

In this instance after the failed import no database was imported
![image.png](https://images.zenhubusercontent.com/60af4a22d2c5ea1082755c53/659ade5c-f127-41e5-99de-a4827527b700)

When I opened the database I tried to import back in vs2 standard manager - some of the databases have lost all its entries!

![image.png](https://images.zenhubusercontent.com/60af4a22d2c5ea1082755c53/84c1fc0c-b5de-47e3-886d-e6db64bb1016)

**Comment by jonathan-knapp** [comment]
Gerda,

Not sure if this is the same cause, but generally when I get this error it has something to do with permission settings in the “C:\ProgramData\AMICS\SystemData” folder.



-Bruker Confidential-
From: GGloy ***@***.***>
Sent: Thursday, June 15, 2023 7:21 PM
To: Bruker-Amics/bugs_features ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Bruker-Amics/bugs_features] Importing database issues!! (Issue #391)

**EXTERNAL EMAIL**

When attempting to importing a database (vs1812) the following error message pop up.
[https://camo.githubusercontent.com/fe173ae3dd0a95456497098cf48588722c2bfffc13932f85272775d04edfb86a/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630616634613232643263356561313038323735356335332f33386339663465312d396361302d346133642d386561662d306436626232636263656237]<https://camo.githubusercontent.com/fe173ae3dd0a95456497098cf48588722c2bfffc13932f85272775d04edfb86a/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630616634613232643263356561313038323735356335332f33386339663465312d396361302d346133642d386561662d306436626232636263656237>

In this instance after the failed import no database was imported
[https://camo.githubusercontent.com/b0262899041339e1bc9e7806a4a4cad3996c9e8342800f7d1a689a4fc5696030/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630616634613232643263356561313038323735356335332f36353961646535632d663132372d343165352d393964652d613438323735323762373030]<https://camo.githubusercontent.com/b0262899041339e1bc9e7806a4a4cad3996c9e8342800f7d1a689a4fc5696030/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630616634613232643263356561313038323735356335332f36353961646535632d663132372d343165352d393964652d613438323735323762373030>

When I opened the database I tried to import back in vs2 standard manager - some of the databases have lost all its entries!

[https://camo.githubusercontent.com/4699570476c707bdd95c32efa603c13e4acd4ccd3e00a9609927ace6b77468d4/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630616634613232643263356561313038323735356335332f38346331666330632d623564652d343765332d383836642d653664623634626231303136]<https://camo.githubusercontent.com/4699570476c707bdd95c32efa603c13e4acd4ccd3e00a9609927ace6b77468d4/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630616634613232643263356561313038323735356335332f38346331666330632d623564652d343765332d383836642d653664623634626231303136>

**Comment by GGloy** [comment]
It’s possible …what should I look for?

**Comment by jonathan-knapp** [comment]
If you go into that directory and try to change the name of the OreTypes.db or UserSTD.db and see if you encounter a windows access error. Maybe asking for a password or something.

Then you need to change permission of the folder/file to allow you access.

@Guo, Junfeng ***@***.***> Does the new version of AMICS still use the .DB files in the AMICS folder in SystemData? Or have you moved it to a “common” folder?

Chi



-Bruker Confidential-

**Comment by GGloy** [comment]
I can change the names.

**Comment by jonathan-knapp** [comment]
Ok then not a permission issue, unless AMICS is not using the files from that folder anymore.

Get Outlook for iOS<https://aka.ms/o0ukef>


-Bruker Confidential-

________________________________

**Comment by GGloy** [comment]
@MarkGuo7 This can be closed, thanks!
