### ISSUE TITLE
Export spx file - wrong dialog!

### ISSUE THREAD

**Issue by GGloy** [Bruker-Amics/bugs_features#392]
When I click on Export spx file from the Mineral Standards tab

the next display is this!![image.png](https://images.zenhubusercontent.com/60af4a22d2c5ea1082755c53/b159dede-1aa6-44b5-8b92-5fd0b7300960)
![image.png](https://images.zenhubusercontent.com/60af4a22d2c5ea1082755c53/4ee8b147-2189-4669-8892-eb17e617a06c)

**Comment by MarkGuo7** [comment]
@GGloy Hi Gerda

Currently, it will let you to choose which oretype to export. 
Which means, it will export all the spectra to spx files.

**Comment by GGloy** [comment]
Got it – I guess I got confused because the normal Export for a single X-ray from the Main Menu Export icon is not working……

**Comment by MarkGuo7** [comment]
You are right Gerda. Let's make it clear next week.

**Comment by ChiLyMan** [comment]
Additional to Gerda's comment:-
When you select "Export to SPX Files"
![image.png](https://images.zenhubusercontent.com/62f264fb4831bda01fb7d454/aa917bf7-43c0-4883-925d-783af88b6bfc)

And the following pop-up dialog appears:-
![image.png](https://images.zenhubusercontent.com/62f264fb4831bda01fb7d454/fbcd7178-2548-43b5-834e-f541c70e61d3)

If you choose the first option (From Current Result File) it will export the OreType Database and not the SPX files
If you choose the second option (from Current Selected Common OreType), then it will export all the SPX files to the selected folder.

**Comment by GGloy** [comment]
@MarkGuo7 in version 1838 it is still exporting the database as Chi mentioned in his comment.

**Comment by GGloy** [comment]
Still the same in vs 1846.
