### ISSUE TITLE
M4 convert mapping to particle does not work

### ISSUE THREAD

**Issue by GGloy** [Bruker-Amics/bugs_features#394]
According to my testing the function to convert mapping results to particle mode from M4 data is again not working - if I select particulate and the phase to set to background then particulate, after the particulation step if I click back on the  images tab the background is removed, but no particle layer option.
![image.png](https://images.zenhubusercontent.com/60af4a22d2c5ea1082755c53/1dad45a5-2b1f-4a8c-b4e2-905a94c82d9e)

**Comment by jonathan-knapp** [comment]
Gerda,

Did you Save Particulation Result? Once you do this it will change the label from Frame to Particle.
***@***.*** ***@***.***



-Bruker Confidential-
From: GGloy ***@***.***>
Sent: Friday, June 16, 2023 1:07 AM
To: Bruker-Amics/bugs_features ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Bruker-Amics/bugs_features] M4 convert mapping to particle does not work (Issue #394)

**EXTERNAL EMAIL**

According to my testing the function to convert mapping results to particle mode from M4 data is again not working - if I select particulate and the phase to set to background then particulate, after the particulation step if I click back on the images tab the background is removed, but no particle layer option.
[https://camo.githubusercontent.com/8dba9b7e88f9ebf03270180e7c833a69eef12549e65f65dcf4e2fe8f4d1686a2/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630616634613232643263356561313038323735356335332f31646164343561352d326231662d346138632d623465322d393035613934633832643965]<https://camo.githubusercontent.com/8dba9b7e88f9ebf03270180e7c833a69eef12549e65f65dcf4e2fe8f4d1686a2/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630616634613232643263356561313038323735356335332f31646164343561352d326231662d346138632d623465322d393035613934633832643965>

**Comment by ChiLyMan** [comment]
Gerda, Can you let us know if saving the particulisation fixes this issue?

**Comment by GGloy** [comment]
Yes, it does. I was not aware of the extra step - the save is not from the normal save button.
