### ISSUE TITLE
Speedup M4 bcf converting

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#396]
Currently, as Gerda tested. 
Convert 9 fields bcf files measured from UQ machine will take about 13.5 m.
![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/562dc62c-ff89-4b6e-9eb1-ed9e8ad9aae6)

The most cost is saving xray info into database.

Without saving xray info, only take about 0.5 m.
![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/259de6ba-b50b-494b-9a5d-20f36ea4fafb)

**Comment by GGloy** [comment]
Tested on small SEM-bcf data - it seems fine now. @ChiLyMan if you can confirm and close

**Comment by jonathan-knapp** [comment]
Seems quicker to me, compared to previous versions.



-Bruker Confidential-
