### ISSUE TITLE
BUG - MAJOR - AMICS 3.3.0.1829 - No Floating Properties Window?

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#397]
v3.3.0.1838
@MarkGuo7 I can't find the setting to make the Properties box float (rather than pinned to the right) - has this functionality been removed? If so, can I have it back please ? It is super-useful. 

If it is still there, can you advise me where the option is, I can't find.

**Comment by GGloy** [comment]
@knapp-amics this ticket can be closed.
