### ISSUE TITLE
BUG-MAJOR_AMICS_PROCESS:Auto Field Adjustment (image stitching) Crashes

### ISSUE THREAD

**Issue by scarlett-01110011** [Bruker-Amics/bugs_features#400]
When trying to run the Auto Field Adjustment (image stitching), it causes Process to crash.

Version 3.3.0.1838

**Comment by ChiLyMan** [comment]
Thanks Scarlett, can you do me a favor and go to the Field Adj. and try "Clear All Adjustment" and see if it also causes the crash.
![image.png](https://images.zenhubusercontent.com/62f264fb4831bda01fb7d454/b4274cce-04e2-4e20-b8ca-79fdc00b42c8)

**Comment by scarlett-01110011** [comment]
Yeah clearing all adjustments also causes it to crash.

**Comment by GGloy** [comment]
Stitching seems fine now (vs3.3.0.1858)
