### ISSUE TITLE
Process Bug - Particle Properties Table: Incorrect Chemistry with Grouping

### ISSUE THREAD

**Issue by scarlett-01110011** [Bruker-Amics/bugs_features#402]
The element % in the particle properties table is very useful, thanks for adding this. 

There is a bug in this table when a mineral group list is applied, the chemistry (element %) is different compared to the chemistry with the primary mineral list, for the same particle.

Version 3.3.0.1811

**Comment by MarkGuo7** [comment]
Thanks Scarlett

I will take a look.

**Comment by GGloy** [comment]
@MarkGuo7 - There is an issue when grouping is applied - that is if I group two minerals to a group with a new name for example I group K-feldspar and albite together in a group called Feldspar - then the chemistry for the feldspar minerals are all 0%. Let me know if I need to show you

**Comment by ChiLyMan** [comment]
@MarkGuo7 I think we are seeing a rounding issue here. The major elements are generally inline between the primary and grouping list, but it seems any element <0.1 in the primary list is being rounded out.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0orQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f71d5ffc5fc1a78654a02b9aaa62a44a190a4148/image.png)

**Comment by ChiLyMan** [comment]
Checked in version 3.3.1 and the rounding error seems to be fixed.

**Comment by scarlett-01110011** [comment]
This is fixed in version 3.4.0 (not fixed in 3.3.1)
