### ISSUE TITLE
BUG_MAJOR_AMICS PROCESS 3.3.0.1904_Can't highlight multiple minerals when grouping applied

### ISSUE THREAD

**Issue by GGloy** [Bruker-Amics/bugs_features#403]
Selecting multiple minerals work for the Primary mineral list, but not for subgrouped minerals list. Only the last selection is highlighted when trying to select multiple minerals.

**Comment by jonathan-knapp** [comment]
This is still happening. 
![image.png](https://images.zenhubusercontent.com/60a274843870252752494569/a2907fe9-1fbe-45fb-9c83-e232ff9865e3)
With only one selected... 
![image.png](https://images.zenhubusercontent.com/60a274843870252752494569/21ddaf70-b7a8-4748-bbbc-dbd7a553bd70)
Selecting a second one and the first phase is no longer selected. 
![image.png](https://images.zenhubusercontent.com/60a274843870252752494569/84502655-166b-4d47-aa86-77cb66ee3c9c)
And de-selecting that phase causes it to default back to everything showing... 
![image.png](https://images.zenhubusercontent.com/60a274843870252752494569/5cf02950-3af3-4627-bb5d-f41164090658)
