### ISSUE TITLE
BUG_MISSION CRITICAL_AMICS PROCESS 3.3.0.1904_Ungrouping of Minerals Doesn't Work

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#404]
v3.3.0.1864

After reclassification, if I want to remove a group in the group editor using either the < or <<< buttons, nothing happens. Similarly, if I want to pull a mineral out of a group using the < button, nothing happens. 

Note that it seems that the buttons do work for groups and minerals that have been moved during the current phase of classification but once the results are reclassified, all of the pre-existing groups and minerals become locked and cannot be moved around.

**Comment by ChiLyMan** [comment]
Tested on 1911 and ungrouping is working now, even after reclassification with same dictionary, common dictionary or another dicitonary.
