### ISSUE TITLE
BUG_MAJOR_AMICS PROCESS 3.3.0.1904_Groupings Change When Copied to Ore Type

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#405]
v 3.3.0.1864
When the current mineral groupings are edited and then copied to the ore type, a whole bunch of entries become ungrouped.

Steps involved:
Loaded up a measurement and reclassified with an existing ore type.
Created some new mineral standards.
Reclassified measurement to apply the new standards.
Edited the mineral groupings by grouping the new standards with existing mineral groups e.g. new muscovite standard grouped with existing muscovite group.
Imported grouping back to the ore type.
Scroll to end of Groupings in the Classification tab and there are a bunch of mineral standards that have become ungrouped.

**Comment by jonathan-knapp** [comment]
Still happening in 1904
