### ISSUE TITLE
BUG_ANNOYING_AMICS PROCESS 3.3.0.1904_Column Width Not Persistent

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#406]
v3.3.0.1864

If I change the width of the mineral name column in any of the tabs on the left, they reset to default when I switch to a different tab (e.g. if I change  the width in "Standards", click on "Groupings" and then reselect "Standards", the columns have reverted to default.

Similarly, there is no width adjustment for the colour swatch column in the Current Results Standards tab. (The swatch column width is too narrow to clearly see similar colours clearly.)

Both minor issues but annoying.

**Comment by jonathan-knapp** [comment]
https://images.zenhubusercontent.com/368966218/f94996b9-f4ee-4abe-ba75-f574ac20e4cd/2023_07_31_14_28_45.mp4
