### ISSUE TITLE
Multiple Batch Processes

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#41]
Multiple batch processes (different projects / measurements) running causes instability. When one batch process is cancelled, it causes both to stop (and usually a crash).

Ideally, allow multiple batches to run at a time or, if not possible, prevent a second batch being instigated by mistake (with a warning message).

Update - have run two batches side by side successfully. It seems to be cancelling one batch that is problematic.
Can we have a proper "cancel" button or does hitting the X do the same? (I don't always get a message box when I hit the X)

**Comment by van-amics** [comment]
Hitting the close (x) button will eventually cancel the batch process. However, it will take a bit of time for the process to "orderly" cancel its current task.

**Comment by Matt-Power** [comment]
OK, thanks but the main point was that when two batches are running, cancelling one of the batch can cause the second to crash.

**Comment by jonathan-knapp** [comment]
Need to test
