### ISSUE TITLE
BUG: Progress file / log for batch calculations not written until end.

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#411]
v3.3.0.1903 (and versions before)

When running a batch calculation, the datafile and/or logs are not written out until the process is complete. If a crash occurs at any point during the batch (unfortunately common with block measurements), the only way to tell which sample is causing the issue is to watch the progress table - for big projects, only fractionally more interesting than watching paint dry and takes about the same time ;-)

Ideally the datasheet should be written out after the first sample in the batch and appended after each subsequent sample so that even if there is a crash, some data are preserved and it is also possible to tell which sample is causing the crash.

**Comment by AlexeiDolgolyov** [comment]
Now result data files are exported after each sample calculations, so even in case of crash everything calculated before crash will be available.
