### ISSUE TITLE
MAJOR_BUG_Excessive Memory Use / Crashing Switching to Calculation Tables

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#412]
V3.3.0.1903 and before

Certain measurements / types cause excessive memory use when the calculation tables are viewed making them virtually impossible to work with.

The measurement will load into the Sample Image view fine but when the calculation table tab is selected, Process progressively uses up all of the available physical memory and will then usually crash. This usually takes about 5 minutes to do this - it seems to be in a death loop but will occasionally show the calculation results.

The measurements are not especially large and I have 32Gb installed (with plenty of spare SSD / swap file space).

@MarkGuo7 I'll upload an example of one of the problematic measurements.

Snapshot of the resource monitor:
![Memory Process](https://github.com/Bruker-Amics/bugs_features/assets/84986921/c70bd4e3-c11b-4114-91f5-28702eb5654e)

**Comment by Matt-Power** [comment]
Bit more investigating:
Seems to happens when blocks are measured as granular samples and where there are a lot of segments.
Converting and reclassifying allows data to be extracted.

In this case, the wrong sample type was selected but there are instances when I need some of the data fields that I can only get granular sample so would be good to figure out why Process is trying to use so much memory (surely using 32Gb must indicate a memory leak or unconventional memory use?)

**Comment by ChiLyMan** [comment]
@Matt-Power Could you send through the example data set so we can have a look please.

**Comment by Matt-Power** [comment]
Just sent a link to an example measurement. Can't remember if I have converted this one to a block though (if I have, please revert back to particle to get the behaviour described).

**Comment by MarkGuo7** [comment]
Thanks Matt for the example dataset, I will take a look

**Comment by MarkGuo7** [comment]
Hi Matt
Gerda and I both tried your result today. Yes, it uses bit memory, but sounds like not much like you saw.
Maybe need bit more steps to repeat this issue.
With thanks

**Comment by MarkGuo7** [comment]
Hi Matt

Could you check this option on your system?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbHN5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6e70c89a670552b7354ceb419c02e08803024159/image.png)

**Comment by Matt-Power** [comment]
@MarkGuo7 Still doing it unfortunately.

I think that the trick to re-creating the issue is to use one of the mineral groupings (there are two in there - either will cause the issue) and then select the calculations table. It will then eat all your available memory and more often than not, eventually give up and crash.

I tried on the same measurement that I sent you the link for so hopefully you should be able to recreate.

Failing that, I have a load of ore types loaded on my system - there's no chance it's reading through all of those at any point is it? (I can't see why but odd that you can't recreate easily.)

**Comment by MarkGuo7** [comment]
Sorry Matt, I didn't make it clear.
Could you change this value to the maximum value? Or change it to 1 (means maximum)
I put some comments on its description.

From your grouping, over 50% are grouping as one mineral, so the whole result will because one grain.

**Comment by Matt-Power** [comment]
@MarkGuo7 I can't see the Zenhub image that you sent so don't know which option to change. Can you embed the image in Github please?

**Comment by MarkGuo7** [comment]
Hi Matt, could you go to the option dialog of Processing, find the "Particle Size Limit" under "Calculation Settings".
Change this value to see if it helps.

**Comment by ChiLyMan** [comment]
@Matt-Power Where you able to test changing the Particle Size Limit to see if this is still occuring?

**Comment by ChiLyMan** [comment]
Do not see this issue in current 3.3.1 release or TMQ branch.
