### ISSUE TITLE
Issues with converted mapping samples vs 1940

### ISSUE THREAD

**Issue by GGloy** [Bruker-Amics/bugs_features#416]
The new changes to measurements that are converted from mapping to particle seem to have issues.

This is what my result looked like after classification.
![image.png](https://images.zenhubusercontent.com/60af4a22d2c5ea1082755c53/d6ba307b-b2f0-40f5-9ebf-492db3bcbec8)

**Comment by ChiLyMan** [comment]
Gerda, Can you send me the data set. I just tested in 1959 and it seems to work fine.

**Comment by GGloy** [comment]
It seems fine now, I will close the ticket
