### ISSUE TITLE
Process v1701 vs 1934 Size Data Does Not Match

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#418]
The mineral size distribution data in the calculation tables for the same sample is very different in 1934 vs 1701.

Interestingly, if I run a batch to get the data in 1934, the numbers in the resultant batch datasheet do match the data in 1701 i.e. the difference Gerda was seeing (#408) is likely that the calculated data tables are incorrect but the batch data are correct.

**Comment by GGloy** [comment]
@Matt-Power thanks for picking this up, Mark and I spent some time today to identify the problem, and Mark is looking into it ASAP.
