### ISSUE TITLE
Data Only Displayed to 2 Decimal Places

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#419]
v3.3.0.1934
All calculated datasheets only display numbers to 2 d.p.
This causes a lot of rounding errors when copied out into Excel etc.

The option to change is no longer present (also not present in 1701 but it is there in 3.2.1.261 - under data view)
Note also that the colour data table option has also gone.

3.3.0.1701:
![image](https://github.com/Bruker-Amics/bugs_features/assets/84986921/a77573da-747f-4fb9-ad26-789a15a10783)

3.2.1.261:
![image](https://github.com/Bruker-Amics/bugs_features/assets/84986921/057b692d-3795-4a04-988c-9164cd8700c9)

**Comment by GGloy** [comment]
@Matt-Power  - These options are now available under Others

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjBQIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8cc597e263d6b7b05f812dc623509ea14d8caa77/image.png)
