### ISSUE TITLE
Include Cleanup Steps in Batch Process

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#42]
Currently, the cleanup steps in the current measurement are used when a batch reclassification process is run. When a batch is run, the cleanup steps are not inherited from the batch and so do not appear in the measurement so if the measurement is reclassified, the data change.

Add a Cleanup tab to the Common Standards window so these can be managed better and applied more consistently. (In a batch of 20+ samples, it is very easy to lose track of which measurement contains the cleanup steps - in 100+ samples, it is impossible to manage.) 

Add box to batch processes dialogue window to allow cleanup steps to be used or not. If not, default to those that exist in the individual measurements.

**Comment by ChiLyMan** [comment]
Touch-up steps are still not being applied when batch processing, reclassification with "another sample" OreType.
