### ISSUE TITLE
BUG - Batches Data and Image Extraction Takes Ages

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#421]
v3.3.0.1961
Batch export of calculated data takes way longer in ver 1961. It seems that each measurement is loaded individually, the data calculated, and then the data is exported. Previously, the data for each sample would extract in about 10s, now it is in the order of minutes, especially for larger and mapped samples.  Is there not a more efficient way to do this?

**Comment by MarkGuo7** [comment]
Sorry about that, Matt

May I know which version you compared with?
We will take a look.

**Comment by Matt-Power** [comment]
@MarkGuo7 Compared with 1701 and before. In that version, the batch is done somewhat in the background (the sample from which you start the batch remains and you can actually interact with the measurement while the batch is going). In the latest version, the sample displayed in the instance of AMICS from which the batch is started changes as it goes through the batch.

I have a lot of ore types on my system so loading up samples takes a long time at the best of times.

Hope this helps.

**Comment by MarkGuo7** [comment]
You are right, Matt
Previous versions, the batching is using another set of code. That's part of the reason, sometimes, the batching results are slightly different from you manually opened.
From my understanding, both should do the same way, open the results and generate the calculation data.
We didn't notice the slowness on our testing yet. Will let you know if we found something.

**Comment by Matt-Power** [comment]
OK, thanks. 

I suspect that it is related to the number of ore types loaded then - I have to keep a bunch semi-permanently so it takes a long time to load a sample in the older versions of Process. Could that be a factor here?

**Comment by MarkGuo7** [comment]
Hi Matt, we still couldn't repeat this issue.
Could you do the same batch with both versions and send me their log files? Hopefully I can take a look where cause so much time.
If still not, maybe need you to share data like before. 

With thanks

**Comment by Matt-Power** [comment]
Edited title as it applies to both data and image extraction.
@MarkGuo7 I'll email you the logs showing the difference between 1703 and 1983.

For extracting a BSE image, the time difference is ~11 secs for 1703 but ~34 secs for 1983.

**Comment by ChiLyMan** [comment]
Check this against 1701 versus 1996 on 16 mixed sample types (Particle and Matrix), all with the same Mineral Library for BSE and Mineral Map export, 1701 took 2:07 and 1996 took 2:32. So 1996 is marginally slower than 1701, but it does seem 1996 is doing more to the data than 1701.

@Matt-Power With the new file format on the horizon, can we park this issue for now, as the new file format will make this irrelevant as you would not need to "export" data from AMICS anymore.

There is a larger difference for export of the calculation as 1701 does not seem to be fully opening the data file, while 1996 is actually opening each MRE file to extract the data. But the advantage for 1993 is the ability to extract modal and assay at the same time.
