### ISSUE TITLE
BUG-M4 Tornado Plus-AMICS 3.3.0.1903_Overview_Image: Overview images do not line up properly

### ISSUE THREAD

**Issue by TDJMurphy** [Bruker-Amics/bugs_features#422]

**Comment by jonathan-knapp** [comment]
This may be a longer-term issue. We may have to automate the camera directly.

**Comment by ChiLyMan** [comment]
We should get Andrew to check when he gets back. I was working with him on the M4 Plus in Berlin, and the overview images seem to line up. The problem was the detectors appear on all the images.

**Comment by TDJMurphy** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFUvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c8e803ccc0273a5551691322689ccea43c980cdb/Image%20overview%203-3-0-19.PNG)

**Comment by ChiLyMan** [comment]
Tested on version 3.3.1 and M4 overview alignment looks good. Not perfect, but nothing that impacts the system operations.
AMICS does need to manually read in HW data when moving between specimen/measurement, but otherwise its working.
