### ISSUE TITLE
Bug-M4 Tornado Plus - AMICS 3.3.0.1903_Measurment_Timeout: Runs longer then 6 hours 55min time out. Appears to be a coms issue with recent M4 Software, also occurs in AMICS 3.2. Doesnt occur in M4 software acquried maps up to 13 hours no issue.

### ISSUE THREAD

**Issue by TDJMurphy** [Bruker-Amics/bugs_features#423]

**Comment by jonathan-knapp** [comment]
Can you please get the logs. It will be big for the long run. We need both M4 and AMICS.

**Comment by TDJMurphy** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGcvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c6995e832482a96b72d1ddc319d45deb40646bd7/Failed.PNG)

**Comment by TDJMurphy** [comment]
[Uploading... Investigator32_2023_08_11_09_30_17_Debug.txt]

**Comment by TDJMurphy** [comment]
I have sent a copy of the log files and the M4 Log files to Mark. Is there a way you want them added here as file options are limited?

**Comment by TDJMurphy** [comment]
[Investigator32_2023_08_11_09_30_17_Debug.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaDQvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7e8a33280971694693e4f4ae50bf0adaaf6f89ef/Investigator32_2023_08_11_09_30_17_Debug.txt)

**Comment by MarkGuo7** [comment]
Esprit team said they already fixed this issue. Should be good in the next build.

**Comment by TDJMurphy** [comment]
We had this happen in version .1983 of investigator. Do you mean a software update from Bruker for the M4?

**Comment by MarkGuo7** [comment]
Yes, I will ask for an Esprit update.

**Comment by TDJMurphy** [comment]
Problem has been resolved with new version of Esprit
