### ISSUE TITLE
Bug-M4 Tornado Plus - AMICS 3.3.0.1903_Added_Measurements: Adding a new measurment in investigator after a scan has completed crashes the software

### ISSUE THREAD

**Issue by TDJMurphy** [Bruker-Amics/bugs_features#425]

**Comment by jonathan-knapp** [comment]
Can you please give step-by-step what you did to crash it (1. I click...) and attach the log file? For this one we may need to do a remote session.

**Comment by TDJMurphy** [comment]
I will grab the logs when I am back in Adelaide, will provide the step-by-step instructions of how it is happening.

From memory but I will confirm the following: After a run has completed > select add measurement > draw the area> select run> >get HW data> check setting values> click start = Investigator shuts down

**Comment by MarkGuo7** [comment]
Thanks Tim

This may need a M4 machine to take a look.

**Comment by MarkGuo7** [comment]
Tim, any further updates? If it keeps happen, we may need online access to find out.

**Comment by TDJMurphy** [comment]
Hi Mark,

Nigel and I upgraded the system to 3.3.1 at the time to get it working. There have been no reported issues since.

**Comment by MarkGuo7** [comment]
Thanks Tim. Let's close it for the moment. Feel free to reopen it if popup again.
