### ISSUE TITLE
Bug-M4 Tornado Plus-AMICS 3.3.0.1903_Scan_Field_Size: When selecting get hardware investigato "Failed to set property Scan Field Size (um) to 14799.00 editing stage or properties in Tools doesnt stop this form occuring.

### ISSUE THREAD

**Issue by TDJMurphy** [Bruker-Amics/bugs_features#426]

**Comment by jonathan-knapp** [comment]
Please provide screen shots or video of the error and the exact sequence of events to recreate the issue. For all errors, please attach the log file from both the M4 software and AMICS Investigator.

**Comment by ChiLyMan** [comment]
Mark and Gerda have fixed this already. We had the same issue on the Berlin M4 Plus.
Mark or Gerda, could you help Tim update the M4 to the "special" Investigator version.

**Comment by TDJMurphy** [comment]
Will provide the logs when I am back in Adeliade...

Select add measurement> draw/select area to scan> right click on the are> click get HW data > warning pops up

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakkvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--679d54203ab747c9ecc4fb096f01edb2ccee71b6/Read%20hardware%20data%20error.PNG)

You can click ok, ignore it and a run will work fine.

Adjust values in Tools and editing the sample holder has had no impact. (will provide more information on this when I am back)

**Comment by TDJMurphy** [comment]
Is there a reason why there are "special versions" and fixes that are not in the latest release already? 
If it can be sent to me so I can update the system and not look like a fool in front of customers/Adelaide Microscopy... would be great.

**Comment by ChiLyMan** [comment]
Because Mark and Gerda only figured out the issue on Friday, and this is an interim fix so we can continue to test other features of AMICS on M4. 

Chi

**Comment by ChiLyMan** [comment]
Do we have any update on this? I know Andrew had this working on the M4 in Berlin. Was Gerda/Mark able to get this working?

**Comment by TDJMurphy** [comment]
Bug is fixed, error is not coming up with latest version
