### ISSUE TITLE
Ability to update reference spectrum

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#427]
It would be really handy to have the ability to update the reference spectrum associated with an ore type entry.

For instance, if I have a noisy, measurement-derived reference for, say, tourmaline, it would be really handy to be able to update with a better one from a direct measurement, an Esprit spectrum file, or even the spectrum tree. 

At the moment, you have to create a new entry but this has a few disadvantages (ore types get quite messy, you have to reclassify the measurement before updating a grouping, creates inconsistencies if you have a long-running reference ore type etc etc).

Apologies if this already exists (can you let me know where to find if it does?).

**Comment by jonathan-knapp** [comment]
This will be fixed in the 3.5 release in March - or changed.
