### ISSUE TITLE
Process grabbing focus and message boxes are always on top - option to disable is gone

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#428]
v3.3.0.1961 (and for much of 3.3 I think)

This one was fixed a while back but seems to have crept back some time ago so I'm logging as a bug (was tempted to put it as epic because it is so annoying though).

The progress message box is always on top and when any classification is complete, Process grabs focus. 

E.g. If I am working on something while Process is doing its thing, the progress box will be in the middle of the screen, on top of 
everything and hiding stuff. When I move the progress box out of the way, I am dragged back to Process (away from whatever I was working on) often causing me to lose my train of thought or if working on multiple instances of Process, it can be really tricky to get back to the version you were working on.  

Also, even if Process is working in the background, once any process (e.g. batch, reclassification etc etc) is complete, Process steals focus e.g. I can be writing an email (or GitHub issue report - like just now) and be mid-word when Process snatches back focus. This is swearing-out-loud annoying.

Can you reinstate the option to disable the always on top messages and prevent Process grabbing focus once it has completed something please? (My colleagues and neighbours will also thank you!)

**Comment by ChiLyMan** [comment]
on version 1996 AMICS Process can be minimized during reclassification and it will not open back up or take focus.

**Comment by ChiLyMan** [comment]
Looks like this has returned in latest version.

**Comment by AlexeiDolgolyov** [comment]
Current progress window implementation seems to be kinda strange in my opinion. Hard to understand some source code sections, but I think I've managed to fix this issue.

**Comment by ChiLyMan** [comment]
Version 3.4.1 Fixed.
Process can know run in the background.
