### ISSUE TITLE
It is possible to create standards with duplicate names (again)

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#429]
v 3.3.0.1961
You can create mineral standards with duplicate names again (it was fixed but looks like it has now crept back in somewhere between 1701 and 1961). 
In previous versions this caused significant issues (ore types get corrupted etc etc) so assuming that this will cause the same problems in 1961?

**Comment by Matt-Power** [comment]
This does indeed cause a lot of problems if / when duplicates are created (groupings get corrupted and other unexpected bahaviour).

**Comment by GGloy** [comment]
@Matt-Power yes I noticed that as well, and should be fixed again in vs1977

**Comment by ChiLyMan** [comment]
Seems to be fixed in vs1983.
@Matt-Power Can you confirm.

**Comment by ChiLyMan** [comment]
@Matt-Power I'm going to close this one as testing on v1983 it will not let me have duplicate standards. but open if you notice it again.
