### ISSUE TITLE
Order mineral standards by "State"

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#430]
It would be really handy to be able to order mineral standards by their state / reliability e.g. so I can have all the high priority ones at the top.

Also would be handy to be able to sort by more than one thing e.g. sort by state and then alphabetically.

This would make editing and managing ore types / mineral libraries much easier - they can get really messy and disorganised at the moment.

**Comment by ChiLyMan** [comment]
<FIXED - sort of>
Checked in version 3.3.1 and ordering by state is now an option. 

wording of the option could be improved.
