### ISSUE TITLE
VS 1971 - Grouping lost after batch classification.

### ISSUE THREAD

**Issue by GGloy** [Bruker-Amics/bugs_features#431]
In the current build, after running a batch all grouped lists are lost. Before batch-

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcFpPIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--33e5bcd6b6953cb5a56ce4ed48bfb60bb3de5259/image.png)

After batch
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGRPIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bf6b10ff7e740fd7602071c7b59e6e0b004658f0/image.png)

**Comment by ChiLyMan** [comment]
I just tested this on 1983 with batch process, and as long as there are groups in the common library dictionary it seems to be copying over the groups correctly.

**Comment by GGloy** [comment]
@ChiLyMan you can close this, thanks!
