### ISSUE TITLE
AMICS_PROCESS: Returning the ability to export the color strip during excel export, rather than just the hex color code.

### ISSUE THREAD

**Issue by ChiLyMan** [Bruker-Amics/bugs_features#433]
Would it be possible to return the functionality of exporting a color patch into excel which was available in previous version of AMICS, rather than currently exporting the hex code only.

**Comment by jonathan-knapp** [comment]
I think it was Microsoft that took this away... I'll check

**Comment by ChiLyMan** [comment]
Thanks Mark this has been put back in!!!
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnFXIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bc48174965e94049d4ee9a86ec83d1b3e96db7a0/image.png)
