### ISSUE TITLE
BUG - MAJOR - PROCESS - Pixel size on mapped images is misleading / wrong

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#434]
All versions.
The pixel size at the bottom left of the mineral images for mapped measurements quotes the BSE resolution NOT the actual mapping resolution e.g. the scale on a mapped measurement acquired at a step interval of 10 microns is quoted as 2 microns. This is really misleading.

The pixel size quoted for any mapped measurement should be the stepping interval. (Segmented images are fine, it's just maps.)

**Comment by MarkGuo7** [comment]
Hi Matt, could you give me bit more details? Or send me an image to show this issue. Thanks

**Comment by Matt-Power** [comment]
See image below - it's a mapped measurement that uses a 10 micron step size so the mineral image is essentially 10 microns per pixel yet the scale says 2 microns (because the underlying BSE image is at 2 microns). For mapped images, the scale for the mineral images should be the point spacing / step size, not the BSE pixel size (i.e. the scale should read 10 microns in this case).

![image](https://github.com/Bruker-Amics/bugs_features/assets/84986921/fef27549-fc59-4589-9751-afd985b8aebc)

**Comment by ChiLyMan** [comment]
Changed PixelSize to PrimaryPixelSize to remove confusion on what the number is representing.

**Comment by Matt-Power** [comment]
@ChiLyMan 
I think that this is missing the point. No one looking at the mineral images wants to know the underlying resolution of the image, they want to know the size of the step used for the mineral layer i.e. how big the collection of pixels that represents one EDS spot is.
This is a constant frustration to me as we have clients that assume we are measuring things at 2 microns (because that is what is displayed at the bottom left, regardless of what you call it), and also, if I need to quickly find out what step size I used in a measurement, I can't just look at the image, I have to open the measurement in AMICS (this is actually a lot more onerous than it seems, especially if the measurement is old and / or has been supplied by a client).

**Comment by jkabel** [comment]
Would a reasonable resolution be adding a separate "Matrix Step Size" property to the databar on maps collected in matrix mode?

**Comment by Matt-Power** [comment]
Yup, that would work. (Although "matrix" has a specific geological meaning so the exact wording needs to be different e.g. Mineral layer step size or Mineral step size or whatever.)

**Comment by ChiLyMan** [comment]
It would be Xray step size.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Matt-Power** [comment]
Perfect.

**Comment by AlexeiDolgolyov** [comment]
Probably was fixed with #1328. Need to recheck.
