### ISSUE TITLE
Additional scale bar measurements - no way to switch off

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#438]
3.3.0.1977

There are additional length markers on the scale of the exported images (see below - the grey arrows markers along the bottom of the image). They could well be useful in various circumstances but they really mess up our post-processing and there is no way to switch them off. 

If these have been added intentionally, can you please add an option to remove them? (Ditto for anything else that changes the appearance of the final images - no problem to add features but please always include options so that they can be disabled.)

![image](https://github.com/Bruker-Amics/bugs_features/assets/84986921/843bb55c-abbb-4aba-8d8c-58cd6fa097ad)

**Comment by MarkGuo7** [comment]
Sure, Matt
I will include this option.

**Comment by Matt-Power** [comment]
Great thanks!

**Comment by MarkGuo7** [comment]
There is an option in Processing: Other View Options -> Meter Block Markers
It will switch on/off this export meter. The default will be off.
