### ISSUE TITLE
Process - BUG - Spectrum tree as classification step not applied (V3.3.0.1977)

### ISSUE THREAD

**Issue by scarlett-01110011** [Bruker-Amics/bugs_features#439]
Hi Mark,

The spectrum tree as a classification step is not being applied during reclassification in version 3.3.0.1977, and neither are the touch-up steps saved to the ore type.

Thanks,
Scarlett

**Comment by Matt-Power** [comment]
@MarkGuo7 and @scarlett-01110011 Just to confirm, I could recreate this. I had a bit of a play as well and the behaviour is quite odd. Here's a bit more detail in case it helps:
When reclassifying, the spectrum tree steps are not applied.
However, if you then reclassify a second time, the steps are applied (or at least show in the displayed image).
Ditto for unselecting the spectrum tree step - reclassify once and the steps remain even when de-selected. The steps are only removed once you reclassify a second time.
And finally... if you reclassify once with the step enabled and then reclassify a second time with it disabled, the result shows that the step has been enabled (i.e. the results seem to be reading the previous classification's data).

**Comment by GGloy** [comment]
This is still the case in vs 1983

**Comment by ChiLyMan** [comment]
Both spectrum tree and Touch-up steps are being applied the first time and every time a specimen is being reclassified. I've tested this on both a single sample reclassification as well as on a batch mode reclassification and in both cases it is working.
NOTE: This will work for Particle Mapping sample type, but the grain touch up will NOT work on Matrix Mapping type. These specimens need to be converted to Particle Mapping type by using the Particulation function first, then it will work.

tested on version 1996.

**Comment by scarlett-01110011** [comment]
Thanks Chi and Mark,
I will update to version 1996
