### ISSUE TITLE
Move Groups Up and Down in Group Editor Pop Up

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#44]
Put ability to change order of mineral groupings into the groupings editor (i.e. add up / down buttons).

Currently has to be done outside the editor and then a reclassification is required to make changes "stick" and if the list is edited before the reclassification, the assigned order is lost.

**Comment by jonathan-knapp** [comment]
Let's have this automatically added as a touch-up step called "Manual Assignments" so that they will be assigned every time it is reclassified.

**Comment by ChiLyMan** [comment]
Hey Matt,
I was testing this on 3.3.0.1315 and you can shift group order in the "Current Result Standards" using the up and down button. The ordering does not seem to need reclassification to stick, and the order survives reclassification (even if the new oreType does not match, you just get left over species at the bottom). I also modified the list, and after modification there was no need to reclassify to make the new modify list work, and it also stuck and survived reclassification. 
Additionally, if you modify the order in the "Current Results Standards" and then go back into the pop-up group editor, the new group position is reflected in the pop-up.
I know your request was specific for functionality in the pop-up menu but does this utility meet your needs? Or am I missing something?

**Comment by Matt-Power** [comment]
This is a really old thread so it was fixed (of sorts) a while back I think. However, it isn't 100% reliable - there are plenty of times that it reverts back to a previous order. I haven't figured out in what circumstances this happens but it is still an issue, even in 3.3.0.1315. I'll try to keep my eye on it and figure out when it happens.

**Comment by ChiLyMan** [comment]
OK That would be great. I've been fiddling around with it and have not seen it revert so if you do see if let us know.

**Comment by Matt-Power** [comment]
Just had the order disappear on me again so this issue is still there. In the latest instance, I set the order to what I wanted, brought it back into the ore type (where it shows in the correct order) and then did a batch assign to all of the samples. When I open up one of the other samples, the order is back to the previous order. I suspect if I re-apply again it will work but not 100 % sure and need to work on it anyway so things will change.

**Comment by Matt-Power** [comment]
OK, bit more digging - it doesn't actually show in the correct order when I import back into the ore type. The groupings are correct but the order will not change to the new one.
Interestingly, if I rename and reimport to the ore type, the newly imported list is in the correct order (the old one is also preserved but with incorrect order).

**Comment by GGloy** [comment]
@knapp-amics Same as #267 - re-ordering groups is not working in latest build (1508) - reported to Mark. This ticket is a duplicate and can be closed
