### ISSUE TITLE
Add a Crop tool and Save Particle List as a New Measurement 

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#440]
## Use Case 
A crop tool would be super-useful, especially for irregular samples and samples that comprise several large chunks of material. At the moment, you can delete unwanted segments but this is fiddly and the BSE / secondary channels are unchanged.

Also, the MLA workflow allowed the user to save a particle sub-set as a new measurement. 

## Solution 
1. A new tool that crops not only the mineral and segment layers but also the BSE (and any secondary channel) at the new pixel level. 
2. This can be restored with the undo button or by restoring. 
3. Add a new top level function "save as new" that will save any data as a new measurement 
- With any filters applied on any tab 
- Without deleted segments / pixels

**Comment by jonathan-knapp** [comment]
It's not crop, but you can now select particles and save them as a new measurement.
