### ISSUE TITLE
Batch window won't close after completing

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#441]
v3.3.0.1983
The batch status window does not close after running a batch. There is no X in the top right corner so I can't kill it that way and the Stop button doesn't do anything (because the batch has finished). It also sits on top of Process so it hides big parts of the screen. Only way to clear it is to restart Process completely which is a pain.

**Comment by ChiLyMan** [comment]
@Matt-Power Do you mean this window?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBay9NIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a9ad14e7a8bef7bb71febf8ba8368055502406ae/image.png)

**Comment by Matt-Power** [comment]
@ChiLyMan Sorry, can't see that image - permission denied. Can you paste into here?

**Comment by ChiLyMan** [comment]
On Friday, 22 September 2023 at 01:50:15 pm GMT-5, Matt-Power ***@***.***> wrote:  
 
 


@ChiLyMan Sorry, can't see that image - permission denied. Can you paste into here?

**Comment by ChiLyMan** [comment]
1996 the "X" in top right-hand corner is avaliable to close the Batch Window
![image](https://github.com/Bruker-Amics/bugs_features/assets/84643841/e807d4d8-c0cb-471d-8cea-496491330119)

**Comment by ChiLyMan** [comment]
@Matt-Power Can you confirm in the newer version if this issue is resolved?

**Comment by Matt-Power** [comment]
@ChiLyMan yes, thanks, this is now resolved although it takes forever to actually quit (it did in previous versions too so nothing new). If there is a way to get it to stop immediately without breaking the measurement, that would be much appreciated.
