### ISSUE TITLE
Spectral matching unreliable

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#442]
v3.3.0.1983
The spectral matching is different when run from a batch vs reclassifying against the ore type for the current sample (and reclassifying against the current standard list also gives a different result). Looking at the unknowns, it seems that there is a problem with reclassifying the current sample against the ore type.

For instance, when I ran a batch reclassification, unknowns would be 0.2 % but after reclassifying using the same ore type (but using the reclassify button, not a batch), this went up to 1 %. When I click on one of the unknowns, the matching table will show that there is a match of >70 with anorthoclase even though the reliability is set at 65 (i.e. it should have been classified as anorthoclase).

If I then reclassify against the current standard list, it works as expected and the unknowns go back to the original value of 0.2 %.

This seems to be a new issue as it didn't seem to be a problem in v. 1970.

For info, no steps were enabled.

**Comment by MarkGuo7** [comment]
Sorry about that, Matt

I will take a look today, Mark

**Comment by MarkGuo7** [comment]
Hi Matt, sounds like it used different matching threshold.
I tried several times, but couldn't repeat it. 

Could you try this latest version to see if it still there? https://bruker-my.sharepoint.com/:u:/p/junfeng_guo/EYFFpjFOZQJPoXRH3QwuDUYB6pTLxSXujC0ro_fTtIWixw?e=2Q5afX

It should be ok with the issue of batch processing.

If still have this issue, I may need your help to send me a sample dataset, so I can repeat it here.

With thanks

**Comment by Matt-Power** [comment]
Hi Mark,
Thanks - I'll give it a go. It's a strange one as it seems to just be that project (others seem to be OK) and the matching was definitely correct when reclassifying and re-classifying. I'll keep on testing with that new version to see if I can reproduce.

**Comment by MarkGuo7** [comment]
Hi Matt

There must be some corner that I didn't notice. You are the deepest tester.
:)

**Comment by Matt-Power** [comment]
Maybe I'm just jinxed ;-)

**Comment by MarkGuo7** [comment]
Hi Matt, I moved this one into the review list for the moment. Please let me know if you want to reopen it.
