### ISSUE TITLE
Investigator: properties not copying to other measurements.

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#443]
Thought that I'd raised this already so apologies if this is a repeat but copying measurement properties to other samples does not work in Investigator 3.3.0.1983.

If I fill a holder with samples, set up a measurement on the first sample and then duplicate to the other positions, the field area resets to the default. I think have to redraw the same area and makes sure I have the correct number of fields etc. When duplicating a measurement, please make it that all settings (e.g. overlap, segment info or step size, field area / shape) are copied with it - or at least give the option to do so. 

Similarly, if I fill a holder with samples and add a new measurement to each, set the parameters for the first sample and then copy settings to other measurements, it doesn't work - field area, field overlap, stepping interval (or segment info) are not copied. Each measurement has to be set manually.

**Comment by MarkGuo7** [comment]
Sorry Matt

This bug should be fixed now. 
One question, do you want to copy the measurement area while coping the parameters?

**Comment by Matt-Power** [comment]
@MarkGuo7 Yes please copy the area (or at least have an option to do so). The measurement area is important to keep consistency through a project. The position of the measurement area relative to the centre of each hole is less important so that doesn't need to be copied over - an option to include would be useful though.

**Comment by ChiLyMan** [comment]
@Matt-Power You can copy the position of the run by using the option "Copy Settings To..." after you "Duplicate the Measurement To..." the various sample locations. 

@MarkGuo7 how easy would it be to put a check box in "Duplicate the Measurement To..." which will also execute the "Copy Settings To..." option as well?

**Comment by Matt-Power** [comment]
@ChiLyMan The issue is that the Copy Settings To doesn't work in v. 1983. It worked OK in previous builds.

I have done some playing and it is the default option that does not work but if you also select "Copy hardware settings", the other settings are copied. However, this overwrites WD / focus settings which I do not want (i.e. if I have to set up a holder but need to copy across some new settings, I'll have to redo focus - a right pain when you have a full 28 samples).

**Comment by MarkGuo7** [comment]
Hi Matt

Could you try this latest build?
https://bruker-my.sharepoint.com/:u:/p/junfeng_guo/ETxKJmvrLEtIpEbdTVV6gswBb_JRvt1z1kgxsItQJt7y9w?e=uRcAKI

**Comment by ChiLyMan** [comment]
The "Copy Settings To" will allow for the option to only copy the properties of the measurement including the position, and/or the HW settings.

Version 3.3.2
