### ISSUE TITLE
Testing: Quantification Testing

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#455]
Play with Quantification in both Investigator and Processing. Try different Quant methods to see how good they are

**Comment by AHM-amics** [comment]
I will do some more testing.  Currently, as far as I am aware, AMICS only imports the “first” results generated by Esprit / M4 quantification.  However, the software during a calculation generates the following: elemental, elemental normalised, stoichiometric, stoichiometric normalised, net sum, net intensity plus errors (1, 2, or 3, sigma) with results in %, per mil, or ppm.  Hence, we need to update the options for what can be imported or displayed in AMICS.
