### ISSUE TITLE
Testing: Spectrum Tree in Processing

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#463]
Play with spectrum tree in Processing

Generate steps
Generate standards
Do classification with steps

**Comment by AHM-amics** [comment]
Spectrum Tree is now very powerful.  And it is especially very useful for MicroXRF data.  However, there are still some bugs. Specifically, when trying to apply the spectrum tree classification steps during a “re-classification” of the data it does work correctly or at all.  However, within spectrum tree it is possible (sometimes) to select “apply cluster” and it works.
This process would be extremely useful for M4 data if the “pseudo-BSE” values generated upon import could be used as “BSE” values in the spectrum tree.  Thus allowing a filter to easily remove resin or identify pores in samples.  Currently this is not functioning.
