### ISSUE TITLE
BUG: MAJOR - PROCESS - Batch Process Randomly Stalls

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#467]
v3.3.0.1990

The batch process now randomly stalls. It will process some samples but then gets hung up. It doesn't stop at a specific sample - could be the 5th sample, could be the 10th (i.e. it isn't a corrupt measurement).

Works fine in previous versions.

**Comment by Matt-Power** [comment]
Unfortunately, this happens a lot and means I cannot use v 1990 for processing. It seems to happen after about 10 samples or so but it is random.

**Comment by ChiLyMan** [comment]
@Matt-Power is this still happening in 3.3.1?

**Comment by Matt-Power** [comment]
Think that this is fixed now.
