### ISSUE TITLE
Zen hub images do not show in this group

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#469]
@MarkGuo7 @ChiLyMan 

ZenHub images do not show in GitHub - they are all marked as private and can't be accessed. Can you make sure that you copy your images into GItHub or find a way to make the ZenHub images public so that I can see them please?

Not AMICS related but it makes beta testing really difficult.

**Comment by ChiLyMan** [comment]
@Matt-Power I've checked with ZenHub and they are not looking to change this policy.

We will notify all the Zenhub users about this, which mean we have to jump back and forth between Zen and Git.

**Comment by ChiLyMan** [comment]
ZenHUB issue nothing we can do about it.
