### ISSUE TITLE
Two Point (Brightness and Contrast) BSE Adjustment

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#471]
Would it be possible to add a two point BSE adjustment i.e. brightness and contrast please?

Points for adjustment could be background and then a selected mineral.

**Comment by ChiLyMan** [comment]
@Matt-Power Did you download my BSE Calibration App?
I know it is not integrated into AMICS :(, but it will let you selected a section of the screen, and provide a labeled histogram so that you can calibrate the brightness and contrast like the good olde days.

**Comment by Matt-Power** [comment]
No I didn't (sorry) but I guess this request was closely linked with #470 i.e. do within AMICS and include as a batch option.

I'll have a look at the app - does it do more than one sample at a time?
