### ISSUE TITLE
BUG: MAJOR - M4 - Dead Loop Issue

### ISSUE THREAD

**Issue by TDJMurphy** [Bruker-Amics/bugs_features#472]

**Comment by TDJMurphy** [comment]
[Investigator32_2023_11_03_17_25_42_Debug-1000.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHV5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--800d5d20a8ee692439c4a9ba00e53577c620e60d/Investigator32_2023_11_03_17_25_42_Debug-1000.txt)

**Comment by TDJMurphy** [comment]
[Investigator32_2023_11_03_17_25_42.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDJ5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d68344feec0fe8482fce0daffc84df4bcd9bb22/Investigator32_2023_11_03_17_25_42.txt)

**Comment by TDJMurphy** [comment]
[MeasureRecordFile.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDZ5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6035ac138ad60120fd0e4bcb38778b84260aca9b/MeasureRecordFile.txt)

**Comment by MarkGuo7** [comment]
Thanks Tim

Already asked Thomas.
Let's see

**Comment by MarkGuo7** [comment]
Hi Tim

Thomas asked for the log files.
Seems I don't have the permission.
And do you have the Esprit log? Normally they will need Verbos logs.

**Comment by ChiLyMan** [comment]
This has been resolved.
