### ISSUE TITLE
Investigator - Mineral Groupings and Steps Not Applied at Measurement Time

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#473]
3.3.0.1983

Mineral groupings and steps are not applied at measurement time.

For instance, if I have an ore type with set of mineral groupings, these are not applied during the measurement (the result just shows the ore type) and I have to import afterwards. 

Similarly, it does not appear that any spectrum tree steps are applied (can't be 100 % sure because the data are also slightly different - will raise a separate issue once I figure that one out). [Slight edit - they are also not transferred to the measurement so I am pretty certain that they are not being applied].

For projects where I have a reliable ore type (that inevitably includes groupings and steps), I still have to reprocess all measurements afterwards which is totally counter productive and time consuming. 

Both mineral groupings and any steps associated with an ore type should be applied during measurement so that the results do not have to be reprocessed just to apply steps and groupings.

**Comment by MarkGuo7** [comment]
Thanks Matt

I will take a look of this.
First, the mineral grouping definitely need to be applied.

But need to consider the spectrum steps, whether or not.
Since some steps will do bit different between sample base and frame base. 
For example, the if you cut by percentage, by size, or auto generate standards.
The classification by frame most likely will not the same if do it by sample.

How about I give you an option to do classification automatically after measurement finished?

**Comment by Matt-Power** [comment]
Hi @MarkGuo7 

Thanks for looking into it.

For the steps, doing an auto classification after the measurement might work if it doesn't slow Investigator down. However, it does mean that the classification is effectively needlessly repeated so I would much prefer an option to apply the steps as it goes along during the measurement. Mind you, if you could automatically reclassify including all steps AND an option to do the stitching properly (the stitching during measurement is not good so always has to be redone), without slowing measurement and acquisition, that would be useful. 

The main application is that I have projects with hundreds of samples, all of which have to be consistent and processed with the same steps and list. I have a reliable ore type, groups and steps but at the moment, I have to reclassify every sample before I can get the data that I need. This is very time consuming so I'm looking at ways to cut down the repeated steps and other wasted time. For instance, if I have to reclassify every sample anyway, I may as well have an ore type for the measurement that contains only two entries (to save a few seconds at the end of each frame). It would seem much more streamlined (and automated) to fully classify on the fly so that you have final data as soon as the run is complete.

**Comment by MarkGuo7** [comment]
Thanks Matt

I will take a look of doing classification after measuring. 
Of course will think about other options, like stitching and exporting etc.
You may take a look of the exported bse image to see if the stitching is ok or not, then you can decide manually redo it or not.
Let me know if you have any other suggestions.

**Comment by Matt-Power** [comment]
@MarkGuo7 thanks, appreciate it.

For the stitching, it is never correct from the instrument and has to be redone every time (so I don't actually need to check). Is there a way to improve the accuracy, especially where there is a slight vertical / lateral offset (rather than just a straight overlap)?
 
The main point is that if you are running 10 samples or so, looking at the BSE images, reclassifying etc etc is just an irritation and not a significant problem. Unfortunately / fortunately (depending on how you look at it), most of our projects are hundreds of samples and it becomes a massive problem. For instance, just applying touch up steps (because they aren't applied during a batch) for a single project can take me over a day to do. You've fixed several of them recently (thanks) but there are still a few other areas where processes have to be repeated and / or are not fully automated and it sucks up an enormous amount of time.

**Comment by MarkGuo7** [comment]
Hi Matt

I guess it is time to review these classification steps, including batching.
If you can list the things that spend most of your time and painful, from Investigator to Processing, then I will try my best to improve current procedure.

For example, like we discussed, I will give you options to do classification after the measurement finished. These options will include stitching, classification, exporting.

I will fix the grouping not apply in Investigator.
I will fix the issue of touchup in batching issue.
Anything else?

**Comment by Matt-Power** [comment]
Hi Mark,

Thank you, really appreciate it. The options to classify (with all steps and groups), stitch, export of BSE and mineral images would really help.

There are several other things but I can't think of many right now (they come to light as I work through a project and then I forget about them until the next time. Duh / sorry.) I will drop them on here as I remember / come across them again. Here are the current ones that I'm struggling with - I think there are tickets covering them but just in case:

Batch data extraction is a lot more time consuming in the current version (not run any specific tests but as far as I remember, it is about 3 minutes vs 30 seconds so very significant, especially for big projects). Reclassification seems very slow too but not compared like-for-like yet.
Batch data extraction is not reliable (fails after a random amount of time).
Groupings and steps are not archived when exporting an ore type - means I have to keep lots of ore types on my system so takes forever to load them when running a batch for the first time etc.
Properties like density and chemistry are set in the ore type and can't be modified in the current mineral list. Means that even small changes requires a complete reclassification of the project. If the values could be set / overwritten somehow without re-doing the spectral matching, that would save a lot of time.

Anyway, sorry to load you up with tickets - realise you've got pots of other stuff to get on with. I'll add some of the other workflow niggles / time draws as I come across them. 

Thanks!

Thanks and I do appreciate the fixes when they come - they all help!

**Comment by Matt-Power** [comment]
Remembered another one:
Is it possible to add a batch BSE adjustment please?

**Comment by MarkGuo7** [comment]
That's awesome, Matt

I will give it a try, and we can keep this conversion going while I am on that way.
Maybe I should have a workshop with you some time. Not sure how much we can solve together, but definitely need to buy you a beer :)

**Comment by Matt-Power** [comment]
Plenty of good beer spots in Vancouver... If you can wangle a trip for a workshop, I'll give you a guided tour of them!

**Comment by Matt-Power** [comment]
And another two:
Option to batch extract the modal data at the same time as the images (save running a batch again).
Option to include the secondary channel image (as above, batch has to be run separately for this at the moment).

**Comment by jonathan-knapp** [comment]
Hey guys... no action on this since November. Has progress been made so this can be closed?

**Comment by ChiLyMan** [comment]
All, I'm going to close this one for now, because we already have plans for a preprocessing for Investigator in future builds, but to avoid slow down we need to refactor the system to allow multithreading tasks.
@Matt-Power do not worry this feature is not forgotten it is on our roadmap already.
