### ISSUE TITLE
Reclassification is extremely slow v 3.3.0.1990 and 2055

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#474]
v 3.3.0.1900 and newer
Reclassification against the ore type is incredibly slow. A measurement taking 1 min 40 s to reclassify in v 3.3.0.1701 takes well over 30 mins (possibly over an hour - I gave up after a while).

This is for mapped measurements (not tested on segmented measurements) and is not measurement-specific (i.e. it's not a corrupted file).

**Comment by Matt-Power** [comment]
Still an issue in 2064

**Comment by Matt-Power** [comment]
Still extremely slow in 2074. Noticed that it does the first in a batch reasonably quickly (~2 mins) but then gets progressively slower - next measurement in batch was over 15 minutes and the third took forever so I killed it.

**Comment by MarkGuo7** [comment]
Sorry about that, Matt

First thing, could you check the Unknown Matching Data option is off or not.
This option is for detail matching unknown, by giving different matching categories.

This option is in the option page of amics processing -> "Spectra Params" -> "Unknown Matching Data".

If it is on, please turn it off and give it another try.
Otherwise, could you send me your result for detail checking?

Mark

**Comment by Matt-Power** [comment]
Hi Mark,

No worries (although it does prevent me from using newer versions of AMICS to reclassify which is a shame).

I can confirm that the Unknown Matching Data is off.

I will upload some example files tomorrow but it's not hard to recreate - just take a few mapped samples, create a batch to reclassify and then run it. It'll grind to a halt after a it's got through a few (and I suspect it will get progressively slower before it stops). I've got a lot of ore types loaded - I have to :-( - which makes opening a new instance of AMICS very slow (depending on the version).  So if you can't recreate, it might be worth loading up a bunch of ore types onto your machine and then trying again.

Thanks,

Matt

**Comment by jonathan-knapp** [comment]
@Matt-Power what's the status on this one? Has it been addressed by 3.3.1?

**Comment by jonathan-knapp** [comment]
@MarkGuo7 has this one been addressed? I think you were working on it?

**Comment by MarkGuo7** [comment]
I think so, but need confirm by Matt

**Comment by Matt-Power** [comment]
Yes, this is resolved now, thanks
