### ISSUE TITLE
BUG - MAJOR - Process - Image export

### ISSUE THREAD

**Issue by TDJMurphy** [Bruker-Amics/bugs_features#475]

**Comment by TDJMurphy** [comment]
Hey All,

When we export images in 3.3.0.1983 we see the following images with missing frames. It is hit and miss. Trying to work out if there is a cause, from the user side of things.
Any thoughts?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWJJQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5211e41548f0f7136a6a6cc461b1f2573291a2b6/SCO3%20ROP2-SampleH06-Particle%20Mapping_Mineral__Image.jpg)

**Comment by MarkGuo7** [comment]
Hi Tim

Did you export from batching?
And may I have your data and the steps to reproduce this issue.

With thanks,
Mark

**Comment by TDJMurphy** [comment]
Hi Mark,

The data wasn't exported via batching. it was using the export button in tools. I've attached the data to the NewSpec SharePoint as it is large.

https://newspecptyltd.sharepoint.com/:u:/s/NewSpecFileShares/EQAUq7pspopPrPRQvd4tXIsB_7uhAlMhG6xoQA_9fqPgsQ?e=m2BJdr

If the link doesn't work here ill send it through via email.

Cheers,
Tim

**Comment by ChiLyMan** [comment]
Guys, I just checked this out and it might be something to do with the data. Exporting using manual single sample or batch creates the same image with missing fields. And the missing fields are consistent with each export, regardless of the file format (PNG, TIF or BMP). I checked export from other data files and do not see this usse. Maybe there is an issues with the binary .fld file?

I tested further by doing a manual export of all the BSE field from the fld using Rob Python code and all field are exporting correctly. So the BSE daat seems to be there, its something during the exporting processes.

**Comment by jonathan-knapp** [comment]
@MarkGuo7  this has been addressed?

**Comment by MarkGuo7** [comment]
Exporting in Tool is not suggested. It's only for engineer debugging.
Didn't take a look yet

**Comment by jonathan-knapp** [comment]
Was this addressed? I don't think this was exported in tool.

**Comment by NewSpec-MattNg** [comment]
TESTED on ver 3.3.2.0 signed
I tested for this using "Export image" and "Export Screen" and saved as the 3 formats (bmp, tiff and png). I was unable to reproduce the issue. All images exported without missing fields.

**Comment by ChiLyMan** [comment]
@NewSpec-MattNg Did you test it on the data set from Tim? When I tested this before the issue seemed to be linked to the data set. It was happening in different versions.

**Comment by jonathan-knapp** [comment]
What was the status of this?!?

**Comment by ChiLyMan** [comment]
This was linked to the data set itself, not repeatable on other datasets, and testing the data on older version resulted in the same issue but only for this data set. So unclear if something went wrong during analysis. It is a NR-Bug
