### ISSUE TITLE
Incorrect context menu

### ISSUE THREAD

**Issue by Marco-ti** [Bruker-Amics/bugs_features#476]
![image](https://github.com/Bruker-Amics/bugs_features/assets/68710652/0a088e3d-5549-4187-8e3e-5907f3c6b441)
When right-clicking on most screens the context menu is replaced by the tab context menu. 
To bypass keep the right-click held down and it keeps the originals (correct) context.

**Comment by ChiLyMan** [comment]
This seems to be a windows issue; I've seen this on some PC and then on another PC it's all fine.
We will look into this once the final release as it is very inconvenient between windows install.

**Comment by ChiLyMan** [comment]
Duplicate critical issue logged. Closes this duplicate.
