### ISSUE TITLE
Field Adjustment BSE Collection

### ISSUE THREAD

**Issue by Marco-ti** [Bruker-Amics/bugs_features#477]
When processing a BSE Collection, after toggling field adjustment the image goes back to the original state, without applying the changes.

Auto Field Adjusted
![image](https://github.com/Bruker-Amics/bugs_features/assets/68710652/13abee59-e05d-4448-885f-6a8a45fdd7fd)

Field Adj. toggled off
![image](https://github.com/Bruker-Amics/bugs_features/assets/68710652/c9f72725-9ad0-45c2-b106-559fec4623b8)

**Comment by ChiLyMan** [comment]
@Marco-ti What version are you using and could you make the data files available for us to test?

**Comment by Marco-ti** [comment]
Hi Chi Ninh Ly,

I am using AMICS Process 3.3.0.1996.

Please find attached the files used:

Thank you
--
*Marco Timich *



Em qui., 14 de dez. de 2023 às 16:41, Chi Vinh Ly ***@***.***>
escreveu:

**Comment by ChiLyMan** [comment]
Marco,
I can not see the file attached. Can you try to send via normal email:-

chi.ly@bruker.com

**Comment by ChiLyMan** [comment]
This seems to be working in version 3.3.1
