### ISSUE TITLE
Esprit timeout during AMICS run

### ISSUE THREAD

**Issue by TDJMurphy** [Bruker-Amics/bugs_features#478]

**Comment by TDJMurphy** [comment]
https://newspecptyltd.sharepoint.com/:f:/s/NewSpecFileShares/EssNW878Y2ZNpsPlldBK5NcBm5_1LzJoOPpe_g1_12MAYg?e=lkc5NL

Hey Mark,

This is the issue that was seen at Rio Tinto. I have recreated at Adelaide Microscopy.

I have just emailed you and Chi. But I have attached the link here to the files.
It appears to be an Esprit problem, as it times out and doesn't reconnect during a run. As esprit isn't communicating AMICS just captures noise which is what was being seen at Rio.

Cheers,
Tim

**Comment by jonathan-knapp** [comment]
@MarkGuo7 is this one fixed? I think so. If so, please close.

**Comment by MarkGuo7** [comment]
I don't know. Couldn't repeat it.
Need someone else double check

**Comment by ChiLyMan** [comment]
I believe this has been fixed with the addition of the forces resting of the ExtControl flag in Esprit.
