### ISSUE TITLE
Export full individual grain properties

### ISSUE THREAD

**Issue by KarstenGoe** [Bruker-Amics/bugs_features#479]
For every individual grain (and/or particles), export full grain properties, ideally to CSV or XML/XLSX, similar to MLA DataView Grain Properties table.
Include particle/grain ID, mineral identification, XY position, size and shape information including equivalent circle diameter, mineral association boundary length, see example Excel file attached.
Individual grain/particle images not required. 

Some of our users request these to be able to do their own statistical calculations/plotting in other software. As far as I can see this currently can't be done using one of the Export or Show...Properties functions, so at the moment I'm still doing these measurements with the MLA software, which is not ideal for many reasons.

Many thanks!
Karsten

[Grain_properties_example.xlsx](https://github.com/Bruker-Amics/bugs_features/files/14456142/Grain_properties_example.xlsx)

**Comment by ChiLyMan** [comment]
Karsten, have you tried the Prop. button?
![image](https://github.com/Bruker-Amics/bugs_features/assets/84643841/b00aed17-f355-48e0-9699-693079595c96)

**Comment by KarstenGoe** [comment]
Yes, I have! But that only seems to contain a selection of parameters? For example it doesn't have the boundary length info (see Excel file I uploaded) that we'd need to for example calculate mineral liberation/assocation by particle size externally. 

And it looks like it can only do separate tables, like one for the particles (which only has number and wt% of different phases but no additional info on relations of phases within particle like invividual sizes/boundary...), and a separate grain table where there is no info on in which particle they are and which other phases with relation, etc?

Mineral liberation/association by particle size is something we regularly need and I can't see how to do that currently in AMICS (using 3.3.0.1996). I might post that as a separate issue.

I think I read in a different post that Python scripting may be an option? I'd be happy to give that a try.

**Comment by jonathan-knapp** [comment]
We are happy to help you with the Python scripting, but this is also a high priority task for us. I am going to add just a little more context before for the development team. 
**Background**
MLA has both a particle and grain table, but no visualizations. We want to emulate and improve on this. AMICS is also missing several mission-critical grain calculations. We will open separate issues for each calculation. 
**Tasks**
- Pre-calculate and store object shape values  
- Add a new calculation table for Objects
- Populate with selected layer data (segment, grain, particle) 
- Add particle export function (described below) 
- Provide functions to sort and filter 
- Include all fields in the "properties" table and all functions of this plus the additional fields in the export attached. 
- Provide the ability to turn columns on and off and rearrange.

**Comment by KarstenGoe** [comment]
So how would I go about the python scripting? 
I've for example also been using the BSE_image_export utility to extract individual BSE frames which is extremely useful. Would be nice to do the Fiji stitching with linear blending of the overlaps.
Can take this off-line (email?) as it getting off-topic.

**Comment by jonathan-knapp** [comment]
We will be able to do this in SPARK.
