### ISSUE TITLE
Bug - AMICS-3.3.0.2078

### ISSUE THREAD

**Issue by TDJMurphy** [Bruker-Amics/bugs_features#480]

**Comment by TDJMurphy** [comment]
Report from Rio when they run particle grid in AMICS process (online version) the software crashes. Waiting on log files to be sent from Rio Tinto. Will pass them on as soon as I receive them. I have also asked what version they are processing with offline to compare.

**Comment by TDJMurphy** [comment]
https://newspecptyltd.sharepoint.com/:f:/s/NewSpecFileShares/EkeXp54C-rxAjXiZYC8dGxYBxuAoW-zbFFUQbYIDl_22ew?e=Ot5K0E link to amics logs

**Comment by ChiLyMan** [comment]
Tim can you get the data from Rio and pass it onto us to test please.

**Comment by TDJMurphy** [comment]
I'll ask for a copy to be sent again

**Comment by jonathan-knapp** [comment]
This issue has been closed because it has no information. You MUST tell us what the bug is for us to fix it.
