### ISSUE TITLE
Bug - AMICS 3.3.0.2078 wrong kV in AMICS files/MQuant not working

### ISSUE THREAD

**Issue by TDJMurphy** [Bruker-Amics/bugs_features#481]

**Comment by TDJMurphy** [comment]
When collecting a spectrum in AMICS the accelerating voltage isnt collected properly. Aspectrum collected at 25kV is recorded at 20kV. This isn't occuring when they collect a spectrum in Esprit then load it manually into AMICS.

Also they find that Quant isnt working - is Quant still being worked on?

**Comment by ChiLyMan** [comment]
Is this from the M4 or SEM? I have notice that on the SEM the kV is always recorded as -1.

Any more clarity on what "Quant isnt working " mean? More details? Crashing? Freezing?

**Comment by TDJMurphy** [comment]
Hi Chi,

This is on the SU7000, when they capture a spectrum in AMICS it is recorded 5kV lower then the instrument settings. In the case that Dale showed me there were running at 25kV and it was being recorded as 20kV when we open the .spx file in a text editor. 

When they use the "Quant" fuction in AMICS after they have captured a .spx file nothing happens, the software continues to run and no quant value is returned. If they use the same file in ESPRIT and quant the spectrum, esprit throws an error as the accelerating voltage is incorrect

Since this is happened the team at Rio have just been using ESPRIT to do their quantification work without problem.

**Comment by ChiLyMan** [comment]
Tim,
Can you check something for me. Can he try collecting at different kV (e.g. 15kv, 20kv, 25kv) and check what the SPX is saving. See if the kV value saved is always 20kV.

**Comment by ChiLyMan** [comment]
I just tested the Quant function on version 3.3.1, and it seems to be working on my system. Is it possible to get access to the system to see step by step use of Quant, or if they can capture video or images.

**Comment by jonathan-knapp** [comment]
This issue is being closed because it is being addressed by a major project underway. Quantification will not work properly until AMICS 3.4 release in August.
