### ISSUE TITLE
Feature request: Table of mineral liberation/association by particle size

### ISSUE THREAD

**Issue by KarstenGoe** [Bruker-Amics/bugs_features#482]
One type of data representation that is requested a lot and would be quite important for us is a table of mineral liberation and locking/association by particle size, e.g. using square root of two size series (...+850µm, +600µm, +425µm, +300µm, +212µm, +150µm, +106µm, +75µm, +53µm, +38µm, +26µm, +20µm, +14µm, +9µm, +6µm....) or similar
for example like this:
![Table](https://github.com/Bruker-Amics/bugs_features/assets/124857817/fc0d8884-9310-4bd6-b944-aa3d0975affb)

Images for this can also be very useful, e.g.
![Image](https://github.com/Bruker-Amics/bugs_features/assets/124857817/147b8c57-a5da-4485-8dc5-7f52639cc9e6)

## Acceptance Criteria

- [ ] **Scenario: Table of mineral liberation/association by particle size**
  - Given the user is on a calculation tab
  - When the user selects the calculation
  - Then the selection shows mineral liberation and locking/association data by particle size
  - Then, when selected, they properly display the table or graph as above.

**Comment by jonathan-knapp** [comment]
It is not yet possible, but I have added this to a new project we will be starting soon. Thank you for the update.

**Comment by jonathan-knapp** [comment]
@ChiLyMan this is my highest priority request for this Atomic project.

**Comment by jonathan-knapp** [comment]
This will be included in release 3.5 for March 2025.
