### ISSUE TITLE
Dataset Reliably Crashes Process (3.2.X, 3.3.0-X, and 3.3.1)

### ISSUE THREAD

**Issue by jkabel** [Bruker-Amics/bugs_features#483]
I have a dataset that seems to reliably crash Process upon reclassification. The standard set used for classification doesn't seem to matter. The dataset was collected with 3.3.0-1996 on a Hitachi SU3900.

The dataset can be found here: https://owncloud.eoas.ubc.ca/s/46qfy6km6nYXwNR

Log file included here: 
[AMICSProcess64_2024_04_22_12_06_55.log](https://github.com/Bruker-Amics/bugs_features/files/15067611/AMICSProcess64_2024_04_22_12_06_55.log)

**Comment by ChiLyMan** [comment]
I'm looking at the file right now. but might need @MarkGuo7 help as it might be a memory issue.

**Comment by ChiLyMan** [comment]
Jacob
I deleted a bunch of the empty fields in your dataset and it will now reclassify. It's not the best answer to the problem, and we should try to figure out why there is a memory issue with the original larger area with all the blank field, but doing the following will at least keep you going.
<img width="859" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0N4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6aef5e58b400ed832fd5bf7c142175f9e27d87b1/image.png" alt="image.png" />

**Comment by jkabel** [comment]
Thanks Chi! I'll give that a shot if it happens again. I wound up re-running that puck.

**Comment by ChiLyMan** [comment]
Closing for now. Can open if it happens again
