### ISSUE TITLE
RIMS: Sorting Having Minerals by percentage

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#485]
Sorting Having minerals by percentage for customer selection

<img width="856" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU95QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ee041947638f99bcebacc0815c8ddb995cc9f74/image.png" alt="image.png" />

**Comment by ChiLyMan** [comment]
Done in TMQ branch
