### ISSUE TITLE
Customize the grid column and quant element list

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#489]
<img width="1065" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeSt5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ddb574bcb0c409264b12ddc374f0c5d160a2db9b/image.png" alt="image.png" />

<img width="758" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekN5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--045bbf3bcde5ee32e2e300b571b976bc15eb396c/image.png" alt="image.png" />

**Comment by ChiLyMan** [comment]
Working in TMQ Branch
