### ISSUE TITLE
Reported Pore Space in Summary Table

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#49]
The porosity value remains in the table even after all pores are deleted. This is not necessarily a bad thing though - could be really useful depending what it refers to. 

What is this value? Is it the area of dark space in the image, the originally identified pore space or something else?

**Comment by van-amics** [comment]
Can you please give me a sample screenshot?

**Comment by Matt-Power** [comment]
<img width="785" alt="AMICSProcess64_AREVFzkSwF" src="https://user-images.githubusercontent.com/84986921/121723662-a613f700-ca9b-11eb-8cba-946a62b8d1ed.png">

**Comment by Matt-Power** [comment]
As I mentioned in my original email, this could actually be useful as the pores are deleted so I can get accurate grain density but it looks like the value is still preserved in the summary table on the right (which is also useful). It would be good to know how that porosity value is calculated given that the "pores" have been deleted.

**Comment by ChiLyMan** [comment]
This is linked to Issue #76. It is not just Pore which is not removed from the right-hand panel. Right now, that panel will not account for delected particles, including mineral species.
