### ISSUE TITLE
RIMS: Click particle image will select the row of grid row

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#490]
<img width="977" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek95QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--720e41867898d2c45e0ead422835c6bb40f52d51/image.png" alt="image.png" />

**Comment by ChiLyMan** [comment]
Working TMQ Branch
