### ISSUE TITLE
RMIS: Move xray here menu item 

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#491]
<img width="578" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelN5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--133938115c259594b17b570c9fee3592a93f5683/image.png" alt="image.png" />

**Comment by ChiLyMan** [comment]
Working in TMQ Branch
