### ISSUE TITLE
RIMS: Remove the selected particles from image view

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#492]
Use shift + mouse to select particles
Remove them from the list by right click

<img width="758" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemF5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--25e29cb44082a99813ae7736e327de5acf28bfc7/image.png" alt="image.png" />

**Comment by ChiLyMan** [comment]
Working in TMQ Branch
