### ISSUE TITLE
RIMS: Customize the filter xray circle color

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#493]
Because overlap with some mineral colors.

<img width="694" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem15QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08338626f435bf7578d5e511620572c574e76566/image.png" alt="image.png" />

**Comment by ChiLyMan** [comment]
Working in TMQ Branch (needs to move the view to refresh).
