### ISSUE TITLE
Result View locate function

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#494]
Can move view center to given particle or stage position.

<img width="677" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenl5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3fb9683781b5b383cd89bca1698bf899600db28d/image.png" alt="image.png" />

**Comment by ChiLyMan** [comment]
Change "Keep This" to "Keep Window Open"
Prevent negative value by pressing the back button at zero
Need to check with you on the goto X,Y position.

**Comment by NewSpec-MattNg** [comment]
MN Test ver 3.4.0.0 Unchanged. X & Y inputs goes to the correct position and ID inputs goes to the correct particles

! OUTSTANDING
=> Change "Keep This" to "Keep Window Open"
=> Prevent negative value by pressing the back button at zero
=> X & Y allows user to go outside of measurement area (is there a way to not allow this and warn user X or Y is outside of the measurement area?)

**Comment by AlexeiDolgolyov** [comment]
- Changed "Keep This" to "Keep Window Open".
- No way to enter negative particle ID now.
- Add message box (YES/NO) that warns user if user tries to go outside of measurement area.
