### ISSUE TITLE
RIMS: Save filter xray position settings with Fiducial point info, particle image, and xray spx files

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#496]
<img width="484" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGF5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6728ead4bf7997b7c9eb6451a8cd95518ea1edfa/image.png" alt="image.png" />

**Comment by ChiLyMan** [comment]
working in TMQ Branch
