### ISSUE TITLE
Show meter location and direction option

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#497]
Also can update its color etc

<img width="677" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG15QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c0b2874016c20cc0136e569438bf8319c197d242/image.png" alt="image.png" />

<img width="277" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHF5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e111c53d2347d6361832ebe1f12caa88f3c42561/image.png" alt="image.png" />

**Comment by ChiLyMan** [comment]
When deselecting "Horizental Meter" (BTW Horizontal spelt wrong) the test should also be rotated 90 degrees.

Currently the test overwrites the scale bar:-
<img width="157" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFhLQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--84d1becd8da8cee82b21d1a3d5d835d5120ab16c/image.png" alt="image.png" />

**Comment by NewSpec-MattNg** [comment]
MN tested (ver. 3.4.0.0) all "Location" with "Horizental Meter" selected and unselected. Also tested if the scale bar would change (size of scale bar and associated value) with the user zooming in and out. All working correctly.

! OUTSTANDING - spelling of "Horizental Meter" - please change to "Horizontal Meter"

**Comment by NewSpec-MattNg** [comment]
New ticket created for related spelling error. New ticket # 1107
