### ISSUE TITLE
BUG_AMICS_Investigator_MAJOR sometimes skips fields (3.3.1.0, 3.3.0.x)

### ISSUE THREAD

**Issue by jkabel** [Bruker-Amics/bugs_features#498]
I've seen this here and there. Sometimes investigator won't collect some fields of a measurement. Most of the time it collects alternating rows when this happens, but this time it was a bit stranger:

![image](https://github.com/Bruker-Amics/bugs_features/assets/12158231/f2effa42-9765-4ffc-9cfc-1a226beae198)

This does not appear to be a display bug. The datasets reflect this odd behaviour. 

Log file here:
[Investigator64_2024_05_01_09_21_00.log](https://github.com/Bruker-Amics/bugs_features/files/15202347/Investigator64_2024_05_01_09_21_00.log)

Dataset here: https://owncloud.eoas.ubc.ca/s/LAcQJXkXLGmZC9q

**Comment by ChiLyMan** [comment]
Could I get a copy of the debug log (Should be in the C:\ProgramData\AMICS\Log folder and will have same timestamp but will have "debug" in front of .log
Alos could you send me the .invst file so I can see the measurement set up.

**Comment by MarkGuo7** [comment]
I will try to repeat this issue tomorrow at UQ. 
Is anyone already know how to repeat it? Have the say, the results are strange.

**Comment by ChiLyMan** [comment]
We have not figure out what causes this and it seems to be somewhat random when it happens. You can check and try to repeat but don't spend too much time until I can talk to Matt Powers about this again when he gets back from vacations.

**Comment by MarkGuo7** [comment]
We tested at UQ system today with the same settings, but couldn't see this issue.

May need remote login the system to take a look.

Will close for the moment. Please feel free to reopen it if it popup somehow.
