### ISSUE TITLE
Export image with meter option

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#499]
Export image with meter under on / off option.

<img width="1389" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG5CQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--df057ea62f3c307c9057b23814bf183b7e21fc14/image.png" alt="image.png" />

**Comment by ChiLyMan** [comment]
Tested on BSE export only and working in TMQ Branch. There is a bug preventing exporting Mineral Map color images.

**Comment by ChiLyMan** [comment]
Tested on the updated 3.3 branch and working for Mineral Map and BSE.
