### ISSUE TITLE
Export Quant Result Info option dialog

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#500]
Customer can decide what to export now:

<img width="1025" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXZCQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c1aade064d120dfc673fb7e06b82abfced033aa/image.png" alt="image.png" />

**Comment by ChiLyMan** [comment]
working in TMQ Branch.
