### ISSUE TITLE
BUG_AMICS-3.3.0.2078_Investigator: BSE images compress and stretch

### ISSUE THREAD

**Issue by TDJMurphy** [Bruker-Amics/bugs_features#501]

**Comment by TDJMurphy** [comment]
<img width="1498" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelhTQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ab6e6921a55cfa36a0fbb458f808dc118e1d8842/Image%20compression%20and%20stretching%20SU7000.JPG" alt="Image compression and stretching SU7000.JPG" />

**Comment by TDJMurphy** [comment]
Issue occurred on SU7000 and is repeatable. Usual "standard" settings used to capture data.

Mark I have the Bruker and AMICS logs for this. Let me know how you would like me to transfer them.

**Comment by TDJMurphy** [comment]
Link to data has been emailed to AMICS support email.

**Comment by MarkGuo7** [comment]
Hi Tim

Somehow, I couldn't see the image. Could you update it? Thanks

**Comment by TDJMurphy** [comment]
<img width="1498" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0xTQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d7b07ec9a47dd387d9eb2e782d01909a2210166b/Image%20compression%20and%20stretching%20SU7000.JPG" alt="Image compression and stretching SU7000.JPG" />

**Comment by TDJMurphy** [comment]
Hi Mark I have added it again. There is also a copy of it in the AMICS support email which has the link to the amics and bruker esprit logs.

**Comment by ChiLyMan** [comment]
@MarkGuo7 I'll pull the images from support email and send to you if you didn't get the email.

**Comment by TDJMurphy** [comment]
Hey @MarkGuo7  and @ChiLyMan ,

I was working on this early this morning. It looks to be a coms issue with the SCU not an AMICS problem.
Feel free to close this ticket out.
