### ISSUE TITLE
Right click menu not showing in Calibration Image - Investigator - AMICS 3.3.1.0

### ISSUE THREAD

**Issue by Marco-ti** [Bruker-Amics/bugs_features#502]
After installing the new AMICS version (3.3.1.0) the right click menu does not show up on the Calibration Image tab in AMICS Investigator. For example, to 'get HW image' I need to go back to the sample holder tab, open the right click menu and click on 'get HW data and image'.

**Comment by ChiLyMan** [comment]
This has been fixed and will be released on the next patch of AMICS. Sorry for inconvenience.
