### ISSUE TITLE
Bug - Process 3.3.1.0 - Reclassify with Other Standards produces 100% unknowns

### ISSUE THREAD

**Issue by KarstenGoe** [Bruker-Amics/bugs_features#503]
Now with Process v3.3.1.0, when we use the function Reclassify | Reclassify with Other Standards (drop down arrow) the result is classified 100% as unknown. This was not the case for us in older versions. This is using Process 64-bit on Windows 10 Pro.

If we click on the Reclassify icon to open the "Do Classification Steps" window and specify the new Ore Type under "1. First, classify with a mineral standard list from:" it works fine.

**Comment by ChiLyMan** [comment]
We should remove this Reclassify with Other Standard option and just integrated into the normal Do Classification Step. Maybe just a 4th option to pull reference library from a MRE file.

**Comment by KarstenGoe** [comment]
Reclassifying with other standard in Do Classification Step works, but I have to manually refresh the ore type database first (under Classification in the left hand side) otherwise it uses the old (not updated) ore type.

**Comment by ChiLyMan** [comment]
Please try version 3.3.3, link below:-
https://help.amics.info/upgrade-to-amics-33


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by KarstenGoe** [comment]
As far as I can tell this is still the same with 3.3.3 - I need to refresh the ore type database first (under Classification in the left hand side) otherwise it uses the old (not updated) ore type for classification.

Maybe I don't understand how this is intended to work. The way I use this is that I have the measurements for a set of samples open in separate Process windows (so I can go back and forth between them to compare), then make changes to the ore type in one of the Process windows, and then reclassify the different measurements in the different Process windows with the updated ore type to see the effect. As far as I can tell I can't use Batch for that as it doesn't work for measurements that are open in Process (so I'd have to close them all and then reopen them).

One thing that is no longer working with 3.3.3 is launching data in Process by clicking on the measurement line in Investigator (or right-click). It will open Process and load the data but when it is finished the Process window just disappears/closes.
This was broken before but was working in 3.3.1. I used this as a quick way for opening a set of measurements from one run (compared to launching separate Process windows manually and then browsing to the different measurements in each one of them or locating them in a File Explorer window).
Is this a feature or a bug, and if the latter, are you already aware of it or shall I create another issue for this?

**Comment by ChiLyMan** [comment]
I will do some testing on your list, but I was able to test on 3.3.3 opening data using the Open Results File in Investigator without any issues.
Can I assume you can open the data set directly with Process?

**Comment by ChiLyMan** [comment]
Base on your usage case described, if you are performing manual reclassification of the data in these other Process windows, you should use the "Reload" button in the Standard tab to ensure that instance of Process has read in the most up to date list, before you reclassify.
<img width="317" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVExQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--469a22e7703ccc689e0c4aa4a478e2f937608afe/image.png" alt="image.png" />

**Comment by KarstenGoe** [comment]
> I will do some testing on your list, but I was able to test on 3.3.3 opening data using the Open Results File in Investigator without any issues. Can I assume you can open the data set directly with Process?

Yes!
