### ISSUE TITLE
Chinese toolbar disappear

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#504]

**Comment by MarkGuo7** [comment]
Switch to Chinese version, run any application. The toolbar couldn't show properly:

<img width="1167" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXQwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0bf0fbe19f04a0d1a95236c3b31744b32675602d/image.png" alt="image.png" />

<img width="1167" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXgwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3643e44f251f355a1eb3ce0137346d0e6770879d/image.png" alt="image.png" />

**Comment by MarkGuo7** [comment]
Show mfc toolbar for the moment, need to figure out how to match with bcg color theme later.

<img width="1094" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXQxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79944146fc1bbec9c5276fcfc69457c1b6cc7986/image.png" alt="image.png" />

**Comment by ChiLyMan** [comment]
I've checked this and noticed the color thing. Closing this and adding it to the exiting open issue in Core #1138
