### ISSUE TITLE
Version 3.3.2.0 I cannot change mineral groupings from OreType the measurement was run with.

### ISSUE THREAD

**Issue by PMC-Labs** [Bruker-Amics/bugs_features#507]
When reclassifying a measurement, I cannot get Mineral groupings anything other than what the measurement was run with I cannot seem do get the proper OreType with groupings from my offline copy.

I work exclusively from an Offline version when doing data processing, but this bug also occurs with the online version

It is almost like the keep mineral groupings check box (not in this version) that was in previous versions is stuck on.

**Comment by jonathan-knapp** [comment]
@ChiLyMan let's evaluate this for the patch.

**Comment by ChiLyMan** [comment]
@knapp-amics Let me confirm with Jason, this might just be related to the grouping is not copying over which is a known bug, which has already been fixed for the upcoming patch.

**Comment by ChiLyMan** [comment]
Linked to group copying over issue, which has already been fixed.
