### ISSUE TITLE
Version number, icon and invalid character of release file

### ISSUE THREAD

**Issue by MarkGuo7** [Bruker-Amics/bugs_features#508]
- The icon of processing not update yet.
- The file version is different with Product version
- There are invalid characters inside the Copyright string

<img width="873" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkNxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--351d2e948b7b2e3fc68bcb73bc99c4d51376a264/image.png" alt="image.png" />

**Comment by MarkGuo7** [comment]
Just leave it as is?

**Comment by ChiLyMan** [comment]
@MarkGuo7 
Just leave it for 3.3.3.0.
I'll mark it as a known issue, but we should just focus on 3.4.1.0 release...maybe change the these now as we know the version release will be 3.4.1.0.
