### ISSUE TITLE
Feature Request: Batch export option for second channel image

### ISSUE THREAD

**Issue by avdhandt** [Bruker-Amics/bugs_features#509]
Hello,

Could you please add a batch export option for the second channel image. We acquire both channels quite frequently and it would speed up data processing tremendously. Thanks!

**Comment by ChiLyMan** [comment]
This option is already present in the latest version of AMICS. If batch exported with the Export Image Mosaic selected, both the BSE and secondary channel are exported at the same time as part of the batch.
