### ISSUE TITLE
BUG: MISSION CRITICAL: PROCESS: Mineral Groupings are Not working 

### ISSUE THREAD

**Issue by PMC-Labs** [Bruker-Amics/bugs_features#510]
In all versions of 3.4 I am having problems with Mineral Groupings. 
All of the groupings are non-functional they show up in the list of groups but there is no grouping taking place

**Comment by jonathan-knapp** [comment]
This bug has been fixed according to my testing. Please download the new installer here: https://github.com/Bruker-Amics/bugs_features/releases/tag/V3.4Beta


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUlJQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd4d5677856ccb7e51e5f176fbac8c5dabbd3d52/2024-11-09_07-54-03.mp4)

If you continue to have this issue, please open a support ticket with support-amics.bna@bruker.com so we can see what is happening on your system with a remove session
