### ISSUE TITLE
Quantification is giving erroneous results

### ISSUE THREAD

**Issue by PMC-Labs** [Bruker-Amics/bugs_features#515]
when using quantification in Process, both TMQ and single spectra, I am getting results that are inconsistent with the actual spectra.

Specifically, I am running a method for Au, Ag and Te and a spectra which consist of Au and Ag peaks are giving Au and Te quantifications with no Ag. When I open a saved spx file in esprit I get an error when I try to quantify. Inconsistent angle specifications.

I attached the spx with a TXT extension in order to transfer here.

[ID(268).txt](https://github.com/user-attachments/files/18086332/ID.268.txt)

**Comment by jonathan-knapp** [comment]
Chi, this seems like a header issue. Can you heck it out? Also, please send Chi a copy of the SPX file and measurement.
