### ISSUE TITLE
Preserve All Spectrum Tree Branches Even Empty Ones

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#57]
Spectrum tree only displays branches containing spectra. Empty branches have to be displayed too. Apologies for the essay but there are many reasons that this is really important - a few outlined below:
It is very difficult to review steps and make sure they are correct or appropriate e.g. if a spectrum tree step successfully classes all spectra from unknowns, the tree will display as empty; there is no easy way to see which spectra are going to which standards. 
The above means that it is usually not easily possible to make minor changes to a spectrum tree step as there is no way to access the invisible branches.
When revising steps, only the active branches are saved so if you need to make a minor edit to an existing step (e.g. change a cut-off from 60 to 55), only the visible branches are saved (all other pre-existing but now empty branches are lost). Therefore, when the data are re-classified, the behaviour is often completely different to the original step. This makes simple iterative changes almost impossible (or a big hassle).
It is possible to workaround these issues by first reclassifying with the relevant steps switched off, reviewing the data and then resaving / reapplying but this means that for even tiny changes, you have to reclassify the data twice (a massive time penalty).
A related "feature" is that if you have to make a minor edit (such as changing a threshold value) to a branch near the trunk, all of the subsequent steps usually disappear and have to be reconstructed.
It is not always possible to account for compositional variations in other samples in a batch. If another sample does not contain a certain phase or if the chemical composition is out of range, it is not possible to amend the branch to account for this. For instance, if I need to include (or edit) a step to account for Fe in dolomite with a threshold of 100 but the current sample only contains dolomite with Fe < 75 and the other sample only contains dolomite with Fe > 100, only one branch is shown (in one sample it is the < 100 branch, in the other it is the >100 branch) and so I cannot assign the two standard needed. This might not be the best example but there are many cases where it is not possible to create a step to be proactive / predictive.  
There are other more or less subtle reasons but the above means that it is challenging and extremely time consuming when working through a complex project. If reviewing other people's work though, it is impossible without starting right from the beginning.
Hope the above outlines why the preservation of the steps is important (I would say mission critical) but the key thing is that by preserving and displaying the empty branches it makes everything much more predictable and simpler.

**Comment by knapp-amics** [comment]
Thank you for this detailed run-down. This has been added to the backlog as a high priority.

**Comment by jonathan-knapp** [comment]
@van-amics let's break this into several work items. We can dothe "view" of the text version this release and than move the rest to the release related to standards (2.4)

**Comment by Matt-Power** [comment]
This is now working in v1961. Thank you!
