### ISSUE TITLE
Investigator - Sort Sample Order

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#58]
Ability to sort (and unsort) samples by sample number, hole or mode within the On Stage Samples window in Investigator. There does not appear to be a way to sort or reset the order of the measurement file (right click and hitting reset does not work). For instance, if several samples are moved up the order but priorities change, there is no way to quickly reset the order, samples have to be reordered manually. In itself, this is fairly minor but the following points mean that there is a major risk to sample integrity;   
The order of the samples in the On Stage Samples table relates to the order in which they were selected in the block holder image. It is super-easy to mess up and not realise that samples have been selected in an incorrect order.
The Apply Layout button is great when running many samples with the same measurement. However, if the measurement priority has been changed for one batch, this order is preserved when the layout is reapplied often causing an inadvertent sample mix-up.
I've been caught out by both of the above more than once and it is really difficult to check for. Adding a button to default to the hole order and a warning messages when reapplying an out of order template telling the user that the holes are not in sequential run order would be really useful and prevent mix ups.

**Comment by MarkGuo7** [comment]
Please test with the version 2325, uploaded to GitHub under V3.1.2Beta release.

![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/5d16173f-9cb2-47ce-8603-36754e2ebfb2)
