### ISSUE TITLE
MicroXRF bcf Import into AMICS - dual detector

### ISSUE THREAD

**Issue by AHM-amics** [Bruker-Amics/bugs_features#60]
@knapp-amics @van-amics @MarkGuo7 This issue relates to the importing of bcf files from an M4 measurement and the loss of 50% of the data due to the separation of data streams for Detector 1 and Detector 2.

Example Data Sets are uploaded onto OneDrive:

Link: https://1drv.ms/u/s!AiQ95bfsvcO8hb9ZWLZCUIyH7OJFFA?e=l9CMLN

Message me for more information when needed.

**Comment by knapp-amics** [comment]
This issue is being addressed at this time. This is covered by a core issue and will be fixed by the beta release
