### ISSUE TITLE
Still can not quantify without Espirt installed

### ISSUE THREAD

**Issue by ChiLyMan** [Bruker-Amics/bugs_features#63]
![Quantification_Error](https://user-images.githubusercontent.com/84643841/122472966-d9b4bc80-cf86-11eb-8b2a-a2432b6509b0.JPG)

Still getting the EDS (no ESPIRT) error when trying to quantify. Maybe I need to install an additional ESPIRT demo version on the system?

**Comment by knapp-amics** [comment]
@Chi Vinh ***@***.***> what do you think about recording the "theoretical" and "measured" valued separately?




- confidential -
From: ChiLyMan ***@***.***>
Sent: Thursday, June 17, 2021 3:14 PM
To: Bruker-Amics/bugs_features ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Bruker-Amics/bugs_features] Still can not quantify without Espirt installed (#63)

**EXTERNAL EMAIL**

[Quantification_Error]<https://user-images.githubusercontent.com/84643841/122472966-d9b4bc80-cf86-11eb-8b2a-a2432b6509b0.JPG>

Still getting the EDS (no ESPIRT) error when trying to quantify. Maybe I need to install an additional ESPIRT demo version on the system?

-

**Comment by ChiLyMan** [comment]
@knapp-amics Do you mean the ZAF quant versus direct assay/book value?

**Comment by MarkGuo7** [comment]
Quanta is part of Esprit function. Need to figure out how to Quanta without Esprit. Is there a web solution?

**Comment by ChiLyMan** [comment]
If we can get the header information, there are non-Espirt options available for this.

**Comment by ChiLyMan** [comment]
The "Quantify Mineral Standard" option in **Process** pops up "Please run Espirt first." error all the time, even when Espirt is already open.
![image.png](https://images.zenhubusercontent.com/62f264fb4831bda01fb7d454/fc8e7d0a-52cf-43f6-b3ce-d1e59ec6428e)
