### ISSUE TITLE
Measurement locked out when checking the Key Mineral Analysis

### ISSUE THREAD

**Issue by ChiLyMan** [Bruker-Amics/bugs_features#65]
![BPS_Error](https://user-images.githubusercontent.com/84643841/122473169-17194a00-cf87-11eb-8809-2cda05990a4a.JPG)
When I set up a Bright Phase Search, and click the “Key Mineral Analysis” check box, it locks out all the measurement setting, including the “Key Mineral Analysis”. The only way to regain access to the setting is to select another sample and go back. But then if you uncheck the “Key Mineral Analysis” the measurement settings are locked again.

**Comment by MarkGuo7** [comment]
Is it still there? @ChilyMan

**Comment by ChiLyMan** [comment]
Hi Mark,

 

Sorry for delay in getting back to you let me check and give you feedback, I’ve been preoccupied with new job.

 

Chi

**Comment by ChiLyMan** [comment]
Hi mark,

Sorry for the delay again. I just checked the new build and the issues seems to be resolved. Just note that I am testing it on a standalone PC as I do not have access to the instrument anymore.

Chi
