### ISSUE TITLE
Ability to Generate Standard from Classified Spectra (Not Just Unknowns)

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#68]
Quite often I would like to create a standard from spectra that are already classified (to make a better match or split some similar minerals). I know it is possible to do this in Spectrum Tree (this is time consuming) but it would great to have the option in the right click menu (same as when you click on unknowns).

A warning message (and the option to switch off) e.g. "A standard already exists... yes / no" would prevent accidentally creating the standard.

**Comment by AHM-amics** [comment]
@Matt-Power Hi Matt. This is possible in the latest version of AMICS. In addition, a standard can be created from a combined group of pixels to give a more robust spectrum.
