### ISSUE TITLE
Image Editing Tools for Clean Up

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#72]
It's really useful to be able to get rid of image artefacts by "painting" them out. For instance, getting rid of bubbles, thin section glass and other random debris that can be within and around a sample (and doesn't always have a fixed chemical composition or shape). It is currently really challenging to do, especially on block type samples - particulates are a bit easier. 

Is it possible to implement image editing tools such as those in iDiscover? The paintbrush turning everything (or just selected minerals) to background was particularly useful. (Although I must admit being able to paint in minerals such as gold was dubious at best.)

**Comment by jonathan-knapp** [comment]
This is a good idea. I will add this to the product backlog for the next release
