### ISSUE TITLE
Process has become really, really slow

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#73]
Since including the standards hierarchy, Process is really slow. 

Process times have gone from 2 minutes to reclassify to upwards of 10-20 minutes per sample (this is on a fast desktop).
Switching between sample images and the calculations tables takes 2-5 minutes to appear (previously 10-20 seconds).
Just opening a file takes a few minutes.
More than 2 instances of AMICS running and doing something (e.g. 1 batch processing, 1 updating a table, and another doing pretty much anything) will cause an Out of Memory error and one instance will close (and the batch will fail).
With some samples, I cannot load the calculation tables for a grouped list - it takes forever and then crashes.
At various other points, it seems to just hang while it is waiting for something (seems to be when calculating the primary or secondary data).
I've looked at the task manager while this is happening and it shows that all memory and all logical processors (all 16) are maxxed out. In comparison, when I am doing a single batch process, there is plenty of headroom.
 
This has rendered it almost unusable for all but the most simple projects.

It could be that my system has a lot of ore types but I don't see why it would need to load those when opening or processing a file.

**Comment by Matt-Power** [comment]
Update: Just tried installing v. 2305 to see if that improves matters but still takes an age.

When opening a file, loading global standards takes a while.
When switching to the calculation tables or charts, it appears to hang calculating the primary data. Just sits there for ages doing something. Ditto with the secondary data.

**Comment by jonathan-knapp** [comment]
Matt,
Please roll back to the latest version that worked. Van is on vacation and he will address this when he returns and addresses a few things on the BiFROST critical pathway. I think that will need 2 or three days once he returns. Sorry, for the delay, but it is important. My sincere apologies for the slowdown, seems to be a memory leak. Make tome a bit to track down.

-Jonathan



- confidential -
