### ISSUE TITLE
Allow Batch Calculation to export multiple outputs

### ISSUE THREAD

**Issue by ChiLyMan** [Bruker-Amics/bugs_features#75]
Notice that the current Batch Calculation option on my version exports one output (e.g. Modal, Liberation, Assay etc) from multiple samples, which is handy. But in case no one had mentioned it might be useful to be able to select different outputs from multiple samples. 

But this might be something you guys are looking at including into an Auto-Reporting function.

**Comment by jonathan-knapp** [comment]
I have added this to the product backlog for the next release.
