### ISSUE TITLE
Mineral Area% Rename

### ISSUE THREAD

**Issue by ChiLyMan** [Bruker-Amics/bugs_features#76]
Not sure if someone else has mentioned this, but I remember that all the versions I've tried the Mineral Area % in Property on the Sample Images does not change when I do clean ups of images, or even delete particles. Though it is good to have a record of the original species distribution, it can sometimes help to know how clean up and particle deletions affect the bulk distribution without skipping back and forth from Calculation Table.

Maybe have "Updated" values in parenthesis? 

![image](https://user-images.githubusercontent.com/84643841/124143458-bf7fe180-da50-11eb-9ef1-9e7d2c0f20ea.png)

**Comment by ChiLyMan** [comment]
Hey Mark,
Van assigned himself this task as high priority but doesn't look like anything was done. I'm not sure it is High priority, and we can discuss if there is value in having this.

**Comment by MarkGuo7** [comment]
@ChiLyMan I will take care of it.

**Comment by MarkGuo7** [comment]
@ChiLyMan Hi Chi, I made the changes to update this mineral area %.
Please give it a try to see if it cover all the cases, such as stitching, deleting etc.

And somehow, these values are bit off with the values from calculation table. Not sure why, will need more time to figure it out as a separate issue.

**Comment by ChiLyMan** [comment]
Still does not seem to be updating the right-hand panel modal mineralogy.
