### ISSUE TITLE
Mineral accuracy plot stops at ~19-20 fields

### ISSUE THREAD

**Issue by ChiLyMan** [Bruker-Amics/bugs_features#77]
I just noticed that the Mineral accuracy plot does not plot past 29-20 fields. 

![image](https://user-images.githubusercontent.com/84643841/124148549-5b135100-da55-11eb-82e0-c6353a7fb632.png)

**Comment by jonathan-knapp** [comment]
This feature is not ready for production. We need to work more on that. Chi, let's discuss how to make this better at AAPG.
