### ISSUE TITLE
Mineral Grouping Locked Out

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#79]
It is not possible to edit a mineral grouping if it is in use in any of the tabbed sheets, not just the current sheet. You often have to hunt out which sheet is using the list which is time consuming.

For instance, if a mineral grouping is used in the Calculation Tables, Calculation Charts and the Sample Images, you have to click each tab, select a different grouping (or the primary) before you can edit the list. Each time a tab is selected, the data are recalculated before you can switch the mineral grouping at which point the data are recalculated again when the new, different grouping is selected (i.e. a minimum of twice before you can edit the mineral grouping). (For bigger datasets, the recalculations can be 2-3 minutes each time i.e. not trivial).

Can we have a "deselect mineral grouping" button so that it is possible to edit a mineral grouping without searching out where it is used and without all the associated (and unnecessary) recalculations please?

**Comment by jonathan-knapp** [comment]
@van-amics can you tell us if this is a fix we can do for 3.2 or if it is extensive and needs to be put off to 3.3. Matt, FYI, the 3.3 will not be too far off.

**Comment by jonathan-knapp** [comment]
This is super tough to change. If you use linking tabs, when you change it on one it will reduce this from happening. We will think hard on how to fix this. 
![image.png](https://images.zenhubusercontent.com/60a274843870252752494569/2526e4dd-ffcd-4049-9954-90095ffcaacb)

**Comment by Matt-Power** [comment]
I have Linked Tabs on by default so the issue still occurs / is not minimised using by switching on. The issue is compounded by the multiple recalcs bug as if I have to go back to a calculation table to change the mineral grouping (to release one for editing), I have to wait for the full calc of properties (which it does and then instantly does a second time but slower) and then again after I have selected the different mineral grouping (again, happens twice due to the bug). Only then does it release the grouping for editing. In large images, this can mean 10 mins of waiting (or longer) before I can access a grouping for editing. This means that minor edits can be really time consuming / problematic.

**Comment by jonathan-knapp** [comment]
@Matt-Power we need to change a lot about the mineral database to allow it to be global. This will need to be revisited after that change is made.

**Comment by jonathan-knapp** [comment]
This is being closed as the mineral database will be updated with the new file format. We re-adress soon-ish
