### ISSUE TITLE
Massive Memory Use When Calculating Primary / Secondary Data

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#80]
AMICS Process appears to consume a vast amount of memory when calculating the primary / secondary data (e.g. when switching from the sample images to the calculation tables tab). It usually happens if more than one instance is open. The calculations appear to stall (stuck on 0% progress) but it eventually finishes and releases the memory (can be well over a minute waiting and most other windows processes are slow or not working at this point).

Here's a snapshot from the Resource Monitor - AMICS is using virtually all the physical memory (in this case 32Gb). Normally, this would cause a crash but I've added more RAM.

![image](https://user-images.githubusercontent.com/84986921/125864698-4050e950-3c47-4ae6-b8fc-60c9c0a103fc.png)

And here it is in the process of happening (the Process window says "Calculating primary data (396521)" and the progress bar is at zero). The memory use ramps up until almost all is used:

![image](https://user-images.githubusercontent.com/84986921/125865563-5f4d2380-3089-4b3f-bef9-21c4d8c2c33a.png)

**Comment by jonathan-knapp** [comment]
@van-amics did you see this?
