### ISSUE TITLE
Missing fields???

### ISSUE THREAD

**Issue by ChiLyMan** [Bruker-Amics/bugs_features#81]
So after running the same sample three times, in one of the runs this section of the sample was skipped for EDS analysis. BSE image was collected, but no x-rays. Attached are false color images and BSE image, and I'll also attached the analytical conditions for the analysis.
![Missing Fields (Conditions)](https://user-images.githubusercontent.com/84643841/126429658-0673b19e-0f22-4ce1-bb43-34e37d70bb8d.JPG)
![Missing Fields](https://user-images.githubusercontent.com/84643841/126429659-ba9d706c-61b6-4f12-88e3-54cd6ded01b3.JPG)
![Missing Fields (BSE)](https://user-images.githubusercontent.com/84643841/126429660-3cd59f08-677a-4678-8b04-54db4922dcaf.JPG)

**Comment by ChiLyMan** [comment]
Just an update on this. Saw it again today on one sample. Looks like occurs in one field, and Nigel and I saw something like this when we were messing around with the Grey Level Factor, where the segmentation seemed not to be correct on lower section of field. And this unsegmented portion could change with changing Grey Level Factor, and then fixed itself.
For reference BSE, mineral and run condition images attached.

![Missing Fields (Conditions 2)](https://user-images.githubusercontent.com/84643841/126540733-2437d194-378c-4480-ac1c-71960dbb1dd8.JPG)
![Missing Fields (2)](https://user-images.githubusercontent.com/84643841/126540737-84b167ae-b95c-4742-81d5-47117ac8ad8a.JPG)
![Missing Fields (BSE) 2](https://user-images.githubusercontent.com/84643841/126540738-3f5e239f-a436-45a2-b620-a1ee63bb7e8e.JPG)

**Comment by ChiLyMan** [comment]
@MarkGuo7 Here is an interesting example of the missing fields issues I noticed today. In this case we are seeing two fields which have been affected, and the cut off seems to be at the same horizontal level between the fields. But what is more interesting, in the right hand field you will notice that the large particle is partially segmented, but then bottom half has not been included in for x-ray analysis. Analytical conditions are the same as the previous example I sent through, so same Grey Scale Factor.
![Missing Fields (BSE) 3](https://user-images.githubusercontent.com/84643841/126667927-c754a045-3cab-4607-9edc-51e2aea76976.JPG)
![Missing Fields (Conditions 3)](https://user-images.githubusercontent.com/84643841/126667928-d1889f67-6322-40c1-8a7b-e49dfe3b95f2.JPG)
![Missing Fields (3)](https://user-images.githubusercontent.com/84643841/126667930-3d27ad0a-8964-4126-b83e-074b6f5f1377.JPG)

**Comment by MarkGuo7** [comment]
Hi Chi, may I know which version you are using?
I fixed an issue related to this missing segments sometime in April?

**Comment by ChiLyMan** [comment]
Hey Mark,

I’ll let Nigel and Jonathan let you know the version but it looks like they didn’t update the software so I will just blame them 😁

Chi

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
