### ISSUE TITLE
Improved analysis speed by splitting out post process?

### ISSUE THREAD

**Issue by ChiLyMan** [Bruker-Amics/bugs_features#85]
I was wondering if anyone has tested to see if there are any significant decrease in analytical time by not doing any spectra matching during the data acquisitions? So during acquisition only BSE collection, Segmentation and X-Ray collection is done. The data is then save, and material characterization can then then done offline.

Just wondering if this would make any significant increase in sample through put

**Comment by jonathan-knapp** [comment]
Thanks for the idea Chi. We found speed improvements through algorithm improvements.
