### ISSUE TITLE
Hang-up on Editing Common Standards Groupings

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#88]
If I edit the Groupings from the tab in the Common Standards manager (i.e. not in Current Minerals Groupings), Process hangs when I hit OK after I have made the edits in the Mineral Standards Group window.

Not checked extent of behaviour but it happens when I create new standards but have not reprocessed the data.

Killing Process and re-opening the files shows that the edits have been made though.

**Comment by Matt-Power** [comment]
Just tried this with v.2556 and it crashes (rather than just hangs).

**Comment by MarkGuo7** [comment]
@Matt-Power Is it still there? Could you show me when you have time? Thanks

**Comment by Matt-Power** [comment]
Yes, although it seems to crash rather than hang now. I'm free anytime next week from Tuesday morning your time. About 4-6 pm PST is best for me but I'm flexible.

**Comment by MarkGuo7** [comment]
@Matt-Power Please let me know when your connection is ready. I am flexible as well, except Monday night, Tuesday night and Thursday night :)
