### ISSUE TITLE
Time remaining - 2617

### ISSUE THREAD

**Issue by knapp-amics** [Bruker-Amics/bugs_features#9]
Show used time and time remaining in status window as well number of field and total fields

**Comment by MarkGuo7** [comment]
M4 system got this issue and Gerda noticed on SEM as well.
Better fix it.

**Comment by jonathan-knapp** [comment]
The Time left calculation is wrong. Especially if the system needs to change the kV and or uA values. The calculation should be from when the Xray collection starts and not from when the start button is pushed and the kV and uA values need to change or to open the m4 software. This often leads to an extremely long calculated measurement time, and therefore is only close to reality after a period time when this start delay is averaged out.
