### ISSUE TITLE
Reporting Zero and undetected

### ISSUE THREAD

**Issue by ChiLyMan** [Bruker-Amics/bugs_features#90]
Just a suggestion, when doing the batch export of mineral data I notice that minerals with zero wt% and area% could either be not detected (i.e. zero grains) or some lower reporting limit (i.e. 1 or two grains).

Some suggestions:-
1) If it is possible to set the reporting detection limit (i.e. setting decimal points to export) and/or
2) Differentiate between "below reporting detection limit" and "mineral not detected" by using DL and ND, respectively, instead of zero?

Just a suggestion, because this might be of importance to some people to know what zero actually mean. Just an idea.

**Comment by Matt-Power** [comment]
Just to chime in, I agree with Chi but having flexibility is important so can we have user-set designations in the options menu please? 

For instance, when exporting data to spreadsheets, the "-" or any text value hiding in the data causes a bunch of errors in calculations and is a pain to weed out, especially with dozens of tabs of data (this is actually a daily issue for me). In other cases I have to fit with a client's database where ND might be 9999.99 or pretty much anything.

**Comment by ChiLyMan** [comment]
Good point Matt,

Though I've not encounter this for the AMCIS data, I do know we need to adjust elastic data to -9999.99 to align with wireline log readers. 

You would think we could have a global standard for "zero" !

**Comment by jonathan-knapp** [comment]
@van-amics can we add a user-defined value to use for each type?

**Comment by ChiLyMan** [comment]
@van-amics That might be the easiest way to do it. User can choose between "-" or "ND" or "0". Same they could choose "0" or "DL" Or "BL" etc etc.

In most cases for labs this will be fixed to fit into their nomenclature, but poor consultant need to adapt to client, but usually I just run a script to find/replace data for me anyway.

Quick question, is the number of decimal points reported already adjustable? Some people might want to report 0.0001%, for whatever reason :)

**Comment by Matt-Power** [comment]
@ChiLyMan - I think that I can answer that one:
![image](https://user-images.githubusercontent.com/84986921/128403869-a91aeec1-07b1-4651-b458-a1ba1574ef8f.png)

It's under Extras>More Options

**Comment by ChiLyMan** [comment]
Gracias

**Comment by jonathan-knapp** [comment]
ok, this is going to be super hard. We will take a look at this for the future.
