### ISSUE TITLE
Long Delay When Switching Tabs

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#94]
When switching between some tabs (e.g. from Sample Images to Calculation Tables), there is often a really long delay (several minutes) where Process appears to have hung. The progress window opens to calculate the primary but then just sits there. It eventually kicks after a few minutes. Switching between the tabs after that seems OK.

It doesn't happen all the time and is not sample-dependent. Current using v2598.

**Comment by bernie1034** [comment]
@Matt-Power   What is your file size (number of fields, approx size of the measurement folder)? I'm testing that version out right now and it's behaving normally - slight delay on switching to the Calculation Tab, but not awful. I'm testing on a file with 199 fields, and total measurement folder size of ~310Mb.

**Comment by Matt-Power** [comment]
These ones are pretty big (143 fields and 1.5Gb - it's a block measurement) but it is really patchy - sometimes it will work OK (10-20 seconds) but then other times, it seems to get stuck (always at the same point i.e. after the progress window has opened but before anything shows on the bar). It happens fairly regularly but not consistently - it can sit there on one sample but e.g. after a reclassification, that same sample might be OK.

**Comment by jonathan-knapp** [comment]
Going to delay this as we look at other speed improvements.

**Comment by jonathan-knapp** [comment]
Will be addressed in coming weeks by another issue
