### ISSUE TITLE
Black Field Boundaries With BSE Adjuster

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#95]
Just been trying the BSE adjuster - very nice, thanks! However, it generates a bunch of black lines across the image on stitched samples (see below). Any way to get rid of these without re-stitching?

![image](https://user-images.githubusercontent.com/84986921/129976383-138af8d9-6977-41bd-976c-f243381c2c30.png)

**Comment by jonathan-knapp** [comment]
I want to be able to demonstrate this feature, and this is not great. It will come up every time. Must fix.
