### ISSUE TITLE
Spectra Do Not Update When Selected With Cursor Keys

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#96]
When cycling through the standards list using the keyboard in either the common standards or current mineral groupings tabs, the spectra do not change. It appears that there is no way to use the keyboard in this list as hitting enter, space bar, tab etc does nothing.  They only change with a mouse click.

Need keyboard functionality for backup (e.g. when mouse battery dies), accessibility for people who can't use mice and simply being able to quickly scroll through and review the standards using the cursor keys which is really useful (and saves more mouse clicks / RSI).

**Comment by jonathan-knapp** [comment]
We will implement this in AMICS 3.4. Good idea!

**Comment by jonathan-knapp** [comment]
@Matt-Power we think this is a GREAT idea to have keyboard shortcuts. We can do this. Can you please come up with a list of shortcuts you want and we will implement them?

**Comment by Matt-Power** [comment]
Almost too many areas to list but to start with: 
Standard spectra to change to that selected as you cycle through with the cursor keys
Keyboard shortcut to copy data and name / copy data to current mineral
Shortcuts to zoom and pan in the all image screens
Key combo to switch between BSE and Mineral images (and separate key to switch to the secondary channel if available)
Tab (or similar) to switch to different mineral groups and a special key combo to change all tabs to a mineral group
Some sort of escape key combo to break out of a process that is taking to long / stalled and bring you back to e.g. the image view
