### ISSUE TITLE
Mineral Order in Batch Export

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#99]
Really like the ability to export the data grouped into separate tabs for area %, wt % etc, thank you. 

However, the minerals are now in alphabetical order, not as set in AMICS. The order from Process should be retained by default and only changed as an option (i.e. a drop down with the option to order as in Process (default), alphabetically, by mineral abundance etc would be ideal).

I spend a lot of time ordering the mineral list to make it consistent with previous projects (it's never alphabetical unfortunately) and this order is carried across various projects too. It also means that the mineral legend does not match the order in the datasheet (which is important). Might seem like a small niggle but reordering in Excel is a pain (even with vba / macros) and would mean a lot of repeated effort for every project.

**Comment by GGloy** [comment]
Hi Matt,  please try build 2606.  Should be fixed in this one (according to my tests work)

**Comment by Matt-Power** [comment]
Perfect, thanks!
